### ISSUE TITLE
Error when interacting with a paragraph block

### ISSUE THREAD

**Issue by versatilehuman** [WordPress/gutenberg#10972]
**Describe the bug**
Gutenberg 4.0.0 & 4.1 RC2: Any time a paragraph block is clicked, this error appears: "The editor has encountered an unexpected error." This happens in any post type using the Gutenberg editor. It occurs with new and existing posts.

**To Reproduce**
1. Click "Posts"
2. Click "Add New" or click "Edit" on an existing post
3. Click on any paragraph block or create new paragraph block

**Expected behavior**
Being able to edit/add paragraph blocks.

**Screenshots**
![image](https://user-images.githubusercontent.com/7032169/47391282-02555d00-d6df-11e8-9f29-d1bdd1865d17.png)

![image](https://user-images.githubusercontent.com/7032169/47391352-2d3fb100-d6df-11e8-96d0-b1bdf18f8f71.png)

![image](https://user-images.githubusercontent.com/7032169/47391714-29f8f500-d6e0-11e8-82ee-7be010a7601e.png)

**Additional context**
- Problem present in Gutenberg 4.0.0 & 4.1 RC2, but not 3.9.0 or previous.
- WordPress 4.9.8
- Windows 7 64-bit
- Chrome 69.0.3497.100
- Problem present in Gutenberg 4.0.0, but not 3.9.0 or previous versions.
- Problem persists even after deactivating all plugins

**Comment by versatilehuman** [comment]
Is there any further information I can pull to help figure this out?

Same Error in IE 11.0.9600.19129:

```
TypeError: Object doesn't support property or method 'find'
   at Anonymous function (/wp-content/plugins/gutenberg/build/components/index.js?ver=1540390037:37:248589)
   at yh (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:95:428)
   at lg (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:82)
   at mg (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:384)
   at gc (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:200)
   at vb (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
   at ub (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
   at wg (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
   at Ze (
/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)
```
Error in Chrome 69.0.3497.100:
```
TypeError: r.find is not a function
    at /wp-content/plugins/gutenberg/build/components/index.js?ver=1540390037:37:248593
    at yh (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:95:430)
    at lg (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)
    at vb (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at wg (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
    at Ze (/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)
```

**Comment by versatilehuman** [comment]
Updated to reflect that the issue only occurs with paragraph blocks.

**Comment by versatilehuman** [comment]
Resolved. 

Was using this empty add_theme_support hack to remove font size options. 

```
function fpdcc_gutenberg_disable_all_colors() {
	add_theme_support( 'editor-font-sizes' );
}
add_action( 'after_setup_theme', 'fpdcc_gutenberg_disable_all_colors' );
```
