### ISSUE TITLE
Add New Page error

### ISSUE THREAD

**Issue by DanielNoakes** [WordPress/gutenberg#11972]
I get this error when I try to add a new page in Wordpress:

Invariant Violation: Minified React error #130
  
And I don't get a new page!

I simply go to:
1. Pages
2. Add New
3. then i get the error (instead of a new page)

I've now disabled the plugin, and it works perfectly well again...

I'm using Windows 10 on a PC, and am in the latest version of Chrome (Version 70.0.3538.102 (Official Build) (64-bit))

I was using version Version 5.3.5 of Gutenburg when the error occurred.

**Comment by swissspidy** [comment]
> I get this error when I try to add a new page

Would you mind sharing the full error message with us please? A screenshot would be helpful too.

> I've now disabled the plugin, and it works perfectly well again...

Have you tried disabling all other plugins except Gutenberg to see if this error still persists?

> I was using version Version 5.3.5 of Gutenburg when the error occurred.

Gutenberg is only at version 4.4.0 though 🤔 And WordPress is at version 5.0 Beta 5.

**Comment by DanielNoakes** [comment]
The full error is

 

Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

    at Sg (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:142:327)

    at m (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:12:388)

    at ed (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:65:98)

    at https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:87:294

    at rd (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:10)

    at O (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:90:455)

    at yh (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:104:145)

    at lg (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)

    at mg (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)

    at gc (https://www.envoprint.co.uk/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)

 

trust this helps

**Comment by bgbruno** [comment]
this exist after today update
yesterday was all OK

I have the same issue but with different error
also existing pages I cannot open

TypeError: Cannot set property 'props' of undefined
    at r (/wp-content/plugins/wp-log-viewer/assets/js/main.min.js?ver=4.9.8:2:15393)
    at t (/wp-content/plugins/gutenberg/build/editor/index.js?ver=1542789922:55:4348)
    at ph (/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:97:88)
    at eg (/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:125:307)
    at fg (/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:126:168)
    at wc (/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:138:237)
    at fa (/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:137:115)
    at gg (/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:135:196)
    at Ca (/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:133:365)
    at Object.enqueueSetState (/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:191:324)

**Comment by bgbruno** [comment]
yap @swissspidy thx I didn't noticed that from that error - with previous versions #gutenberg all is OK

I write to #wplogviewer about this error

**Comment by swissspidy** [comment]
Thanks!

I'm closing this issue for now. If new information emerges about the compatibility of these plugins, we can always re-open.
