### ISSUE TITLE
Error: wp.Media is not a function

### ISSUE THREAD

**Issue by LensflarePhoto** [WordPress/gutenberg#12492]
I can no longer open any page or post I have created or edited in Gutenberg, although they can be edited using the classic editor.

When I attempt to open the page or post I receive the following message: 

"The editor has encountered an unexpected error" with the following error text:

TypeError: wp.media is not a function
    at new t (http://lensflarephoto.com/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=1543623257:12:5273)
    at zf (http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:69:258)
    at Mf (http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:87:4)
    at ph (http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:98:474)
    at eg (http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:125:307)
    at fg (http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:126:168)
    at wc (http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:138:237)
    at fa (http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:137:115)
    at gg (http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:135:196)
    at Ca `(http://lensflarephoto.com/wp-content/plugins/gutenberg/vendor/react-dom.min.713f0afa.js:133:365)

I have tried disabling all of my other plugins other than Gutenberg and the issue remains.  Any help would be appreciated?

**Comment by swissspidy** [comment]
Which version of Gutenberg and WordPress are you using? Does this still happen with one of the default themes active?

Does this happen when creating new posts or only when trying to edit existing ones?

**Comment by designsimply** [comment]
If you are using Gutenberg is a plugin, does the problem go away when you deactivate Gutenberg?

I searched here and found two similar cases reporting the `TypeError: wp.media is not a function` error. 

In #9717, they solved the problem by switching to a different internet connection (which sounds strange and it's worth noting they also did a fresh install of WordPress prior to getting everything working). 

In #7643, they noted the same error appears when the Wordfence plugin is active. If you had a similar plugin that you deactivated for testing, did you also try clearing cache after doing that to make sure you've checked that change thoroughly?

**Comment by LensflarePhoto** [comment]
Thanks for your help guys, after disabling all of my plugins one by one again, I cleared my cache in my browser and the issue has cleared now.

For future reference, the issue was that basically couldn't load the Gutenberg plugin at all from the wp-admin portal, whether it be to edit an existing post/page or create a new one.  

Version of the Gutenberg plugin was 4.6.1 in Wordpress 4.9.8.

**Comment by designsimply** [comment]
@LensflarePhoto thank you so much for the follow-up! If you happen to find out which plugin caused the trouble, please reply again and let me know so I can make a note of it in the title (which helps others in searches).

**Comment by afeiship** [comment]
```js
import { removeFilter } from '@wordpress/hooks';

removeFilter(
      'editor.MediaUpload',
      'core/edit-post/components/media-upload/replace-media-upload'
);
```
