### ISSUE TITLE
wp_post_lock_check fatal with Frontenberg

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#13407]
When running Frontenberg with Gutenberg v4.8 activated on WordPress 5.0.3 the following stack trace occurs:

```
<br /><b>Fatal error</b>: Uncaught Error: Call to undefined function wp_check_post_lock() in /srv/www/tomjn.com/htdocs/wp-content/plugins/gutenberg/lib/client-assets.php:1222
Stack trace:
#0 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(286): gutenberg_editor_scripts_and_styles('')
#1 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters(NULL, Array)
#2 /srv/www/tomjn.com/htdocs/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
#3 /srv/www/tomjn.com/htdocs/wp-includes/script-loader.php(2231): do_action('wp_enqueue_scri...')
#4 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('')
#5 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters(NULL, Array)
#6 /srv/www/tomjn.com/htdocs/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
#7 /srv/www/tomjn.com/htdocs/wp-includes/general-template.php(2614): do_action('wp_head')
#8 /srv/www/tomjn.com/htdocs/wp-content/themes/Frontenberg/header.php(7): wp_head()
#9 /srv/www/tomjn.com/htdoc in <b>/srv/www/tomjn.com/htdocs/wp-content/plugins/gutenberg/lib/client-assets.php</b> on line <b>1222</b><br />
```

**Comment by tomjn** [comment]
In particular it appears this is done to check the post locking to conditionally set `$lock` to true, but, if I've already gone to the lengths of disabling the post locking functionality ( which I have ), is there really any point in calling it?

**Comment by designsimply** [comment]
@adamsilverstein I know that you have worked on post locking issues in the past. Any chance you might have a moment to help take a look at this issue?! Also @dd32 since you mentioned http://wordpress.org/gutenberg is based on @tomjn's frontenberg code at https://wordpress.slack.com/archives/C02QB8GMM/p1547091694186400.

**Comment by tomjn** [comment]
My current thinking since post locking on the frontend is never desirable is to monkey patch with something like this:

```php
if ( !function_exists( 'wp_check_post_lock' ) ) {
    function wp_check_post_lock () {
        return false;
    }
}
```

But this is suboptimal. I would imagine this would become an issue if post locking were ever needed in a REST endpoint too

**Comment by adamsilverstein** [comment]
I'll take a look!

**Comment by tomjn** [comment]
I don't think this happens with Frontenberg in Gutenberg 4.9, my immediate thinking is that if it crops up again a mock function that returns false will help, but, it would be nice if this was filterable instead so that I could simply unhook or replace the relevant part of bootstrapping

**Comment by adamsilverstein** [comment]
> post locking on the frontend is never desirable

Curious why this is? what happens if two users edit the same post at the same time in Frontenberg and both try to save, will the second save fail?

So your goal would be to short circuit the gutenberg checks for the the locked post?  can you send me the link to where that wp_check_post_lock call is made?

**Comment by dd32** [comment]
For reference, for WordPress.org/gutenberg we worked around it by loading the file, not showing the lock dialogue, and always having the post locked by the @wordpressdotorg user:
https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/gutenberg/functions.php?marks=173-175,184-185,191-201#L170

**Comment by tomjn** [comment]
> Curious why this is? what happens if two users edit the same post at the same time in Frontenberg and both try to save, will the second save fail?

@adamsilverstein for my usage and the various projects that inherit from Frontenberg, post locking is problematic. The ability for users to do anything with persistence is gone if not mostly eliminated, so they can't save.

The problem comes when a site admin/author logs in and goes to that post, and it gets locked. Now nobody else can use the site as intended, the entire UI is locked out behind a modal dialog that can't be dismissed

**Comment by adamsilverstein** [comment]
> The problem comes when a site admin/author logs in and goes to that post, and it gets locked. Now nobody else can use the site as intended, the entire UI is locked out behind a modal dialog that can't be dismissed

@tomjn I investigated this a bit further... 

you can disable post lock checking at load time with the `show_post_locked_dialog` filter, https://github.com/WordPress/gutenberg/blob/317b21910ec6e8664fdb3d2511cad2238cabcafb/lib/client-assets.php#L1083 

Returning false will have GB ignore whether the post was locked initially.

`add_filter( 'show_post_locked_dialog', '__return_false' );`

To disable subsequent post locking if two people are editing the post) I would try to remove the hooked callbacks (like this https://github.com/WordPress/gutenberg/blob/95edac1e42cb10ed7da9f406696cdc85d6e476d5/packages/editor/src/components/post-locked-modal/index.js#L44-L45) - if you can't get at that hookName with its instanceId, another option would be to add an earlier priority filter that cleared the locking data, something like:

```js
addFilter( 'heartbeat.tick', 'myplugin', function ( data ) {  
    data['wp-refresh-post-lock'] = false; 
    return data;
}, 9 );
```

Hope that helps.

**Comment by tomjn** [comment]
@adamsilverstein I've already got a lot of anti-post locking measures that are quite effective.

The root problem of this ticket is that I updated the Gutenberg plugin and got PHP fatal errors for `wp_post_lock_check`, this doesn't seem to happen with the latest release of the plugin at the moment, but I'm unsure if this is because the issue is resolved, or because of how the site is configured

Moving the lock checking call into a filter means I can unhook it, fixing the original issue and avoiding the problem, while providing additional benefits

**Comment by adamsilverstein** [comment]
Ah, got it. Sounds reasonable.

**Comment by ramonjd** [comment]
If folks still think this issue is relevant in 2025, please reopen. Thank you!
