### ISSUE TITLE
`@wordpress/data` build uses variables before they are declared.

### ISSUE THREAD

**Issue by nerrad** [WordPress/gutenberg#15031]
**Describe the bug**
In my plugin I import WordPress packages as `devDependencies` solely for the purpose of testing components that utilize them.  Today I updated from an earlier version of `@wordpress/data` to the latest version and the following error started appearing in one of my tests:

<details>
<summary>click for error details</summary>

```
TypeError: Cannot read property 'default' of undefined

      51 |                                      'invalid'
      52 |                              ) ).toEqual( null );
    > 53 |                      } );
         |                                    ^
      54 |                      it( 'returns expected value for model in state', () => {
      55 |                              expect( selectorToTest(
      56 |                                      mockStateForTests,

      at Object.get [as withSelect] (node_modules/@wordpress/data/build/index.js:20:24)
      at assets/src/data/eventespresso/schema/test/selectors.js:53:452
          at Array.forEach (<anonymous>)
      at _objectSpread (assets/src/data/eventespresso/schema/test/selectors.js:53:392)
      at Object.user:/Users/dethier/webprojects/vagrant/www/ee-alpha-testing/wp-content/plugins/event-espresso-core/node_modules/@wordpress/data/build/index.js: (assets/src/data/eventespresso/schema/test/selectors.js:27:31)
      at Object.<anonymous> (node_modules/@wordpress/data/build/plugins/persistence/@wordpress/data/src/plugins/persistence/index.js:10:1)
      at Object.<anonymous> (node_modules/@wordpress/data/build/plugins/@wordpress/data/src/plugins/index.js:2:1)
      at Object.<anonymous> (node_modules/@wordpress/data/build/index.js:78:39)
      at Object.requireActual [as user:/Users/dethier/webprojects/vagrant/www/ee-alpha-testing/wp-content/plugins/event-espresso-core/node_modules/@wordpress/data/build/index.js:] (assets/src/data/eventespresso/schema/test/selectors.js:28:13)
      at Object.<anonymous> (assets/src/data/eventespresso/base-selectors.js:4:1)
      at Object.<anonymous> (assets/src/data/eventespresso/schema/selectors.js:4:1)
      at Object.<anonymous> (assets/src/data/eventespresso/schema/test/selectors.js:4:1)
```
</details>

From the trace, the `build/index.js` file is throwing this error at the line with this code:

```js
Object.defineProperty(exports, "withSelect", {
  enumerable: true,
  get: function get() {
    return _withSelect.default; /** <-- this line **/
  }
});
```

I discovered that this will start throwing an error beginning with `@wordpress/data@4.3.0`.  At first I thought it was due to a hoisting issue because `_withSelect` is defined later in the same file.  If I move all those definitions earlier than the `Object.defineProperty` call things work.

However, the built file is similar in versions before `4.3.0` and the tests run fine on them.

So, I'm just leaving this issue open for now and will try to figure out what's going on but thought I'd post this in case anyone has ideas for what may be happening. (@gziolo, @ntwb any ideas?)

Failing test job: https://travis-ci.com/eventespresso/event-espresso-core/jobs/193833933
Test code failing: https://github.com/eventespresso/event-espresso-core/blob/d44f72c1f6abbdba6bb36e6553b5154919eb5cfb/assets/src/data/eventespresso/schema/model.js

**Comment by nerrad** [comment]
I wonder if it is the changes in the `@babel/runtime` package dependency versions between 4.2.1 and 4.3.0?  In other words, it has to with the `_interopRequireWildcard` and `interopRequireDefault` functions imported from `@babel/runtime`?

**Comment by nerrad** [comment]
Ahh, looks like I needed to update other @wordpress packages too because of mismatch between the @babel/runtime and the core-js version.  So it was a configuration issue on my end.

**Comment by nerrad** [comment]
For those who may stumble on this issue.  I'm still not sure exactly what is going on but it's clear its some sort of loading issue with the various packages in play.  It stems from using `requireRequireActual` in some of the tests I had setup in my plugin for mocking parts of the `@wordpress/data` and keeping the other imported values the same.  This ultimately is causing the error.  Uncertain whether this is a jest or babel problem (or configuration) but for now, changing how I was mocking things fixed the issue in my tests.
