### ISSUE TITLE
Playground won't run - cannot resolve dependency core-js/modules/es6.array...

### ISSUE THREAD

**Issue by timhibberd** [WordPress/gutenberg#16082]
**Describe the bug**
Playground won't run - cannot resolve dependency core-js/modules/es6.array...

` ×  K:\SkyBindProjects\gutenberg\playground\src\index.js: Cannot resolve dependency 'core-js/modules/es6.array.copy-within'
at Resolver.resolve (K:\SkyBindProjects\gutenberg\node_modules\parcel-bundler\src\Resolver.js:71:17)
 at async Bundler.resolveAsset (K:\SkyBindProjects\gutenberg\node_modules\parcel-bundler\src\Bundler.js:433:18)
at async Bundler.resolveDep (K:\SkyBindProjects\gutenberg\node_modules\parcel-bundler\src\Bundler.js:484:14)
 at async K:\SkyBindProjects\gutenberg\node_modules\parcel-bundler\src\Bundler.js:608:26
 at async Promise.all (index 4)
 at async Bundler.loadAsset (K:\SkyBindProjects\gutenberg\node_modules\parcel-bundler\src\Bundler.js:599:21)
 at async K:\SkyBindProjects\gutenberg\node_modules\parcel-bundler\src\Bundler.js:610:13
 at async Promise.all (index 0)
 at async Bundler.loadAsset (K:\SkyBindProjects\gutenberg\node_modules\parcel-bundler\src\Bundler.js:599:21)
 at async Bundler.processAsset (K:\SkyBindProjects\gutenberg\node_modules\parcel-bundler\src\Bundler.js:557:5)`

**To reproduce**

1. install node (https://nodejs.org/en/download/)
2. clone gutenberg (https://github.com/WordPress/gutenberg.git)
3. npm install --save-dev --save-exact @wordpress/scripts
4. npm run playground:start

NOTE: attempts to install core-js (npm install --save core-js) do not resolve this issue.

**Expected behavior**
Gutenberg playground available at localhost:1234

**Screenshots**
None applicable.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser not an issue
 - Version not an issue

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
- Gutenberg latest version

**Comment by zakalwe2016** [comment]
Very similar issue. I got:

```
🚨  /var/www/dev/gutenberg/playground/src/index.js: Cannot resolve dependency 'core-js/modules/es6.array.fill'
[1]     at Resolver.resolve (/var/www/dev/gutenberg/node_modules/parcel-bundler/src/Resolver.js:71:17)
```

**Comment by timhibberd** [comment]
The file exists in my node_modules directory but with a node_modules/core-js/modules/es.array prefix rather than the expected node_modules/core-js/modules/es6.array prefix. It's like the es6 processor is not being run or is being run but not setting the prefix properly.

**Comment by swissspidy** [comment]
#15947 should fix this.

**Comment by timhibberd** [comment]
Thanks @swissspidy @jorgefilipecosta much appreciated :-)

NOTE: Unfortunately now the master branch does not build at all for me. I have added a new Issue: https://github.com/WordPress/gutenberg/issues/16099
