### ISSUE TITLE
Embeds: handle `allow-presentation` JS error

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#1655]
Since we started sandboxing embeds (yay 🎉), this error shows up in Chrome:

```
Uncaught DOMException: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.
    at V.P (chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm/cast_sender.js:76:87)
    at Object.chrome.cast.P (chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm/cast_sender.js:91:165)
    at g.iI.g.h.init (https://www.youtube.com/yts/jsbin/player-vfleyMpxV/en_US/base.js:5817:509)
    at Swa (https://www.youtube.com/yts/jsbin/player-vfleyMpxV/en_US/remote.js:10:96)
    at Zwa (https://www.youtube.com/yts/jsbin/player-vfleyMpxV/en_US/remote.js:25:8)
    at window.chrome.window.chrome.cast.window.chrome.cast.isAvailable.window.__onGCastApiAvailable (https://www.youtube.com/yts/jsbin/player-vfleyMpxV/en_US/remote.js:60:200)
    at Object.chrome.cast.ea (chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm/cast_sender.js:94:152)
    at chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm/cast_sender.js:94:204
    at chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm/cast_sender.js:94:326
```

I suspect the steps to reproduce, aside from using Chrome, is to have a Google Chromecast on your network. The error is likely from the YouTube embed in the demo content.

It's not necessary for users to be able to cast their YouTube videos, but it'd be nice if we could prevent the error from showing up. And per this https://stackoverflow.com/questions/30183320/iframe-sandboxing-with-allow-same-origin-flag-error, it's probably a matter of adding an attribute somewhere.

**Comment by dovk** [comment]
```
      <iframe [src]="url"
              frameborder="1"
              sandbox="allow-scripts allow-same-origin allow-presentation">
```
worked for me

**Comment by kwight** [comment]
@notnownikki @jasmussen Why was this issue closed? Was it handled somewhere, or did we think it wasn't worth taking action?

**Comment by jasmussen** [comment]
Let's reopen and revisit!

**Comment by adamziel** [comment]
@kwight I think it was closed after this PR was merged: https://github.com/WordPress/gutenberg/pull/1657

Since the PR mentions it fixed the error, I'm going to close this one. Feel free to reopen if the error comes back.
