### ISSUE TITLE
Gutenberg Standalone

### ISSUE THREAD

**Issue by futureweb** [WordPress/gutenberg#16967]
Hey there,
is it planed to make Gutenberg available Standalone without WP?
Would love to integrate it's functionality within our own CMS ...
thx, bye from Austria
Andreas S.

**Comment by Soean** [comment]
Hi Andreas,
there is a Gutenberg [Drupal Version](https://www.drupal.org/project/gutenberg) and for [Laraberg  for Laravel](https://github.com/VanOns/laraberg).  So it is already possible.

We also have the [playground](https://github.com/WordPress/gutenberg/tree/master/playground) in this repository, which is a minimal Gutenberg version without WordPress. You can run it via `npm run playground:build` and `npm run playground:start`.

**Comment by futureweb** [comment]
Hey Soean,
didn't know about the Laravel Implementation so far.
Even I don't use Laravel maybe that could be a possible way to integrate it into our CMS ... Will have a look into it ... thx! ;-)

**Comment by futureweb** [comment]
Well ... seems like I already struggle with trying out the Playground ... 
npm install fails with 
```
npm WARN enzyme-to-json@1.6.0 requires a peer of enzyme@^2.7.1 but none was installed.
npm WARN react-native@0.60.0 requires a peer of react@16.8.6 but none was installed.
```

When trying to install enzyme it tells me that it's missing react
When trying to install react it tells me it's missing enzyme ...

*sigh*

Any ideas on how to escape this lockdown?!?

**Comment by futureweb** [comment]
Well ... semms like I already struggle at building the Playground ... *sigh*

 ```
cat /daten/www/futureweb/gutenberg/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'playground:build' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'preplayground:build',
4 verbose run-script   'playground:build',
4 verbose run-script   'postplayground:build' ]
5 info lifecycle gutenberg@6.2.0~preplayground:build: gutenberg@6.2.0
6 silly lifecycle gutenberg@6.2.0~preplayground:build: no script for preplayground:build, continuing
7 info lifecycle gutenberg@6.2.0~playground:build: gutenberg@6.2.0
8 verbose lifecycle gutenberg@6.2.0~playground:build: unsafe-perm in lifecycle true
9 verbose lifecycle gutenberg@6.2.0~playground:build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/daten/www/futureweb/gutenberg/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
10 verbose lifecycle gutenberg@6.2.0~playground:build: CWD: /daten/www/futureweb/gutenberg
11 silly lifecycle gutenberg@6.2.0~playground:build: Args: [ '-c',
11 silly lifecycle   'npm run build:packages && parcel build playground/src/index.html -d playground/dist' ]
12 silly lifecycle gutenberg@6.2.0~playground:build: Returned: code: 1  signal: null
13 info lifecycle gutenberg@6.2.0~playground:build: Failed to exec playground:build script
14 verbose stack Error: gutenberg@6.2.0 playground:build: `npm run build:packages && parcel build playground/src/index.html -d playground/dist`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid gutenberg@6.2.0
16 verbose cwd /daten/www/futureweb/gutenberg
17 error Linux 3.10.0-957.10.1.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "playground:build"
19 error node v6.17.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error gutenberg@6.2.0 playground:build: `npm run build:packages && parcel build playground/src/index.html -d playground/dist`
22 error Exit status 1
23 error Failed at the gutenberg@6.2.0 playground:build script 'npm run build:packages && parcel build playground/src/index.html -d playground/dist'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the gutenberg package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build:packages && parcel build playground/src/index.html -d playground/dist
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs gutenberg
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls gutenberg
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by youknowriad** [comment]
The playground is also available here and built on each master merge, so it should be working properly https://wordpress.github.io/gutenberg/

Make sure to update your node/npm versions to the last LTS at least.
