### ISSUE TITLE
Fresh build of the plugin fails

### ISSUE THREAD

**Issue by wpscholar** [WordPress/gutenberg#21116]
**Describe the bug**
Running `npm run build` (after running `npm install`) on a fresh Gutenberg clone fails.

Before failing, the result is a wall of errors similar to this:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/wpscholar/Sites/LocalSites/gutenberg/app/public/wp-content/plugins/gutenberg/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:524:9)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/wpscholar/Sites/LocalSites/gutenberg/app/public/wp-content/plugins/gutenberg/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10) {
  type: 'NodeError',
  '$error': '$error',
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

**To reproduce**
1. Git clone the master branch of the Gutenberg repo.
2. Run `npm install`
3. Run `npm run build`
4. Build appears to work at first, but then results in a wall of errors before finally failing.

**Workaround**
I'm able to get the build to work by running `npm install node-sass --save` and then running `npm run build`. Even though doing this doesn't change the `node-sass` version, it updates other dependencies such that things work properly. 

I'm attaching my working `package-lock.json` file and a copy of the log file after running the `npm run build` command.

- [2020-03-24T15_55_18_698Z-debug.log](https://github.com/WordPress/gutenberg/files/4376830/2020-03-24T15_55_18_698Z-debug.log)
- [package-lock.json.log](https://github.com/WordPress/gutenberg/files/4376835/package-lock.json.log) - This is a JSON file, but I had to add the `.log` extension to the end in order for GitHub to allow me to upload it.

**Expected behavior**
I expected the build to succeed.

**Additional context**
- I tested in 3 different Unix/Linux environments with the same results.
- I tested using Node 10, 12, and 13 with the same results.
- I'm specifically on the `192bcf42d2b618120ce17f1b1e4c9d39bf53c9ce` commit on `master`.

**Comment by gziolo** [comment]
Can you open PR that solves the issue for you? I’m happy to test it locally and land it if it still works 👍

**Comment by wpscholar** [comment]
Sorry, this appears to have resolved itself with later Gutenberg updates.
