### ISSUE TITLE
[eslint-plugin] Update to 5.0.0 breaks eslint

### ISSUE THREAD

**Issue by marekdedic** [WordPress/gutenberg#21614]
**Describe the bug**
Updating `@wordpress/eslint-plugin` breaks eslint.

**To reproduce**
```sh
$ npm run lint:ts:eslint

> crdm-modern@0.2.2 lint:ts:eslint /home/user/project
> eslint src/**/*.ts gulpfile.ts

Error: Failed to load plugin '@wordpress/eslint-plugin' declared in '.eslintrc.json': Cannot find module '../utils'
Require stack:
- /home/user/project/node_modules/@wordpress/eslint-plugin/rules/i18n-ellipsis.js
- /home/user/project/node_modules/requireindex/index.js
- /home/user/project/node_modules/@wordpress/eslint-plugin/configs/index.js
- /home/user/project/node_modules/@wordpress/eslint-plugin/index.js
- /home/user/project/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /home/user/project/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /home/user/project/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/user/project/node_modules/eslint/lib/cli-engine/index.js
- /home/user/project/node_modules/eslint/lib/cli.js
- /home/user/project/node_modules/eslint/bin/eslint.js
Referenced from: /home/user/project/.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/home/user/project/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/user/project/node_modules/@wordpress/eslint-plugin/rules/i18n-ellipsis.js:9:5)
    at Module._compile (/home/user/project/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! crdm-modern@0.2.2 lint:ts:eslint: `eslint src/**/*.ts gulpfile.ts`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the crdm-modern@0.2.2 lint:ts:eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-04-15T14_31_23_830Z-debug.log
```

See skaut/crdm-modern#160 and https://circleci.com/gh/skaut/crdm-modern/1488.

**Expected behavior**
Either a succesfull lint or an error, but not a crash

**Desktop (please complete the following information):**
 - Debian testing

**Comment by marekdedic** [comment]
Fixed in #21609, thanks!
