### ISSUE TITLE
Update node-sass to 4.13 to compatible with latest MacOS

### ISSUE THREAD

**Issue by rilwis** [WordPress/gutenberg#21634]
When I run `npm run dev` or `npm run build`, I see this error:

```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (79)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.12.0
    at module.exports (/Library/WebServer/Documents/metaboxplugins/wp-content/plugins/gutenberg/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Library/WebServer/Documents/metaboxplugins/wp-content/plugins/gutenberg/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/Library/WebServer/Documents/metaboxplugins/wp-content/plugins/gutenberg/bin/packages/build-worker.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
/Library/WebServer/Documents/metaboxplugins/wp-content/plugins/gutenberg/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
```

Looking into the `node_modules` folder, I found `node-sass` version is 4.12 which is not compatible with MacOS 13 (see this [link](https://github.com/sass/node-sass/releases/tag/v4.12.0)).

The node-sass project also confirms the version 4.13.1 is compatible with the latest MacOS, see this [link](https://github.com/sass/node-sass/releases/tag/v4.13.1).

I'd suggest updating dependencies in `package.json` to make the development easier.

**Comment by Soean** [comment]
node-sass 4.13 adds support for Node 13 not MacOS. Try to run `npm rebuild node-sass`. After the rebuild you should be able to run the dev and build command.

**Comment by rilwis** [comment]
I see.

I've resolved it for myself by running `npm i node-sass@4.13.1`. It upgraded `node-sass` to the latest version.

So everything is fine now.
