### ISSUE TITLE
Error at launch 

### ISSUE THREAD

**Issue by Romaixn** [WordPress/gutenberg#21641]
**Describe the bug**
`wp-env start` doesn't want to start. 

**To reproduce**
I just launch `wp-env start` in the directory of a Wordpress Plugin.

**Screenshots**
```
✖ config.pluginSources.flatMap is not a function
TypeError: config.pluginSources.flatMap is not a function
    at buildDockerComposeConfig (/usr/local/share/.config/yarn/global/node_modules/@wordpress/env/lib/build-docker-compose-config.js:20:44)
    at initConfig (/usr/local/share/.config/yarn/global/node_modules/@wordpress/env/lib/init-config.js:35:30)
```

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by Soean** [comment]
You are probably using an old Node version, see #20661
