### ISSUE TITLE
E2E Tests: Intermittent failure in Quote tests

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#22430]
Related: https://github.com/WordPress/gutenberg/pull/22377#issuecomment-630348481

**Examples:**

- https://travis-ci.com/github/WordPress/gutenberg/jobs/336142279

**Error:**

```
FAIL packages/e2e-tests/specs/editor/blocks/quote.test.js (71.035s)

  ● Quote › can be merged into from a paragraph
    TypeError: Cannot read property 'click' of undefined
      at _callee$ (../e2e-test-utils/build/@wordpress/e2e-test-utils/src/insert-block.js:12:8)
      at tryCatch (../../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../../node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
          at runMicrotasks (<anonymous>)
```

**Recent Changes to Relevant Code:**

- `insertBlock` utility was changed in #21368, largely reverted in #22377

**Debugging:**

Possible leads:

- If there's no "Quote" or "Paragraph" button to click on, is it possible that these blocks are disabled by some means or another? (block manager, etc)
- The XPath selector used for finding the inserter item is extremely broad and could match other elements on the page (any `span` within a `button` that contains the text "Quote" or "Paragraph"). That said, based on the error message, it's unclear why the first member would be `undefined` if it were matching another element.
   - https://github.com/WordPress/gutenberg/blob/4fd5ba0e01a978022f3e8805dd37c8747e6228f3/packages/e2e-test-utils/src/insert-block.js#L15
   - Related: #18771

**Comment by gziolo** [comment]
@youknowriad did you manage to fix it?

**Comment by youknowriad** [comment]
I can't guarantee 100% I did fix intermittent failures on the Quote test but the error was different. Maybe we can close and reopen if it happens again.
