### ISSUE TITLE
Hey I would to report there is an error install

### ISSUE THREAD

**Issue by mewt** [WordPress/gutenberg#22617]
Hey I would to report there is an error install

`sudo npm install -g @wordpress/env
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
^T[            ......] - extract:json-schema: sill extract json-schema@0.2.3 extracted to /usr/lib/node_modules/.staging/js/usr/bin/wp-env -> /usr/lib/node_modules/@wordpress/env/bin/wp-env

> nodegit@0.26.5 install /usr/lib/node_modules/@wordpress/env/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Pre-built binaries not installable for nodegit@0.26.5 and node@14.2.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/build'
gyp
WARN
EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.2.0"
gyp
WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/.node-gyp"
gyp
WARN install got an error, rolling back install
gyp
WARN install got an error, rolling back install
gyp
ERR! configure error
gyp ERR!
stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/.node-gyp'
gyp
ERR! System Linux 5.6.12-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd
/usr/lib/node_modules/@wordpress/env/node_modules/nodegit
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp
ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/@wordpress/env/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp
ERR! System Linux 5.6.12-1-MANJARO
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/@wordpress/env/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/@wordpress/env/node_modules/nodegit
node-pre-gyp ERR! node -v
v14.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/usr/lib/node_modules/@wordpress/env/node_modules/nodegit/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.26.5 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.26.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-24T04_51_37_658Z-debug.log
`

_Originally posted by @mewt in https://github.com/WordPress/gutenberg/pull/20002#issuecomment-633179188_

**Comment by mewt** [comment]
The error solved. ZSH ins't recognize new update npm.
