### ISSUE TITLE
E2E Tests: Intermittent failure in Meta Attribute Block tests

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#22795]
**Error:**

```
FAIL packages/e2e-tests/specs/editor/plugins/meta-attribute-block.test.js (30.948s)
  Block with a meta attribute
    Early Registration
      ✓ Should persist the meta attribute properly (4652ms)
      ✕ Should use the same value in all the blocks (4896ms)
      ✓ Should persist the meta attribute properly in a different post type (5641ms)
    Late Registration
      ✓ Should persist the meta attribute properly (4618ms)
      ✓ Should use the same value in all the blocks (4537ms)
      ✓ Should persist the meta attribute properly in a different post type (5071ms)
  ● Block with a meta attribute › Early Registration › Should use the same value in all the blocks
    expect(received).toBe(expected) // Object.is equality
    Expected: "Meta Value"
    Received: "Meta ValueTest Meta Attribute Block (Early Registration)"
      65 | 						await input.click();
      66 | 						const inputValue = await input.getProperty( 'value' );
    > 67 | 						expect( await inputValue.jsonValue() ).toBe(
         | 						                                       ^
      68 | 							'Meta Value'
      69 | 						);
      70 | 					} )
      at specs/editor/plugins/meta-attribute-block.test.js:67:46
          at runMicrotasks (<anonymous>)
          at async Promise.all (index 1)
      at Object.<anonymous> (specs/editor/plugins/meta-attribute-block.test.js:59:5)
```

**Possible Leads:**

- Meta values are "global" and could be changing outside the scope of the test
- Noting that the received text includes the block name, possible conflict with how block is inserted using that string earlier in the same test case (`insertBlock` indirectly uses keyboard to search for block to insert)

**Comment by kathrynwp** [comment]
Hi @aduth – is this still occurring with the latest version of Gutenberg (13.7.3) and WordPress (6.0.1)? Thanks!

**Comment by kathrynwp** [comment]
I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to add a comment with additional details and I’ll be glad to reopen it.
