### ISSUE TITLE
createInterpolateElement import in block-editor/src/components/inserter/tips.js is wrong

### ISSUE THREAD

**Issue by tn3rb** [WordPress/gutenberg#22879]
**Describe the bug**

i receive the following error while running unit tests:

```
    TypeError: (0 , _element.createInterpolateElement) is not a function

    > 4 | import { InspectorControls } from '@wordpress/block-editor';

      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/inserter/@wordpress/block-editor/src/components/inserter/tips.js:9:2)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/inserter/@wordpress/block-editor/src/components/inserter/menu.js:19:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/inserter/@wordpress/block-editor/src/components/inserter/index.js:20:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-list/@wordpress/block-editor/src/components/block-list/insertion-point.js:17:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-list/@wordpress/block-editor/src/components/block-list/root-container.js:17:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-list/@wordpress/block-editor/src/components/block-list/block-wrapper.js:22:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-list/@wordpress/block-editor/src/components/block-list/block.js:37:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-navigation/@wordpress/block-editor/src/components/block-navigation/block-slot.js:24:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-navigation/@wordpress/block-editor/src/components/block-navigation/block-contents.js:10:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-navigation/@wordpress/block-editor/src/components/block-navigation/block.js:22:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-navigation/@wordpress/block-editor/src/components/block-navigation/branch.js:14:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-navigation/@wordpress/block-editor/src/components/block-navigation/tree.js:12:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-navigation/@wordpress/block-editor/src/components/block-navigation/index.js:16:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/block-navigation/@wordpress/block-editor/src/components/block-navigation/dropdown.js:13:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/components/@wordpress/block-editor/src/components/index.js:19:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/hooks/@wordpress/block-editor/src/hooks/align.js:23:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/hooks/@wordpress/block-editor/src/hooks/index.js:4:1)
      at Object.<anonymous> (node_modules/@wordpress/block-editor/build/@wordpress/block-editor/src/index.js:12:1)
```

following that stack trace leads to:
https://github.com/WordPress/gutenberg/blob/master/packages/block-editor/src/components/inserter/tips.js#L5

which has the following line of code:

```js
 import { createInterpolateElement, useState } from '@wordpress/element'; 
```

but `createInterpolateElement` was moved to `@wordpress/block-editor`
https://github.com/WordPress/gutenberg/tree/master/packages/block-editor/src/components/inspector-controls

and the import in `tips.js` was obviously never updated

**Comment by talldan** [comment]
@tn3rb It looks to me like `createInterpolateElement` is still in the `element` package - https://github.com/WordPress/gutenberg/blob/master/packages/element/src/create-interpolate-element.js.

Unit tests are run against every merged PR, so this issue with the failing test would have been flagged. 

I'm not sure what the issue that you're seeing is, but it doesn't seem related to the location of `createInterpolateElement`. It does seem curious to me that the stack trace for your tests is referencing the `node_modules` folder.

**Comment by gziolo** [comment]
Based on the error message shared it look like the code imports from itself creating cyclic dependency.

**Comment by tellthemachines** [comment]
Closing this issue because OP hasn't replied in over 2 years.
