### ISSUE TITLE
How to fix! The editor has encountered an unexpected error. WORDPRESS V5.5

### ISSUE THREAD

**Issue by pMehta1609** [WordPress/gutenberg#24549]
After updating my WP to version 5.5, this is the error code I get. I can't be able to edit my post through the block editor. please help
website: https://infohub1on1.com
PHP version - 7.4.6 (Supports 64bit values)

Error: An error occurred while running 'mapSelect': e(...).getEntityRecordChangesByRecord is not a function
The error may be correlated with this previous error:
TypeError: e(...).getEntityRecordChangesByRecord is not a function
    at Object.current (https://infohub1on1.com/my_includes/js/dist/editor.min.js:12:71041)
    at e (https://infohub1on1.com/my_includes/js/dist/data.min.js:2:24561)
    at https://infohub1on1.com/my_includes/js/dist/data.min.js:2:24726
    at https://infohub1on1.com/my_includes/js/dist/data.min.js:2:18650
    at Array.forEach (<anonymous>)
    at o (https://infohub1on1.com/my_includes/js/dist/data.min.js:2:18622)
    at https://infohub1on1.com/my_includes/js/dist/data.min.js:2:15849
    at p (https://infohub1on1.com/my_includes/js/dist/data.min.js:2:7909)
    at https://infohub1on1.com/my_includes/js/dist/data.min.js:2:9895
    at Object.dispatch (https://infohub1on1.com/my_includes/js/dist/data.min.js:2:10330)

Original stack trace:
    at Ge (https://infohub1on1.com/my_includes/js/dist/data.min.js:2:24353)
    at Xo (https://infohub1on1.com/my_includes/js/dist/editor.min.js:12:71010)
    at je (https://infohub1on1.com/my_includes/js/dist/vendor/react-dom.min.js:78:476)
    at qe (https://infohub1on1.com/my_includes/js/dist/vendor/react-dom.min.js:89:115)
    at ph (https://infohub1on1.com/my_includes/js/dist/vendor/react-dom.min.js:216:489)
    at lh (https://infohub1on1.com/my_includes/js/dist/vendor/react-dom.min.js:126:409)
    at O (https://infohub1on1.com/my_includes/js/dist/vendor/react-dom.min.js:121:71)
    at ze (https://infohub1on1.com/my_includes/js/dist/vendor/react-dom.min.js:118:14)
    at https://infohub1on1.com/my_includes/js/dist/vendor/react-dom.min.js:53:49
    at unstable_runWithPriority (https://infohub1on1.com/my_includes/js/dist/vendor/react.min.js:26:340)

**Comment by BenLinders** [comment]
I'm having the same error. Is there a work around?

**Comment by annezazu** [comment]
@pMehta1609 @BenLinders Thanks for reporting this although I'm bummed to see you've run into trouble. Here are a few next steps as it would be super helpful to have more information about your site:

- Have you all ruled out a plugin or theme conflict? For example, have you tried disabling all other plugins to see if the error persists? If it doesn't, try re-enabling plugins one at a time to find the culprit. 
- Are you using the Gutenberg plugin or simply the site editor as part of the WordPress 5.5 release?

**Comment by BenLinders** [comment]
I'm able again to edit posts and pages, no fatal error anymore.

**Comment by annezazu** [comment]
Fantastic to hear, Ben.

**Comment by talldan** [comment]
Closing as there hasn't been any further info on the issue. If this is still being experienced by anyone, and the above questions can be answered very happy to reopen this.
