### ISSUE TITLE
Unexpected @wordpress/eslint-plugin TypeError since v7.2.0

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress/gutenberg#25048]
Since `@wordpress/eslint-plugin` v7.2.0, I'm seeing the following error in CircleCI:

```
TypeError: Failed to load plugin '@wordpress/eslint-plugin' declared in '.eslintrc': Cannot destructure property 'config' of 'cosmiconfigSync(...).search(...)' as it is null.
Referenced from: /home/circleci/project/.eslintrc
```

Any ideas why this might be happening?

**Comment by hacktivista** [comment]
I can confirm. Something similar happened to me:

```
> eslint any.js


Oops! Something went wrong! :(

ESLint: 7.8.1

TypeError: Failed to load plugin '@wordpress/eslint-plugin' declared in '.eslintrc': Cannot destructure property `config` of 'undefined' or 'null'.
Referenced from: /home/mentorpro/dev/web/public_html/wp-content/themes/astra-child/mentorpro/.eslintrc
    at Object.<anonymous> (/home/mentorpro/dev/web/public_html/wp-content/themes/astra-child/mentorpro/node_modules/@wordpress/eslint-plugin/configs/recommended.js:11:71)
    at Module._compile (/home/mentorpro/dev/web/public_html/wp-content/themes/astra-child/mentorpro/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/mentorpro/dev/web/public_html/wp-content/themes/astra-child/mentorpro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at /home/mentorpro/dev/web/public_html/wp-content/themes/astra-child/mentorpro/node_modules/requireindex/index.js:52:28
    at Array.forEach (<anonymous>)
```

Apparently it's ignoring the specific plugins to be used and tries with `@wordpress/eslint-plugin/recommended` instead.

**Comment by ocean90** [comment]
https://github.com/WordPress/gutenberg/commit/c348eb6b1d36cfba7a6411c3ea004dfbc541d670 seems to be the related commit for this change.
