### ISSUE TITLE
dependency-extraction-webpack-plugin doesn't work with Webpack 5

### ISSUE THREAD

**Issue by slightlyfaulty** [WordPress/gutenberg#26134]
**Describe the bug**
Using `@wordpress/dependency-extraction-webpack-plugin` with Webpack 5 throws a build error:

```
[webpack-cli] Promise rejection: TypeError: Cannot read property 'tap' of undefined
[webpack-cli] TypeError: Cannot read property 'tap' of undefined
    at ExternalModuleFactoryPlugin.apply (.../node_modules/@wordpress/dependency-extraction-webpack-plugin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:17:37)
    at .../node_modules/@wordpress/dependency-extraction-webpack-plugin/node_modules/webpack/lib/ExternalsPlugin.js:16:63
    at Hook.eval [as call] (eval at create (.../node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (.../node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at .../node_modules/webpack/lib/Compiler.js:958:23
    at Hook.eval [as callAsync] (eval at create (.../node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (.../node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (.../node_modules/webpack/lib/Compiler.js:955:28)
    at .../node_modules/webpack/lib/Compiler.js:456:12
    at Compiler.readRecords (.../node_modules/webpack/lib/Compiler.js:797:11)
```

**To reproduce**
1. Install and configure Webpack.
1. Add `@wordpress/dependency-extraction-webpack-plugin`.
2. Build.
3. See error.

**Expected behavior**
Build succeeds with no error.

**Package versions:**
- `webpack` 5.1.0
- `webpack-cli` 4.0.0
- `@wordpress/dependency-extraction-webpack-plugin` 2.7.0

**Additional context**
Webpack 5 is the current stable version of Webpack. This and other `@wordpress` packages should work with it.

**Comment by ocean90** [comment]
Related: https://webpack.js.org/migrate/5/

**Comment by slightlyfaulty** [comment]
Seems to work fine if its `dependencies` are updated (though really `webpack` should be a `peepDependency`).

I also had to change these lines to `window` instead of `this`:

https://github.com/WordPress/gutenberg/blob/9ed837bda30d6037a492e8a4be84cd911dc0299b/packages/dependency-extraction-webpack-plugin/lib/index.js#L91

https://github.com/WordPress/gutenberg/blob/9ed837bda30d6037a492e8a4be84cd911dc0299b/packages/dependency-extraction-webpack-plugin/lib/index.js#L122

**Comment by gziolo** [comment]
@jsnajdr is working on issues you mentioned:
- https://github.com/WordPress/gutenberg/pull/26272
- https://github.com/WordPress/gutenberg/pull/26382

**Comment by internalsystemerror** [comment]
Is there going to be a release so that we can use this? I'm still receiving the exact same error.

**Comment by jsnajdr** [comment]
This issue was closed by mistake, by automation after merging #26272. But that PR solved only one particular webpack 5 compat issue, not everything. I filed a draft PR #27533 with the plugin's complete upgrade now.
