### ISSUE TITLE
Calendar Block triggers errors as widget 

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#26174]
When I try to add the calendar block to a widget area, we get the message: "this block has encountered an error and cannot be previewed" 

Errors from the Browser console are below.

**To reproduce**
1. Go to 'Appearance > Widget'
2. Add a calendar block to a widget area of your choice
3. See erro in the widget screen
4. Open browser console for the JavaScript Error. 

**Expected behavior**
That the calendar is displayed in the widget section. 

**Screenshots**
![Calendar Block errors as Widget](https://user-images.githubusercontent.com/39980/96188883-8416a480-0f0d-11eb-9218-fed81623afd0.gif)

**Editor version (please complete the following information):**
- WordPress version: trunc
- Gutenberg from Master

**Desktop (please complete the following information):**
 - OS: OS X 10.15.7,
 - Browser: Google Chrome
 - Version: 86.0.4240.75

**Additional context**
Errors from the Browser Console: 
index.js?ver=87345ead23d3e76d183ebd87cd628d61:1 
An error occurred while running 'mapSelect': Cannot read property 'getEditedPostAttribute' of null

Error: An error occurred while running 'mapSelect': Cannot read property 'getEditedPostAttribute' of null
The error may be correlated with this previous error:
TypeError: Cannot read property 'getEditedPostAttribute' of null
    at Object.current (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/build/block-library/index.js?ver=2ce465235c90e3066730ded9ac0a2d1b:16:38202)
    at e (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/build/data/index.js?ver=87345ead23d3e76d183ebd87cd628d61:1:28690)
    at http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/build/data/index.js?ver=87345ead23d3e76d183ebd87cd628d61:1:28799
    at Bh (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:126:456)
    at oj (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:126:549)
    at Aj (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:160:448)
    at unstable_runWithPriority (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react.min.e713ea3b.js:25:260)
    at Da (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:60:280)
    at ab (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:154:190)
    at Te (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:146:355)

Original stack trace:
    at Xe (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/build/data/index.js?ver=87345ead23d3e76d183ebd87cd628d61:1:28482)
    at edit (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/build/block-library/index.js?ver=2ce465235c90e3066730ded9ac0a2d1b:16:38166)
    at we (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:84:293)
    at He (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:97:464)
    at zj (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:228:406)
    at Th (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:152:223)
    at tj (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:152:152)
    at Te (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:146:151)
    at http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react-dom.min.de439aae.js:61:68
    at unstable_runWithPriority (http://test-wp54-rc5.local/wp-content/plugins/gutenberg-test-2020-10-15-6-40/vendor/react.min.e713ea3b.js:25:260)
Me @ react-dom.min.de439aae.js:125
Jh.f.componentDidCatch.c.callback @ react-dom.min.de439aae.js:139
Wg @ react-dom.min.de439aae.js:67
oj @ react-dom.min.de439aae.js:127
Aj @ react-dom.min.de439aae.js:160
unstable_runWithPriority @ react.min.e713ea3b.js:25
Da @ react-dom.min.de439aae.js:60
ab @ react-dom.min.de439aae.js:154
Te @ react-dom.min.de439aae.js:146
(anonymous) @ react-dom.min.de439aae.js:61
unstable_runWithPriority @ react.min.e713ea3b.js:25
Da @ react-dom.min.de439aae.js:60
Pg @ react-dom.min.de439aae.js:61
ha @ react-dom.min.de439aae.js:60
mk.Events.current @ react-dom.min.de439aae.js:236
Ei @ react-dom.min.de439aae.js:41

**Comment by draganescu** [comment]
This can be reproduced in master Gutenberg as of Oct 16th

**Comment by noisysocks** [comment]
Still able to reproduce this. Moving to needs dev.

**Comment by draganescu** [comment]
I tested this again with Gutenberg master of Feb 18, 2021 and it worked all right.
