### ISSUE TITLE
Gutenberg crashes on 9.2.0 when clicking on a block or inserting a block

### ISSUE THREAD

**Issue by arjendejong12** [WordPress/gutenberg#26381]
**Describe the bug**
Clicking on blocks or trying to add a block via de inserter causes Gutenberg to crash with the following error stack trace:
```
Error: An error occurred while running 'mapSelect': u.substr is not a function
The error may be correlated with this previous error:
TypeError: u.substr is not a function
    at v (https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/block-serialization-default-parser/index.js?ver=7110f347451a9a2bcae6223b180b96dd:1:3536)
    at b (https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/block-serialization-default-parser/index.js?ver=7110f347451a9a2bcae6223b180b96dd:1:2843)
    at p (https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/block-serialization-default-parser/index.js?ver=7110f347451a9a2bcae6223b180b96dd:1:2342)
    at Gr (https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/blocks/index.js?ver=97c5495cbfb44eab0e216227afed9391:13:36982)
    at https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/block-editor/index.js?ver=feebd7dffa288c5eabfc28da06543146:25:51819
    at u (https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/block-editor/index.js?ver=feebd7dffa288c5eabfc28da06543146:1:10419)
    at i (https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/block-editor/index.js?ver=feebd7dffa288c5eabfc28da06543146:25:49769)
    at Array.map (<anonymous>)
    at https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/block-editor/index.js?ver=feebd7dffa288c5eabfc28da06543146:25:50158
    at u (https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/block-editor/index.js?ver=feebd7dffa288c5eabfc28da06543146:1:10419)

Original stack trace:
    at Xe (https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/data/index.js?ver=a0effe22ca5a445ba9c4ee384cdf7853:1:28482)
    at https://scriptware.mediasoep.nl/content/plugins/gutenberg/build/data/index.js?ver=a0effe22ca5a445ba9c4ee384cdf7853:1:29038
    at we (https://scriptware.mediasoep.nl/content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:84:293)
    at He (https://scriptware.mediasoep.nl/content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:97:464)
    at zj (https://scriptware.mediasoep.nl/content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:228:406)
    at Th (https://scriptware.mediasoep.nl/content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:223)
    at tj (https://scriptware.mediasoep.nl/content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:152)
    at Te (https://scriptware.mediasoep.nl/content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:151)
    at https://scriptware.mediasoep.nl/content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68
    at unstable_runWithPriority (https://scriptware.mediasoep.nl/content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)
```
This only happens on 9.2.0. Downgrading to 9.1.0 fixes the issue. It happens on every block, not a specific one.

**To reproduce**
1. Open or create a post/page.
2. Click on a block, or on the + for the inserter.
3. See Gutenberg crashing.

**Expected behavior**
Clicking a block or inserting one should just work.

**Editor version (please complete the following information):**
- WordPress version: 5.5.1
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Plugin
- If the Gutenberg plugin is installed, which version is it? 9.2.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88.0.4292.2

**Comment by talldan** [comment]
@arjendejong12 A patch, 9.2.1, was released for the plugin, does that help with your issue?

**Comment by arjendejong12** [comment]
@talldan Unfortunately it still happens with 9.2.1.

**Comment by fotovat** [comment]
Similar problem

**Comment by talldan** [comment]
@arjendejong12 @fotovat Would you be able to share the plugins and theme do you have active?

Not saying it isn't a Gutenberg bug, but it seems like it must be triggered by something specific to your WordPress environments, as it's not happening in the vanilla Gutenberg dev environment and there don't seem to have been any other reports of the issue.

**Comment by fotovat** [comment]
WordPress 5.5.1
Twenty Twenty theme
Gutenberg 9.2.1 without any other plug in
SiteGround  hosting tested with PHP 7.4 and 7.3

I tested on staging site in local environment by MAMP Pro PHP 7.3  and there is no problem.

**Comment by talldan** [comment]
@arjendejong12 @fotovat This looks like it could be the fix for your issue:
https://github.com/WordPress/gutenberg/pull/26484

I tested an empty reusable block and the console error message matched yours.

If you can check your Reusable blocks (`wp-admin/edit.php?post_type=wp_block`) to see if there are any empty, and if so that would confirm the bug. As a workaround you can also remove or update any empty reusable blocks to be non-empty, and that should also help.

**Comment by arjendejong12** [comment]
@talldan This PR fixes my issue. I had an empty reusable block and when I deleted that, the bug didn't occur. With an empty block and this fix, the bug also doesn't occur.

**Comment by talldan** [comment]
Great, glad we tracked that down 👍
