### ISSUE TITLE
Gutenberg error writing post - The editor has encountered an unexpected error.  Attempt Recovery Copy Post Text Copy Error

### ISSUE THREAD

**Issue by KaylaACM** [WordPress/gutenberg#26558]
Trying to write posts on WordPress with Gutenberg. It stops suddenly and this error comes up. Clicking attempt recovery does nothing. 

<img width="929" alt="Screen Shot 2020-10-29 at 11 20 06 am" src="https://user-images.githubusercontent.com/73621026/97510502-f640bc00-19d8-11eb-9e20-500e2dc2a222.png">

**Comment by talldan** [comment]
@KaylaACM Could you click `Copy Error` and paste the output in a comment here. Thanks.

**Comment by mprior92** [comment]
I'm constantly getting the same error.

TypeError: Cannot read property 'attributes' of null

**Comment by talldan** [comment]
Thanks for sharing the error. Unfortunately that's quite difficult to track down as `attributes` is used in a lot of place. I hoped the error would have a stack trace with it.

@mprior92 if you open the browser dev tools when the error comes up (right click somewhere on the page and select 'Inspect Element') and then switch to the console tab. If there's red text there it'd be great if you could screenshot it and post it here.

**Comment by KaylaACM** [comment]
Error: An error occurred while running 'mapSelect': u.substr is not a function
The error may be correlated with this previous error:
TypeError: u.substr is not a function
    at v (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/block-serialization-default-parser/index.js?ver=7110f347451a9a2bcae6223b180b96dd:1:3536)
    at b (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/block-serialization-default-parser/index.js?ver=7110f347451a9a2bcae6223b180b96dd:1:2843)
    at p (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/block-serialization-default-parser/index.js?ver=7110f347451a9a2bcae6223b180b96dd:1:2342)
    at Gr (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/blocks/index.js?ver=c8e8f699f604ff1628eaf1863098f07a:13:36982)
    at https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=111d02e55937608149e0d53ccb3d5ab2:25:51819
    at u (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=111d02e55937608149e0d53ccb3d5ab2:1:10419)
    at i (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=111d02e55937608149e0d53ccb3d5ab2:25:49769)
    at Array.map (<anonymous>)
    at https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=111d02e55937608149e0d53ccb3d5ab2:25:50158
    at u (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=111d02e55937608149e0d53ccb3d5ab2:1:10419)

Original stack trace:
    at Xe (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/data/index.js?ver=a0effe22ca5a445ba9c4ee384cdf7853:1:28482)
    at https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/build/data/index.js?ver=a0effe22ca5a445ba9c4ee384cdf7853:1:29038
    at we (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:84:293)
    at He (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:97:464)
    at zj (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:228:406)
    at Th (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:223)
    at tj (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:152)
    at Te (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:151)
    at https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68
    at unstable_runWithPriority (https://adrianchambersmotorsports.com.au/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)

**Comment by KaylaACM** [comment]
<img width="1130" alt="Screen Shot 2020-10-29 at 3 09 04 pm" src="https://user-images.githubusercontent.com/73621026/97524420-bdb0da80-19f8-11eb-8b11-6ad8dc5f757c.png">

**Comment by talldan** [comment]
Thanks @KaylaACM. This is something that will be fixed in an upcoming version of the Gutenberg plugin.

It's a bad bug that's triggered by having an empty reusable block on your site. As a temporary workaround you can remove the empty reusable block from your site, or add something to it. Some instructions here:
https://github.com/WordPress/gutenberg/issues/26381#issuecomment-717023597

Sorry that you've been affected by this one!

**Comment by KaylaACM** [comment]
I can't seem to access any reusable blocks seeing as I can't make a post without it going straight to that error page?

**Comment by talldan** [comment]
Closing as this has since been fixed (and I know the website in question was able to resolve the issue).
