### ISSUE TITLE
E2E Testing: Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#27229]
**Describe the bug**

Raised by @rafaelgalani in the comment https://github.com/WordPress/gutenberg/pull/27178#issuecomment-732383418:

> The build was failing before this last commit. I tried analyzing the YAML for the E2E tests; apparently, the runs are split between 4 runners... Right? And, for some reason (which I am not sure why), the [build failed in the second one](https://github.com/WordPress/gutenberg/runs/1437311420?check_suite_focus=true)... I just made an empty commit, and it passed now...
>
> Edit: after some quick searching, I think that the issue could be something similar [to this](https://github.com/puppeteer/puppeteer/issues/3323).

```
FAIL specs/local/demo.test.js (6.64s)
57
  ● new editor state › content should load, making the post dirty
58

59
    Execution context was destroyed, most likely because of a navigation.
60

61
      at rewriteError (../../node_modules/puppeteer/lib/ExecutionContext.js:157:23)
62
          at runMicrotasks (<anonymous>)
63
      at ExecutionContext._evaluateInternal (../../node_modules/puppeteer/lib/ExecutionContext.js:65:64)
64
      at ../../node_modules/puppeteer/lib/DOMWorld.js:120:30
65
      at DOMWorld.$$ (../../node_modules/puppeteer/lib/DOMWorld.js:160:26)
66
        -- ASYNC --
67
      at ExecutionContext.<anonymous> (../../node_modules/puppeteer/lib/helper.js:105:23)
68
      at ../../node_modules/puppeteer/lib/DOMWorld.js:120:44
69
          at runMicrotasks (<anonymous>)
70
        -- ASYNC --
71
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:105:23)
72
      at ../../node_modules/@axe-core/puppeteer/src/axePuppeteer.ts:41:30
73
      at ../../node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:8:71
74
      at __awaiter (../../node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:4:12)
75
      at injectJS (../../node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:29:12)
76
      at ../../node_modules/@axe-core/puppeteer/src/axePuppeteer.ts:45:15
77
      at fulfilled (../../node_modules/@axe-core/puppeteer/dist/axePuppeteer.js:5:58)
```

**To reproduce**
Run `npm run test-e2e specs/local/demo.test.js` a few times and observe the error.

**Expected behavior**

E2E tests always pass.

**Comment by rafaelgalani** [comment]
I was able to reproduce it and fix it locally. I'm opening the PR. 😸

**Comment by rafaelgalani** [comment]
I was able to reproduce it and fix it locally. Can I open the PR? 😸

**Comment by gziolo** [comment]
> I was able to reproduce it and fix it locally. Can I open the PR? 😸 

It sounds fantastic! Sure you can open PRs, there is no need to ask 😃
