### ISSUE TITLE
wp-env: destroy command doesn't work on Windows 10 Pro

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#27957]
**Describe the bug**

I have Windows 10 Pro, Hyper-V enabled, Docker Desktop 3.0.0 installed and running, node v14.5.3 LTS, using cmd.exe to run a command.

`wp-env destroy` generates an error and, obviously, does nothing:

```
> wp-env destroy
i WARNING! This will remove Docker containers, volumes, and networks associated with the WordPress instance.
? Are you sure you want to continue? Yes
× Command failed: docker volume rm $(docker volume ls | grep "1e2b715f53b19e9bda31531bd2a0e2cc" | awk '/ / { print $2 }') && docker network rm $(docker network ls | grep "1e2b715f53b19e9bda31531bd2a0e2cc" | awk '/ / { print $1 }')
'grep' is not recognized as an internal or external command,
operable program or batch file.

Error: Command failed: docker volume rm $(docker volume ls | grep "1e2b715f53b19e9bda31531bd2a0e2cc" | awk '/ / { print $2 }') && docker network rm $(docker network ls | grep "1e2b715f53b19e9bda31531bd2a0e2cc" | awk '/ / { print $1 }')
'grep' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: `docker volume rm $(docker volume ls | grep "1e2b715f53b19e9bda31531bd2a0e2cc" | awk '/ / { print $2 }') && docker network rm $(docker network ls | grep "1e2b715f53b19e9bda31531bd2a0e2cc" | awk '/ / { print $1 }')`,
  stdout: '',
  stderr: "'grep' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n'
}
```

**Expected behavior**

Everything should be destroyed.

**Comment by noahtallen** [comment]
he problem is that we execute some commands on the CLI which are available in bash which are unfortunately not on windows (like `grep`). This is definitely an oversight on my part.

**Comment by carolinan** [comment]
Any update on this?

**Comment by noahtallen** [comment]
Sorry for taking so long on this. It should be working on `trunk` now, and I hope we can release an npm update within a week
