### ISSUE TITLE
wp-env: running `start` with non-empty plugins[] generates error

### ISSUE THREAD

**Issue by slaFFik** [WordPress/gutenberg#27958]
**Describe the bug**

I have Windows 10 Pro, Hyper-V enabled, Docker Desktop 3.0.0 installed and running, node v14.5.3 LTS, using cmd.exe to run a command.

Here is my `.wp-env.json` file:

```json
{
  "phpVersion": "7.4",
  "plugins": [
    "https://downloads.wordpress.org/plugin/woocommerce.zip",
    "."
  ],
  "port": 8888,
  "testsPort": 8889,
  "config": {
    "WP_DEBUG": true,
    "WP_DEBUG_DISPLAY": true,
    "SCRIPT_DEBUG": true
  }
}
```

Here are my FileSharing settings in Docker:
![image](https://user-images.githubusercontent.com/282234/103446857-0b61f180-4c8d-11eb-8f1c-0b5282586b23.png)

This is the path where I run the `wp-env start` command: `C:\OpenServer\domains\example\test` - so it's within the allowed path as per Docker "File Sharing" settings.

<details>
<summary>Command output:</summary>

```
>wp-env start
× Error while running docker-compose command.
Step 1/6 : FROM wordpress:php7.4
 ---> bc5f6567b763
Step 2/6 : RUN apt -qy install $PHPIZE_DEPS     && pecl install xdebug  && docker-php-ext-enable xdebug
 ---> Using cache
 ---> d683b9d811be
Step 3/6 : RUN touch /usr/local/etc/php/php.ini
 ---> Using cache
 ---> dfa9186a2310
Step 4/6 : RUN echo 'xdebug.start_with_request=yes' >> /usr/local/etc/php/php.ini
 ---> Using cache
 ---> 0cfd6938367f
Step 5/6 : RUN echo 'xdebug.mode=off' >> /usr/local/etc/php/php.ini
 ---> Using cache
 ---> 7c393efd6ba1
Step 6/6 : RUN echo 'xdebug.client_host="host.docker.internal"' >> /usr/local/etc/php/php.ini
 ---> Using cache
 ---> b6e3109e7833

Successfully built b6e3109e7833
Successfully tagged wordpress:php7.4
Building wordpress
Recreating 1e2b715f53b19e9bda31531bd2a0e2cc_mysql_1 ... done
Creating 1e2b715f53b19e9bda31531bd2a0e2cc_tests-wordpress_1 ... error
Creating 1e2b715f53b19e9bda31531bd2a0e2cc_wordpress_1       ...

ERROR: for 1e2b715f53b19e9bda31531bd2a0e2cc_tests-wordpress_1  Cannot create container for service tests-wordpress: status code not OK but 500: ☺\u02d9\u02d9\u02d9\u02d9☺♀☻FDocker.Core, Version=3.0.0.50646, Culture=neutral, PubWatsonBuckets☺☺♥♥☺☺☺☺☺▲System.Collections.IDictionary►System.Excepti☻☻♠ocker.Core.DockerException♠♦▲Filesharing has been cancelledg►RemoteStackIndex☼ExceptionMethodHResult♠Source


♠♣\u015a‼   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__6.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.HttpApi\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
♠♠\u0141☺8
MoveNext
Docker.ApiServices, Version=3.0.0.50646, Culture=neutral, PublicKeyToken=null
Docker.ApiServices.Mounting.FileSharing+<DoShareAsync>d__8
Creating 1e2b715f53b19e9bda31531bd2a0e2cc_wordpress_1       ... error

ERROR: for 1e2b715f53b19e9bda31531bd2a0e2cc_wordpress_1  Cannot create container for service wordpress: status code not OK but 500: ☺\u02d9\u02d9\u02d9\u02d9☺♀☻FDocker.Core, Version=3.0.0.50646, Culture=neutral, PublicKeyToken=WatsonBuckets☺☺♥♥☺☺☺☺☺▲System.Collections.IDictionary►System.Excepti☻☻♠ocker.Core.DockerException♠♦▲Filesharing has been cancelledStackIndex☼ExceptionMethodHResult♠Source


♠♣\u015a‼   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__6.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.HttpApi\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
♠♠\u0141☺8
MoveNext
Docker.ApiServices, Version=3.0.0.50646, Culture=neutral, PublicKeyToken=null
Docker.ApiServices.Mounting.FileSharing+<DoShareAsync>d__8
Void MoveNext()§‼�♠↕Docker.ApiServices

ERROR: for tests-wordpress  Cannot create container for service tests-wordpress: status code not OK but 500: ☺\u02d9\u02d9\u02d9\u02d9☺♀☻FDocker.Core, Version=3.0.0.50646, Culture=neutral, PublicKeyToken=null♣ocker.Core.DockerEWatsonBuckets☺☺♥♥☺☺☺☺☺▲System.Collections.IDictionary►System.Excepti☻☻♠ocker.Core.DockerException♠♦▲Filesharing has been cancelledodHResult♠Source


♠♣\u015a‼   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__6.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.HttpApi\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
♠♠\u0141☺8
MoveNext
Docker.ApiServices, Version=3.0.0.50646, Culture=neutral, PublicKeyToken=null
Docker.ApiServices.Mounting.FileSharing+<DoShareAsync>d__8
Void MoveNext()§‼�♠↕Docker.ApiServices

ERROR: for wordpress  Cannot create container for service wordpress: status code not OK but 500: ☺\u02d9\u02d9\u02d9\u02d9☺♀☻FDocker.Core, Version=3.0.0.50646, Culture=neutral, PublicKeyToken=null♣ocker.Core.DockerException♀  CWatsonBuckets☺☺♥♥☺☺☺☺☺▲System.Collections.IDictionary►System.Excepti☻☻♠ocker.Core.DockerException♠♦▲Filesharing has been cancelled


♠♣\u015a‼   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__6.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.HttpApi\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
♠♠\u0141☺8
MoveNext
Docker.ApiServices, Version=3.0.0.50646, Culture=neutral, PublicKeyToken=null
Docker.ApiServices.Mounting.FileSharing+<DoShareAsync>d__8
Void MoveNext()§‼�♠↕Docker.ApiServices
Encountered errors while bringing up the project.
```

</details>

**Comment by timnolte** [comment]
@slaFFik is this really wp-env issue or a Docker 3.x issue? Can you confirm whether it works with a version of Docker prior to 3.x? I don't have a Windows 10 machine readily available to test on that platform specifically, I'm hoping that this isn't some sort of regression from my work adding the PHP configuration support on #25268

**Comment by noahtallen** [comment]
I tested a fresh install of Docker 3 on Windows 10 today and had no problems. It might be worth checking the docker configuration again -- I had some trouble getting docker running myself. I think I ended up having to switch to WSL2. You can test if the Docker daemon is detected with `docker ps -a` (which will error if things aren't working)
