### ISSUE TITLE
Plugin: 9.8.0-rc.1 crash on activation

### ISSUE THREAD

**Issue by sirreal** [WordPress/gutenberg#28240]
## Description

When activating the [plugin 9.8.0-rc.1 ](https://github.com/WordPress/gutenberg/releases/tag/v9.8.0-rc.1) on a new, clean site, it crashes. After uploading the zip and clicking activate, the site crashes with a fatal error at `…/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s=`

```
Fatal error: Uncaught Error: Call to undefined function gutenberg_use_widgets_block_editor() in /srv/users/user4ecca219/apps/user4ecca219/public/wp-content/plugins/gutenberg-9.8.0-rc.1/gutenberg.php:46 Stack trace:
#0 /srv/users/user4ecca219/apps/user4ecca219/public/wp-includes/class-wp-hook.php(287): gutenberg_menu('')
#1 /srv/users/user4ecca219/apps/user4ecca219/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /srv/users/user4ecca219/apps/user4ecca219/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /srv/users/user4ecca219/apps/user4ecca219/public/wp-admin/includes/menu.php(155): do_action('admin_menu', '')
#4 /srv/users/user4ecca219/apps/user4ecca219/public/wp-admin/menu.php(327): require_once('/srv/users/user...')
#5 /srv/users/user4ecca219/apps/user4ecca219/public/wp-admin/admin.php(158): require('/srv/users/user...')
#6 /srv/users/user4ecca219/apps/user4ecca219/public/wp-admin/plugins.php(10): require_once('/srv/users/user...')
#7 {main} thrown in /srv/users/user4ecca219/apps/user4ecca219/public/wp-content/plugins/gutenberg-9.8.0-rc.1/gutenberg.php on line 46
```

## Step-by-step reproduction instructions
1. Create a new site
2. Install the 9.8 RC zip
3. Activate
4. See the fatal error

## WordPress information
- WordPress version: 5.6
- Gutenberg version: 9.8.0-rc.1
- Are all plugins except Gutenberg deactivated? yes

**Comment by sirreal** [comment]
This was user error. I got the source code zip instead of the `gutenberg.zip` from the release page.
