### ISSUE TITLE
Unable to edit Pages or Posts

### ISSUE THREAD

**Issue by john17899** [WordPress/gutenberg#29131]
Unable to edit posts or pages with Guttenberg.

## Step-by-step reproduction instructions

TypeError: Cannot read property '$el' of undefined
    at new b (https://www.harperandfriends.com/wp-content/plugins/gutenberg/build/media-utils/index.js?ver=a3779b089c194011c3954a4a6b7b0809:1:6410)
    at Yg (https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:7:4856)
    at rh (https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:8:7382)
    at zj (https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:14:22285)
    at Th (https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:11:728)
    at tj (https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:11:657)
    at Te (https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:10:7241)
    at https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:7:1114
    at unstable_runWithPriority (https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:3:3396)
    at Da (https://www.harperandfriends.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:7:824)
## WordPress information
- WordPress version: 5.6.1
- Gutenberg version: 10.0
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Using Flatsome, Switched to Twenty twenty one

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Edge Chrome Firefox

**Comment by talldan** [comment]
@john17899 Is this happening when opening the editor or at another time?

**Comment by john17899** [comment]
When opening the editor

**Comment by talldan** [comment]
@john17899 That error seems related to media uploading for blocks like the image, gallery or cover.

Do you have any plugins installed that might change how the media uploader or media modal work?

**Comment by annezazu** [comment]
Due to lack of progress on this issue, I am going to close this out. Feel free to reopen if this is still an issue!
