### ISSUE TITLE
Deleting a block using "Delete" button makes block crash.

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#29958]
## Description
My plugin was working well. After installing Gutenberg 10.2.0 a strange behaviour happens.
When I try to delete the first input field from a form, the block crashes. This is happening only on first field. From second field and above, all works as expected.
If I try to delete the input field with three dots menu, it works.
If I use "Delete" button it crashes.
If I disable Gutenberg, the plugin works great.
Cannot say if it happens with other blocks.

## Step-by-step reproduction instructions

1. Install Formello from https://wordpress.org/plugins/formello/
2. Insert a basic form
3. Delete the first input using "Delete" button

## Expected behaviour
Using "Delete" button should work

## Actual behaviour
When deleting a block using "Delete" button the block crashed. If I use the three dots the block works great.

## WordPress information
- WordPress version: 5.7.0
- Gutenberg version: 10.2.0
- Are all plugins except Gutenberg deactivated?  "Yes"
- Are you using a default theme (e.g. Twenty Twenty-One)? - "Yes"

This is the fullstack:

```
index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1 Uncaught Error: An error occurred while running 'mapSelect': Cannot read property 'title' of undefined
The error may be correlated with this previous error:
TypeError: Cannot read property 'title' of undefined
    at Object.current (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=d61c93bbc33d9bdb16bbf7408ade8d8f:54:10919)
    at http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:30744
    at s (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:25037)
    at Object.__experimentalMarkListeningStores (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:25416)
    at http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:30044
    at e (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:30721)
    at t (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:30899)
    at http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:21999
    at p (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:12096)
    at http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1:9762

Original stack trace:
    at Me (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/data/index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1:30447)
    at Nd (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=d61c93bbc33d9bdb16bbf7408ade8d8f:54:10632)
    at Ld (http://localhost/affiliateblog/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=d61c93bbc33d9bdb16bbf7408ade8d8f:54:12349)
    at renderWithHooks (http://localhost/affiliateblog/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:14938:20)
    at updateFunctionComponent (http://localhost/affiliateblog/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:17169:22)
    at beginWork (http://localhost/affiliateblog/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:18745:18)
    at HTMLUnknownElement.callCallback (http://localhost/affiliateblog/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:182:16)
    at Object.invokeGuardedCallbackDev (http://localhost/affiliateblog/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:231:18)
    at invokeGuardedCallback (http://localhost/affiliateblog/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:286:33)
    at beginWork$1 (http://localhost/affiliateblog/wp-content/plugins/gutenberg/vendor/react-dom.82e849f1.js:23338:9)
Me @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
Nd @ index.js?ver=d61c93bbc33d9bdb16bbf7408ade8d8f:54
Ld @ index.js?ver=d61c93bbc33d9bdb16bbf7408ade8d8f:54
renderWithHooks @ react-dom.82e849f1.js:14938
updateFunctionComponent @ react-dom.82e849f1.js:17169
beginWork @ react-dom.82e849f1.js:18745
callCallback @ react-dom.82e849f1.js:182
invokeGuardedCallbackDev @ react-dom.82e849f1.js:231
invokeGuardedCallback @ react-dom.82e849f1.js:286
beginWork$1 @ react-dom.82e849f1.js:23338
performUnitOfWork @ react-dom.82e849f1.js:22289
workLoopSync @ react-dom.82e849f1.js:22265
performSyncWorkOnRoot @ react-dom.82e849f1.js:21891
(anonymous) @ react-dom.82e849f1.js:11224
unstable_runWithPriority @ react.af754d50.js:2685
runWithPriority$1 @ react-dom.82e849f1.js:11174
flushSyncCallbackQueueImpl @ react-dom.82e849f1.js:11219
flushSyncCallbackQueue @ react-dom.82e849f1.js:11207
scheduleUpdateOnFiber @ react-dom.82e849f1.js:21334
dispatchAction @ react-dom.82e849f1.js:15795
e @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
t @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
(anonymous) @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
p @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
(anonymous) @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
dispatch @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
n @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
e @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
r.any @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
e @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
e @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
c @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
t @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
r.iterator @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
e @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
e @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
e @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
c @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
t @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=3825f2b436975404bdf95fbea3ccf34a:1
(anonymous) @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
(anonymous) @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
(anonymous) @ index.js?ver=389a40540abec87a5da2a8b4d1b6e827:1
l @ index.js?ver=d61c93bbc33d9bdb16bbf7408ade8d8f:29
Show 33 more frames
react_devtools_backend.js:2430 The above error occurred in the <Ld> component:
    in Ld
    in o
    in Unknown (created by (Component))
    in (Component) (created by ((Component)))
    in ((Component)) (created by WithFontSizeInlineStyles(((Component))))
    in WithFontSizeInlineStyles(((Component))) (created by WithFilters(Component))
    in WithFilters(Component) (created by IfCondition(WithFilters(Component)))
    in IfCondition(WithFilters(Component)) (created by WithDispatch(IfCondition(WithFilters(Component))))
    in WithDispatch(IfCondition(WithFilters(Component)))
    in Unknown (created by Pure(WithSelect(WithDispatch(IfCondition(WithFilters(Component))))))
    in Pure(WithSelect(WithDispatch(IfCondition(WithFilters(Component))))) (created by Cd)
    in Cd (created by Sd)
    in Sd (created by cf)
    in Ya (created by cf)
    in cf (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in ForwardRef (created by Edit)
    in form (created by Edit)
    in div (created by Edit)
    in Edit (created by FormEdit)
    in FormEdit
    in Unknown (created by WithSelect(FormEdit))
    in WithSelect(FormEdit)
    in Unknown (created by WithToolbarControls(Component))
    in WithToolbarControls(Component) (created by WithInspectorControl(WithToolbarControls(Component)))
    in WithInspectorControl(WithToolbarControls(Component)) (created by WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))) (created by WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component)))))
    in WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))
    in Unknown (created by WithDispatch(Component))
    in WithDispatch(Component)
    in Unknown (created by WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))))
    in WithMultipleValidation(WithToolbarControls(WithInspectorControl(WithInspectorControl(WithToolbarControls(Component))))) (created by WithFilters(Component))
    in WithFilters(Component) (created by nl)
    in nl
    in div (created by Ld)
    in Ld
    in o
    in Unknown (created by (Component))
    in (Component) (created by ((Component)))
    in ((Component)) (created by WithFontSizeInlineStyles(((Component))))
    in WithFontSizeInlineStyles(((Component))) (created by WithFilters(Component))
    in WithFilters(Component) (created by IfCondition(WithFilters(Component)))
    in IfCondition(WithFilters(Component)) (created by WithDispatch(IfCondition(WithFilters(Component))))
    in WithDispatch(IfCondition(WithFilters(Component)))
    in Unknown (created by Pure(WithSelect(WithDispatch(IfCondition(WithFilters(Component))))))
    in Pure(WithSelect(WithDispatch(IfCondition(WithFilters(Component))))) (created by Cd)
    in Cd (created by Sd)
    in Sd (created by wd)
    in div (created by wd)
    in wd (created by T)
    in div (created by rs)
    in rs (created by T)
    in div (created by T)
    in div (created by T)
    in T (created by tr)
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in div (created by ForwardRef)
    in ForwardRef (created by tr)
    in tr (created by ar)
    in o (created by ar)
    in Unknown
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(Component)
    in Ya
    in an
    in an
    in Unknown
    in Unknown (created by Context.Consumer)
    in WithRegistryProvider(Component) (created by ar)
    in vl (created by ar)
    in M (created by N)
    in o (created by N)
    in N (created by ar)
    in StrictMode (created by ar)
    in ar

React will try to recreate this component tree from scratch using the error boundary you provided, o.
```

**Comment by talldan** [comment]
Thanks for reporting @Tropicalista. I think this is the same issue as https://github.com/WordPress/gutenberg/issues/29498, so I'll close as a duplicate.
