### ISSUE TITLE
Site editor: Error when removing navigation block with backspace

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#30723]
## Description

This was reported by multiple users during a contributor day at Yoast on April 9.
_I removed the navigation with my Backspace button, and got this error: This block has encountered an error and cannot be previewed._

I have confirmed that this issue only happens in the site editor, not the post editor. JS errors below.

## Step-by-step reproduction instructions

Please list the steps needed to reproduce the bug. For example:
1. Activate a full site editing theme like TT1 blocks.
2. In the site editor, add a navigation block.
3. With the block selected, press backspace to remove it. See error.

## Expected behaviour

The block should be removed.

## Actual behaviour

The block was not removed and displays an error message.

## Code snippet (optional)
Errors:

```
10:19:54.109 react-dom.min.de439aae.js:125 Error: An error occurred while running 'mapSelect': Cannot read property 'title' of undefined
The error may be correlated with this previous error:
TypeError: Cannot read property 'title' of undefined
    at Object.current (http://localhost:8888/wp-content/plugins/gutenberg-git/build/block-editor/index.js?ver=daa4ed0fe31c7a231895c489e2f53d96:54:11945)
    at http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:30570
    at s (http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:24851)
    at Object.__experimentalMarkListeningStores (http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:25230)
    at http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:29870
    at e (http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:30547)
    at t (http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:30725)
    at http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:21813
    at Object.p [as dispatch] (http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:11910)
    at e (<anonymous>:1:40553)

Original stack trace:
    at Me (http://localhost:8888/wp-content/plugins/gutenberg-git/build/data/index.js?ver=05595335a9d457a71fba9653d695ba2c:1:30273)
    at rb (http://localhost:8888/wp-content/plugins/gutenberg-git/build/block-editor/index.js?ver=daa4ed0fe31c7a231895c489e2f53d96:54:11658)
    at http://localhost:8888/wp-content/plugins/gutenberg-git/build/block-library/index.js?ver=28a6fcc173f84e04c2b6040862b05707:30:36468
    at we (http://localhost:8888/wp-content/plugins/gutenberg-git/vendor/react-dom.min.de439aae.js:84:293)
    at He (http://localhost:8888/wp-content/plugins/gutenberg-git/vendor/react-dom.min.de439aae.js:97:464)
    at zj (http://localhost:8888/wp-content/plugins/gutenberg-git/vendor/react-dom.min.de439aae.js:228:406)
    at Th (http://localhost:8888/wp-content/plugins/gutenberg-git/vendor/react-dom.min.de439aae.js:152:223)
    at tj (http://localhost:8888/wp-content/plugins/gutenberg-git/vendor/react-dom.min.de439aae.js:152:152)
    at Te (http://localhost:8888/wp-content/plugins/gutenberg-git/vendor/react-dom.min.de439aae.js:146:151)
    at http://localhost:8888/wp-content/plugins/gutenberg-git/vendor/react-dom.min.de439aae.js:61:68
Me @ react-dom.min.de439aae.js:125
10:19:54.113 index.js?ver=05595335a9d457a71fba9653d695ba2c:1 An error occurred while running 'mapSelect': Cannot read property 'title' of undefined
Me @ index.js?ver=05595335a9d457a71fba9653d695ba2c:1
10:19:54.115 react-dom.min.de439aae.js:125 TypeError: Cannot read property 'mode' of undefined
    at rb (index.js?ver=daa4ed0fe31c7a231895c489e2f53d96:54)
    at ab (index.js?ver=daa4ed0fe31c7a231895c489e2f53d96:54)
    at we (react-dom.min.de439aae.js:84)
    at zj (react-dom.min.de439aae.js:226)
    at Th (react-dom.min.de439aae.js:152)
    at tj (react-dom.min.de439aae.js:152)
    at Te (react-dom.min.de439aae.js:146)
    at react-dom.min.de439aae.js:61
    at unstable_runWithPriority (react.min.e713ea3b.js:25)
    at Da (react-dom.min.de439aae.js:60)

```

## WordPress information
- WordPress version: 5.7
- Gutenberg version:  Confirmed in current trunk and with 10.3.2
- Are all plugins except Gutenberg deactivated? yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
Browser: Firefox 87.0 Operating System: macOS 11.2.3
Browser: Firefox 87.0 Operating System: MacOS Big Sur 11.2.1
Browser: Chrome 89.0.4389.114, windows 10

**Comment by Mamaduka** [comment]
Related issue #29498.

**Comment by annezazu** [comment]
I'm going to close this out in favor of the issue @Mamaduka referenced here as it covers the same problem 🙌🏼
