### ISSUE TITLE
v10.5.1: "Cannot read property 'isNavigationMode' of undefined" when trying to edit a post

### ISSUE THREAD

**Issue by moisespr123** [WordPress/gutenberg#31335]
Hi, after updating the plugin to v10.5.1, I'm getting the following issue:

```
TypeError: Cannot read property 'isNavigationMode' of undefined
    at Ms (https://moisescardona.me/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=03b49d2fb4f620da6199dad936b24233:29:13195)
    at Nb (https://moisescardona.me/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=03b49d2fb4f620da6199dad936b24233:56:10732)
    at Rb (https://moisescardona.me/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=03b49d2fb4f620da6199dad936b24233:56:11852)
    at we (https://moisescardona.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:84:293)
    at zj (https://moisescardona.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:226:496)
    at Th (https://moisescardona.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:223)
    at tj (https://moisescardona.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:152)
    at Te (https://moisescardona.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:151)
    at https://moisescardona.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68
    at unstable_runWithPriority (https://moisescardona.me/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)
```

To reproduce, just try to edit a post.

**Comment by moisespr123** [comment]
Seems to be fixed in v10.5.2.
