### ISSUE TITLE
Hi! My wordpress site is not letting me create New entries for blog posts

### ISSUE THREAD

**Issue by santiagoru97** [WordPress/gutenberg#32236]
## WordPress information
- WordPress version: 
- Gutenberg version: 
- Are all plugins except Gutenberg deactivated? 
- Are you using a default theme (e.g. Twenty Twenty-One)? 

## Device information
- Device: 
- Operating system: 
- Browser:

**Comment by santiagoru97** [comment]
This is the error that shows: TypeError: Cannot read property 'setOpenState' of null
at render (https://sweetheal.com/wp-content/plugins/full-site-editing/wpcom-block-editor-nux/dist/wpcom-block-editor-nux.js?ver=118256d54ccb171d443f1945ade71c78:6:15488)
at we (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:84:293)
at zj (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:226:496)
at Th (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:223)
at tj (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:152:152)
at Te (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:151)
at https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68
at unstable_runWithPriority (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)
at Da (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60:280)
at Pg (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:14)
at ha (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60:451)
at Ja (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:224:400)
at ch (https://sweetheal.com/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:93:79)
at e (https://sweetheal.com/wp-content/plugins/gutenberg/build/data/index.js?ver=fea108f0aaaf82bb5009a166f408360d:1:18554)
at t (https://sweetheal.com/wp-content/plugins/gutenberg/build/data/index.js?ver=fea108f0aaaf82bb5009a166f408360d:1:18621)
at https://sweetheal.com/wp-content/plugins/gutenberg/build/data/index.js?ver=fea108f0aaaf82bb5009a166f408360d:1:12786
at b (https://sweetheal.com/wp-content/plugins/gutenberg/build/data/index.js?ver=fea108f0aaaf82bb5009a166f408360d:1:6309)
at https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:9455
at https://sweetheal.com/wp-content/plugins/gutenberg/build/data/index.js?ver=fea108f0aaaf82bb5009a166f408360d:1:8161
at https://sweetheal.com/wp-content/plugins/gutenberg/build/data/index.js?ver=fea108f0aaaf82bb5009a166f408360d:1:8464
at dispatch (https://sweetheal.com/wp-content/plugins/gutenberg/build/data/index.js?ver=fea108f0aaaf82bb5009a166f408360d:1:7169)
at https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:9243
at https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:5205
at Array.some (<anonymous>)
at r (https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:5180)
at https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:5133
at e.any (https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:5722)
at https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:5205
at Array.some (<anonymous>)
at r (https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:5180)
at https://sweetheal.com/wp-content/plugins/gutenberg/build/redux-routine/index.js?ver=1006a86c2b18fb05833222a51bf4f02d:1:5128

**Comment by talldan** [comment]
@santiagoru97 From the error it looks like you're using WordPress.com. 

WordPress.com is a commercial product that happens to use this open source software, so this isn't the right place to report this issue. Please could you reach out to WordPress.com support staff. Here's a link - https://wordpress.com/support/.

Thanks.
