### ISSUE TITLE
E_ERROR thrown in wp-content/plugins/gutenberg/lib/class-wp-theme-json-gutenberg.php on line 1155

### ISSUE THREAD

**Issue by MeiKatz** [WordPress/gutenberg#32342]
## Description
E_ERROR thrown in `class-wp-theme-json-gutenberg.php` on line `1155` because `$this->theme_json` is an instance of `stdClass` instead of an array.

## Step-by-step reproduction instructions
Try to edit a page.

## Expected behaviour
Edit page should work like a charm.

## Actual behaviour
Error page pops up.

## WordPress information
- WordPress version: 5.7.2
- Gutenberg version: 10.7.1 (worked until version 10.7)
- Are all plugins except Gutenberg deactivated? No
- Are you using a default theme (e.g. Twenty Twenty-One)? No

## Device information
Doesn't matter.

## Debug trace
```
Uncaught Error: Cannot use object of type stdClass as array in wordpress/wp-content/plugins/gutenberg/lib/class-wp-theme-json-gutenberg.php:1155
Stack trace:
#0 wordpress/wp-content/plugins/gutenberg/lib/class-wp-theme-json-resolver-gutenberg.php(293): WP_Theme_JSON_Gutenberg->merge(Object(WP_Theme_JSON_Gutenberg))
#1 wordpress/wp-content/plugins/gutenberg/lib/class-wp-theme-json-resolver-gutenberg.php(419): WP_Theme_JSON_Resolver_Gutenberg::get_theme_data(Array)
#2 wordpress/wp-content/plugins/gutenberg/lib/global-styles.php(108): WP_Theme_JSON_Resolver_Gutenberg::get_merged_data(Array, 'theme')
#3 wordpress/wp-includes/class-wp-hook.php(294): gutenberg_experimental_global_styles_settings(Array)
#4 wordpress/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array)
```

**Comment by MeiKatz** [comment]
Okay, solved the problem by myself: in the theme I am using I defined the `editor-color-palette` in a separate JSON file. For this task I use `json_decode`. And there was the error: I loaded the associative array as an object and not as an array. Therefore Gutenberg broke.
