### ISSUE TITLE
Error Failed to read the 'cssRules' property from 'CSSStyleSheet': 

### ISSUE THREAD

**Issue by MonicaMaroun** [WordPress/gutenberg#33155]
I was busy updating my Wordpress Page, using windows 10 and Chrome.
In the middle of editing a block the following error has come up:

Error: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at https://keicountry.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js:77:1467
    at Array.forEach (<anonymous>)
    at https://keicountry.com/wp-content/plugins/gutenberg/build/block-editor/index.min.js:77:1426
    at Tj (https://keicountry.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:179:399)
    at unstable_runWithPriority (https://keicountry.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://keicountry.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at Ra (https://keicountry.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:178:368)
    at gf (https://keicountry.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:161:497)
    at https://keicountry.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://keicountry.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)

I am now unable to access the site, as the message keeps coming up 'refused to connect' as though there is no internet.

**Comment by Mamaduka** [comment]
Hello, @MonicaMaroun

Can you provide more details on how to reproduce this issue?

Thanks

P.S. My best guess that this is coming from the `useSimulatedMediaQuery` method. cc @tellthemachines

**Comment by talldan** [comment]
There have been previous reports of this. #22507 is one that has been kept open for investigation, so I'll close this as a duplicate.

The issue usually comes from a browser extension injecting stylesheets. I'd recommend disabling browser extensions one-by-one and then checking to try to figure out which one causes it.
