### ISSUE TITLE
TypeError: f is not a function

### ISSUE THREAD

**Issue by mikeatamplify** [WordPress/gutenberg#34561]
Went to edit my pages in wordpress like normal and every time I click on a page it says "The editor has encountered an unexpected error." This is the error. Any help would be awesome! And in as simple language as possible because coding is NOT my thing, unfortunately! 

TypeError: f is not a function
    at T (https://amplify-fitness.com/wp-content/plugins/gutenberg/build/rich-text/index.min.js:1:31898)
    at Ye (https://amplify-fitness.com/wp-content/plugins/gutenberg/build/rich-text/index.min.js:1:32329)
    at js (https://amplify-fitness.com/wp-content/plugins/gutenberg/build/editor/index.min.js:31:2986)
    at Le (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:100:3)
    at Pj (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:231:183)
    at di (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:305)
    at Nj (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:236)
    at sc (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:168:96)
    at gf (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:109)
    at https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
    at unstable_runWithPriority (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26)
    at Za (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8)
    at $g (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:176)
    at ja (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:111)
    at Pa (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:157:212)
    at Me (https://amplify-fitness.com/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:110:250)
    at e (https://amplify-fitness.com/wp-content/plugins/gutenberg/build/data/index.min.js:1:20691)
    at t (https://amplify-fitness.com/wp-content/plugins/gutenberg/build/data/index.min.js:1:20758)
    at https://amplify-fitness.com/wp-content/plugins/gutenberg/build/data/index.min.js:1:14931
    at b (https://amplify-fitness.com/wp-content/plugins/gutenberg/build/data/index.min.js:1:8453)
    at https://amplify-fitness.com/wp-content/plugins/gutenberg/build/redux-routine/index.min.js:1:9455
    at https://amplify-fitness.com/wp-content/plugins/gutenberg/build/data/index.min.js:1:10306
    at https://amplify-fitness.com/wp-content/plugins/gutenberg/build/data/index.min.js:1:10609
    at dispatch (https://amplify-fitness.com/wp-content/plugins/gutenberg/build/data/index.min.js:1:9313)
    at https://amplify-fitness.com/wp-content/plugins/gutenberg/build/redux-routine/index.min.js:1:9243
    at https://amplify-fitness.com/wp-content/plugins/gutenberg/build/redux-routine/index.min.js:1:5205
    at Array.some (<anonymous>)
    at r (https://amplify-fitness.com/wp-content/plugins/gutenberg/build/redux-routine/index.min.js:1:5180)
    at https://amplify-fitness.com/wp-content/plugins/gutenberg/build/redux-routine/index.min.js:1:5133

**Comment by bph** [comment]
Hi @mikeatamplify 
This sounds like a plugin conflict with a 3rd party plugin. Did you double-check that this is happening with a default theme, and all other plugins deactivated? 
You can do so via the [Health Check plugin ](https://wordpress.org/plugins/health-check/) (it's non-developer safe!) and its Troubleshooting Mode. 

Without any details about your site (WordPress version, Gutenberg version etc. , or the exact steps to reproduce it, it's really hard to come up with a fix.

**Comment by devinmaeztri** [comment]
Hi! I'm closing this issue as the author @mikeatamplify hasn't responded in 2+ weeks. It can be reopened when needed. Thanks!
