### ISSUE TITLE
sh: wp-scripts: command not found

### ISSUE THREAD

**Issue by EightArmsWebmaster** [WordPress/gutenberg#35252]
### Description

I cannot install a block using `npx @wordpress/create-block todo-list`. The command fails at

```
Formatting JavaScript files.
/Users/djave/.npm/_npx/0890e296436e9575/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 127: npm run format
sh: wp-scripts: command not found

> todo-list@0.1.0 format
> wp-scripts format

    at makeError (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/init-wp-scripts.js:25:2)
    at async module.exports (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/scaffold.js:100:3)
    at async Command.<anonymous> (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/index.js:91:6) {
  shortMessage: 'Command failed with exit code 127: npm run format',
  command: 'npm run format',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n> todo-list@0.1.0 format\n> wp-scripts format\n',
  stderr: 'sh: wp-scripts: command not found',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

### Step-by-step reproduction instructions

Run 

    $ npx @wordpress/create-block todo-list

Get above output.
Check wp-scripts:

    $ which wp-scripts
    wp-scripts not found
   
Try to install wp-scripts

    $ npm install --save-dev @wordpress/scripts
    $ which wp-scripts
    wp-scripts not found

Try to install globally 

    $ npm install -g @wordpress/scripts
    $ which wp-scripts                 
    /Users/djave/.nvm/versions/node/v16.10.0/bin/wp-scripts

Back to the plugin directory, try again:

    $ npx @wordpress/create-block todo-list2
```
Creating a new WordPress block in "todo-list2" folder.

Creating a "block.json" file.

Creating a "package.json" file.

Installing npm dependencies. It might take a couple of minutes...

Installing `@wordpress/scripts` package. It might take a couple of minutes...

Formatting JavaScript files.

Compiling block.
/Users/djave/.npm/_npx/0890e296436e9575/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 2: npm run build
[webpack-cli] Error: Cannot find module '@wordpress/browserslist-config'
Require stack:
- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/node.js
- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js
- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/config/webpack.config.js
- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/lib/bootstrap.js
- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/bin/cli.js
- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at Object.loadQueries (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/node.js:164:35)
    at Function.select (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js:1149:26)
    at /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js:318:18)
    at browserslist (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js:444:21)
    at Object.load (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/lib/config/browserslistTargetHandler.js:70:9)
    at TARGETS.web (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/lib/config/target.js:86:47) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/node.js',
    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js',
    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/config/webpack.config.js',
    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/bin/cli.js',
    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/bin/webpack.js'
  ]
}

> todo-list2@0.1.0 build
> wp-scripts build

    at makeError (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/init-wp-scripts.js:31:2)
    at async module.exports (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/scaffold.js:100:3)
    at async Command.<anonymous> (/Users/djave/.npm/_npx/0890e296436e9575/node_modules/@wordpress/create-block/lib/index.js:91:6) {
  shortMessage: 'Command failed with exit code 2: npm run build',
  command: 'npm run build',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n> todo-list2@0.1.0 build\n> wp-scripts build\n',
  stderr: "[webpack-cli] Error: Cannot find module '@wordpress/browserslist-config'\n" +
    'Require stack:\n' +
    '- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/node.js\n' +
    '- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js\n' +
    '- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/config/webpack.config.js\n' +
    '- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/lib/webpack-cli.js\n' +
    '- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/lib/bootstrap.js\n' +
    '- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/bin/cli.js\n' +
    '- /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/bin/webpack.js\n' +
    '    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)\n' +
    '    at Function.resolve (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)\n' +
    '    at Object.loadQueries (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/node.js:164:35)\n' +
    '    at Function.select (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js:1149:26)\n' +
    '    at /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js:336:33\n' +
    '    at Array.reduce (<anonymous>)\n' +
    '    at resolve (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js:318:18)\n' +
    '    at browserslist (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js:444:21)\n' +
    '    at Object.load (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/lib/config/browserslistTargetHandler.js:70:9)\n' +
    '    at TARGETS.web (/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/lib/config/target.js:86:47) {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    '  requireStack: [\n' +
    "    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/node.js',\n" +
    "    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js',\n" +
    "    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/config/webpack.config.js',\n" +
    "    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/lib/webpack-cli.js',\n" +
    "    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/lib/bootstrap.js',\n" +
    "    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack-cli/bin/cli.js',\n" +
    "    '/Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/bin/webpack.js'\n" +
    '  ]\n' +
    '}',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

So now I've been checking if the browserlist files exist:

    $ test -f /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js && echo "File exists."
    File exists
    $ test -f /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/webpack/bin/webpack.js && echo "File exists"
    File exists
    $ test -f /Users/djave/.nvm/versions/node/v16.10.0/lib/node_modules/@wordpress/scripts/node_modules/browserslist/index.js && echo "File exists"
    File exists

But I can't help but thinking I am barking up the wrong tree entirely trying to debug this. The main issue is that the original / local wp-scripts isn't found in the shell. 

### Screenshots, screen recording, code snippet

![Gutenberg](https://user-images.githubusercontent.com/43214167/135442126-5fb933a2-d212-4689-ad48-62b731675093.gif)

### Environment info

Wordpress Version 5.8.1
node -v => v16.10.0
npm -v => 7.24.1
shell => zsh

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by EightArmsWebmaster** [comment]
I added this line to my `~/.zshrc` and it solved the issue. 

    PATH=/bin:/usr/bin:/usr/local/bin:${PATH}
    export PATH

**Comment by yglik** [comment]
i have the same issue
