### ISSUE TITLE
UnitControl: Storybook stories are crashing

### ISSUE THREAD

**Issue by mirka** [WordPress/gutenberg#35649]
I'm guessing this is just a problem with the Storybook knobs, rather than the component itself. The stories probably need to be reworked a bit.

https://wordpress.github.io/gutenberg/?path=/story/components-unitcontrol--default

```
SyntaxError: Unexpected token % in JSON at position 2
    at JSON.parse (<anonymous>)
    at Object.jsonParse [as object] (https://wordpress.github.io/gutenberg/450.d135edfc.iframe.bundle.js:2:1056170)
    at KnobManager.knob (https://wordpress.github.io/gutenberg/450.d135edfc.iframe.bundle.js:2:1061969)
    at object (https://wordpress.github.io/gutenberg/450.d135edfc.iframe.bundle.js:2:1064920)
    at Example (https://wordpress.github.io/gutenberg/main.2813274b.iframe.bundle.js:9:127748)
    at Ch (https://wordpress.github.io/gutenberg/450.d135edfc.iframe.bundle.js:2:3848263)
    at ck (https://wordpress.github.io/gutenberg/450.d135edfc.iframe.bundle.js:2:3900258)
    at bk (https://wordpress.github.io/gutenberg/450.d135edfc.iframe.bundle.js:2:3887536)
    at ak (https://wordpress.github.io/gutenberg/450.d135edfc.iframe.bundle.js:2:3887467)
    at Tj (https://wordpress.github.io/gutenberg/450.d135edfc.iframe.bundle.js:2:3887336)
```

**Comment by mirka** [comment]
Closing this for now since I haven't encountered it in a while.
