### ISSUE TITLE
[keyboard-shortcuts] Can't read property of undefined 

### ISSUE THREAD

**Issue by erwanvivien** [WordPress/gutenberg#37152]
### Description

I get this error, while I didn't have it before. I even rolled back to a month old commits to tests

```bash
Uncaught TypeError: Cannot read properties of undefined (reading 'current')
# in file /@wordpress/keyboard-shortcuts/src/hooks/use-shortcut.js:37
```
Associated with the error:
```
The above error occurred in the <NavigableToolbar> component:

    at NavigableToolbar (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:40383:5)
    at BlockContextualToolbar (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:25907:5)
    at div
    at div
    at div
    at Popover (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:137638:5)
    at BlockPopover (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:26042:5)
    at WrappedBlockPopover (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:26263:5)
    at InsertionPoint (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:27066:5)
    at div
    at BlockTools (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:26629:5)
    at div
    at BlockRefsProvider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:40894:5)
    at BlockEditorProvider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:40941:5)
    at http://127.0.0.1:3000/static/js/vendors~main.chunk.js:41232:7
    at WithRegistryProvider(BlockEditorProvider)
    at SlotFillProvider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:141558:5)
    at SlotFillProvider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:141930:5)
    at Provider (http://127.0.0.1:3000/static/js/vendors~main.chunk.js:141870:5)
    at div
    at PocPage (http://127.0.0.1:3000/static/js/main.chunk.js:8568:88)
```

I don't even know where those error come from. Version 3.0.6 of keyboard shortcuts is used everywhere in package-lock.json

My component looks something like that, I believe it's good as I never touched it :/

As soon as I click on the plus sign, I get the above errors

```jsx
function PocPage() {
  const [blocks, updateBlocks] = useState([]);

  return (
    <div className="playground">
      <SlotFillProvider>
        <BlockEditorProvider
          value={blocks}
          onInput={updateBlocks}
          onChange={updateBlocks}
        >
          <div className="playground__sidebar">
            <BlockInspector />
          </div>
          <div className="playground__content">
            <BlockTools>
              <div className="editor-styles-wrapper">
                <BlockEditorKeyboardShortcuts.Register /> {/*  Here is one potential source of the problem  */}
                <WritingFlow> {/*  Here is the second potential source of the problem  */}
                  <ObserveTyping>
                    <BlockList />
                  </ObserveTyping>
                </WritingFlow>
              </div>
            </BlockTools>
          </div>
          <Popover.Slot />
        </BlockEditorProvider>
      </SlotFillProvider>
    </div>
  );
}
export default PocPage;
```

### Step-by-step reproduction instructions

I'm using the previously given React Component

I run the page and click anywhere, the hook is triggered and the error comes with it

### Environment info

My dev environnement

```
> node --version
v16.13.0

> npm --version
7.24.2
```

My package.json (only the wordpress related stuff)
```json
{
    "@wordpress/babel-plugin-makepot": "file:packages/babel-plugin-makepot",
    "@wordpress/babel-preset-default": "file:packages/babel-preset-default",
    "@wordpress/base-styles": "4.0.0",
    "@wordpress/block-library": "6.0.0",
    "@wordpress/editor": "11.0.2",
    "@wordpress/format-library": "3.0.2",
}
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by talldan** [comment]
@erwanvivien It looks like your example is based off of the storybook. It's missing the `ShortcutProvider` component:
https://github.com/WordPress/gutenberg/blob/792c3035ca900314fad7ab8afae3486ed9951329/storybook/stories/playground/index.js#L33

It was added to the storybook in this PR - https://github.com/WordPress/gutenberg/pull/35652.

**Comment by johnstonphilip** [comment]
@talldan Do you know if this should this be updated in the [readme for the Block Editor package](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor)? It seems to be broken without this addition.

**Comment by fnwbr** [comment]
I think you're right @johnstonphilip -- can you confirm @talldan?

**Comment by erwanvivien** [comment]
At least I can confirm, as it was what I used.
