### ISSUE TITLE
"TypeError: MiniCssExtractPlugin is not a constructor" in fresh wp-scripts installation

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/gutenberg#38003]
### Description

Starting this morning I am getting a `TypeError` when trying to scaffold a project with `@wordpress/scripts`. Based on a similar issue on the CreateReactApp _(facebook/create-react-app#11930)_ Project it appears that the `mini-css-extract-plugin` was updated to version `2.5.0` and based on our `package.json` dependency it automatically pulls the latest minor version: https://github.com/WordPress/gutenberg/blob/bccf7261f9f390de6c47e6c4ee3d105e7a4164db/packages/scripts/package.json#L72

**This is the full error I am getting:**
```bash
Failed to load '/Users/fabiankaegy/Developer/personal/sandpack-block/node_modules/@wordpress/scripts/config/webpack.config.js' config
[webpack-cli] TypeError: MiniCSSExtractPlugin is not a constructor
    at Object.<anonymous> (/Users/fabiankaegy/Developer/personal/sandpack-block/node_modules/@wordpress/scripts/config/webpack.config.js:240:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at WebpackCLI.tryRequireThenImport (/Users/fabiankaegy/Developer/personal/sandpack-block/node_modules/webpack-cli/lib/webpack-cli.js:244:16)
    at loadConfigByPath (/Users/fabiankaegy/Developer/personal/sandpack-block/node_modules/webpack-cli/lib/webpack-cli.js:1710:30)
    at /Users/fabiankaegy/Developer/personal/sandpack-block/node_modules/webpack-cli/lib/webpack-cli.js:1765:11
```

### Step-by-step reproduction instructions

- Create a new project and install `@wordpress/scripts`
- add `start: wp-scripts start` to the `package.json` `scripts` section
- run `npm start`
- See the issue happen

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by fabiankaegy** [comment]
There already is an issue on the mini-css-extract-plugin repo: webpack-contrib/mini-css-extract-plugin#896

**Comment by fabiankaegy** [comment]
This is a duplicate of #37992
