### ISSUE TITLE
Enable `@wordpress/jest-console` globally for mobile unit tests

### ISSUE THREAD

**Issue by fluiddot** [WordPress/gutenberg#38177]
## What problem does this address?

Console logs are not being analyzed by mobile unit tests, which might be overlooking potential errors.

## What is your proposed solution?

Enable `@wordpress/jest-console` globally by adding it to the native Jest configuration ([reference](https://github.com/WordPress/gutenberg/blob/trunk/test/native/jest.config.js)). I tried this locally and spotted that the following seven tests fail, so as part of this effort, we should also fix them:

```
● Embed block › create by pasting URL › creates embed block when pasting URL in paragraph block

    expect(jest.fn()).not.toHaveLogged(expected)

    Expected mock function not to be called but it was called with:
    ["Processed HTML piece:·
    ", "<p>https://www.youtube.com/watch?v=lXMskKTw3Bc</p>"]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

  ● Embed block › create by pasting URL › creates link when pasting URL in paragraph block

    expect(jest.fn()).not.toHaveLogged(expected)

    Expected mock function not to be called but it was called with:
    ["Processed HTML piece:·
    ", "<p>https://www.youtube.com/watch?v=lXMskKTw3Bc</p>"]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

Summary of all failing tests
 FAIL  packages/editor/src/components/editor-help/test/index.native.js
  ● navigates back from help topic detail screen

    expect(jest.fn()).not.toHaveErrored(expected)

    Expected mock function not to be called but it was called with:
    ["Warning: You called act(async () => ...) without await. This could lead to unexpected testing behaviour, interleaving multiple act calls and mixing their scopes. You should - await act(async () => ...);"]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

 FAIL  packages/react-native-editor/src/test/setup-locale.test.js
  ● Setup locale › sets up default domain translations

    expect(jest.fn()).not.toHaveLogged(expected)

    Expected mock function not to be called but it was called with:
    ["locale", "test", {"default-string": ["default-string-translation"], "extra-string": ["extra-string-translation"]}]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

  ● Setup locale › sets up plugin translations

    expect(jest.fn()).not.toHaveLogged(expected)

    Expected mock function not to be called but it was called with:
    ["locale", "test", {"default-string": ["default-string-translation"], "extra-string": ["extra-string-translation"]}],["domain-1 - locale", "test", {"domain-1-string": ["domain-1-string-translation"]}]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

 FAIL  packages/block-library/src/cover/test/edit.native.js (21.347 s)
  ● when an image is attached › edits the focal point with a slider

    expect(jest.fn()).not.toHaveWarned(expected)

    Expected mock function not to be called but it was called with:
    ["Non-serializable values were found in the navigation state. Check:·
    FocalPoint > params.onFocalPointChange (Function)·
    This can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state for more details."]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

  ● color settings › sets a color for the overlay background when the placeholder is visible

    expect(jest.fn()).not.toHaveWarned(expected)

    Expected mock function not to be called but it was called with:
    ["Non-serializable values were found in the navigation state. Check:·
    Color > params.onColorChange (Function)·
    This can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state for more details."]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

 FAIL  packages/block-library/src/embed/test/index.native.js (42.323 s)
  ● Embed block › create by pasting URL › creates embed block when pasting URL in paragraph block

    expect(jest.fn()).not.toHaveLogged(expected)

    Expected mock function not to be called but it was called with:
    ["Processed HTML piece:·
    ", "<p>https://www.youtube.com/watch?v=lXMskKTw3Bc</p>"]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

  ● Embed block › create by pasting URL › creates link when pasting URL in paragraph block

    expect(jest.fn()).not.toHaveLogged(expected)

    Expected mock function not to be called but it was called with:
    ["Processed HTML piece:·
    ", "<p>https://www.youtube.com/watch?v=lXMskKTw3Bc</p>"]

      at Object.assertExpectedCalls (packages/jest-console/build/@wordpress/jest-console/src/index.js:36:4)

```

**Comment by dcalhoun** [comment]
This was accomplished in #53125.
