### ISSUE TITLE
@wordpress/e2e-test-utils activateTheme() creates issues due to not awaiting (or returning) when calling `switchUserToTest()`

### ISSUE THREAD

**Issue by thomasplevy** [WordPress/gutenberg#39862]
I have an e2e test that switches the active theme using `activateTheme()`. When the theme is *already set* to the requested theme (for example if I request to switch to 2022 and the active theme is already 2022) the following condition is met in the function:

https://github.com/WordPress/gutenberg/blob/f594f6cff6db36e27df4ac44e78c448bb8a173d4/packages/e2e-test-utils/src/activate-theme.js#L20-L23

I believe that L21 should be `await switchUserToTest()`. Or L21-22 should be `return switchUserToTest()` so that when calling the method an await can be added as needed.

The error I'm encountering as a result is intermittent errors being reported from apiFetch, "You are probably offline". After quite a long while trying to trace back the source of this issue I've settled on rerunning the offending test with `jest.retryTimes(2)` however when doing this I encounter the following error:

```
/home/runner/work/lifterlms/lifterlms/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:230
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.getCookies): Target closed.
    at /home/runner/work/lifterlms/lifterlms/node_modules/puppeteer-core/src/common/Connection.ts:304:16
    at new Promise (<anonymous>)
    at CDPSession.send (/home/runner/work/lifterlms/lifterlms/node_modules/puppeteer-core/src/common/Connection.ts:300:12)
    at Page.cookies (/home/runner/work/lifterlms/lifterlms/node_modules/puppeteer-core/src/common/Page.ts:1245:26)
    at getCurrentUser (/home/runner/work/lifterlms/lifterlms/node_modules/@wordpress/e2e-test-utils/build/@wordpress/e2e-test-utils/src/get-current-user.js:7:29)
    at switchUserToTest (/home/runner/work/lifterlms/lifterlms/node_modules/@wordpress/e2e-test-utils/build/@wordpress/e2e-test-utils/src/switch-user-to-test.js:13:15)
    at activateTheme (/home/runner/work/lifterlms/lifterlms/node_modules/@wordpress/e2e-test-utils/build/@wordpress/e2e-test-utils/src/activate-theme.js:[21](https://github.com/gocodebox/lifterlms/runs/5743094473?check_suite_focus=true#step:4:21):3)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.<anonymous> (/home/runner/work/lifterlms/lifterlms/tests/e2e/tests/activate/bootstrap.test.js:17:5) {
  originalMessage: ''
}
```

I believe that this is ultimately resulting from the same (somewhat misleading) fetch_error ("You are probably offline."). Everything I can find points to missing `await` in some place so that the browser is closed with an open connection which would make sense if the async `switchUserToTest()` isn't completed yet.

I'm struggling to provide a reduced test case to display the error as I can't recreate this locally, it only happens when running my tests in a CI environment.

You can see my latest failing tests at https://github.com/gocodebox/lifterlms/actions/runs/2060616521

You'll notice that some tests fail and some succeed.

**Comment by thomasplevy** [comment]
thanks @Mamaduka!
