### ISSUE TITLE
e2e: Playwright module is missing when using Windows

### ISSUE THREAD

**Issue by carolinan** [WordPress/gutenberg#40352]
### Description

On Windows 10, if I use the following commands in the command prompt:
`bash`
`npm run test-e2e:playwright`

or only
`npm run test-e2e:playwright`

I see the following:

```
Error: Cannot find module '/mnt/d/Carolina/Documents/local%20sites/fsestaging/app/public/wp-content/plugins/gutenberg/test/e2e/config/global-setup.ts'
Require stack:
- /mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/loader.js
- /mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/runner.js
- /mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/cli.js
- /mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/node_modules/playwright-core/lib/cli/cli.js
- /mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/node_modules/playwright-core/cli.js
- /mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at resolveScript (/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/loader.js:451:18)
    at Loader._processConfigObject (/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/loader.js:98:62)
    at Loader.loadConfigFile (/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/loader.js:82:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/loader.js',
    '/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/runner.js',
    '/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/lib/cli.js',
    '/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/node_modules/playwright-core/lib/cli/cli.js',
    '/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/node_modules/playwright-core/cli.js',
    '/mnt/d/Carolina/Documents/local sites/fsestaging/app/public/wp-content/plugins/gutenberg/node_modules/@playwright/test/cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gutenberg@13.0.0-rc.3 test-e2e:playwright: `playwright test --config test/e2e/playwright.config.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gutenberg@13.0.0-rc.3 test-e2e:playwright script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

-----

I have confirmed that the expected files are in the node_modules folder.
I also tried `npx playwright install` followed by `npm run test-e2e:playwright` but the result was the same.

### Step-by-step reproduction instructions

1. Do a git clone of the Gutenberg repository in the plugins folder of a WP install.
2. In the command prompt, navigate to the gutenberg folder. Use `npm install`
3.  `npm run build`
4. `bash`
5. `npm run test-e2e:playwright`

### Environment info

WordPress 5.9.3, Local, Windows 10
Gutenberg trunk
Also tested with #40336

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Related: #39721
I believe this PR #39765 will solve this problem.

**Comment by carolinan** [comment]
Thank you, lets close this as a duplicate

**Comment by Laxmankere** [comment]
e2e folder is missing

**Comment by t-hamano** [comment]
@Laxmankere Could you report a new issue with more details about the problem?
