### ISSUE TITLE
Playground broken in storybook

### ISSUE THREAD

**Issue by superdav42** [WordPress/gutenberg#41263]
### Description

[playground broken on stories page](https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default) just vist the page and you will see the error
```
TypeError: Cannot destructure property 'metadata' of '_ref' as it is null.
    at https://wordpress.github.io/gutenberg/main.6c22fb76.iframe.bundle.js:1:2077981
    at Array.filter (<anonymous>)
    at __experimentalGetCoreBlocks (https://wordpress.github.io/gutenberg/main.6c22fb76.iframe.bundle.js:1:2077953)
    at registerCoreBlocks (https://wordpress.github.io/gutenberg/main.6c22fb76.iframe.bundle.js:1:2078153)
    at https://wordpress.github.io/gutenberg/main.6c22fb76.iframe.bundle.js:20:327421
    at fk (https://wordpress.github.io/gutenberg/499.74296657.iframe.bundle.js:2:2988775)
    at exports.unstable_runWithPriority (https://wordpress.github.io/gutenberg/499.74296657.iframe.bundle.js:2:3232773)
    at gg (https://wordpress.github.io/gutenberg/499.74296657.iframe.bundle.js:2:2929523)
    at Oj (https://wordpress.github.io/gutenberg/499.74296657.iframe.bundle.js:2:2988241)
    at https://wordpress.github.io/gutenberg/499.74296657.iframe.bundle.js:2:2988154
```
and nothing works on the page.
Tag v13.1.0 seems to work fine so something must have been introduced since then.

### Step-by-step reproduction instructions

Visit https://wordpress.github.io/gutenberg/?path=/story/playground-block-editor--default or run `npm run storybook:dev` in trunk branch.

### Environment info

Latest gutenberg trunk branch.
Any browser.
Checkout tag v13.1.0 and it seems to work fine.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by AlexxAccount** [comment]
The issue is due to a change to __experimentalGetCoreBlocks which affects registerCoreBlocks. It was changed 24 days ago ([repo](https://github.com/WordPress/gutenberg/blame/trunk/packages/block-library/src/index.js)), which is why v13.1.0 works fine. It's a problem with the destructuring assignment of 'metadata', I have no idea for a solution.
