### ISSUE TITLE
Draft post image is not visible when changing phone orientation

### ISSUE THREAD

**Issue by vanessamaartinstt** [WordPress/gutenberg#42869]
## Description
When adding media (image or gallery block) and changing phone orientation, the media already added to the post is not visible anymore.

## Step-by-step reproduction instructions
1. Start a new post or edit an existent one
2. Upload an image (or a few, in Gallery block) 
3. Once uploaded change phone orientation

## Expected behaviour
Media file should be visible after changing phone orientation.

## Actual behaviour
Uploaded media file is not visible after changing phone orientation.

## Screenshots or screen recording (optional)

<details><summary>App Logs</summary>

```
01 - [Aug-01 19:27 API] Dispatching action: TaxonomyAction-FETCHED_TERMS
02 - [Aug-01 19:27 POSTS] An error occurred while updating the post formats with type: INVALID_RESPONSE
03 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
04 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
05 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
06 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
07 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
08 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
09 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
10 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
11 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
12 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
13 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
14 - [Aug-01 19:27 STATS] 🔵 Tracked: editor_closed, Properties: {"default_tab_experiment":"dashboard"}
15 - [Aug-01 19:27 UTILS] trackLastActivity, activityId: Post List
16 - [Aug-01 19:27 API] : ListStore: Loading next page
17 - [Aug-01 19:27 API] : ListStore: Loading next page
18 - [Aug-01 19:27 STATS] 🔵 Tracked: editor_session_end, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","blog_id":202984668,"content_type":"gutenberg","site_type":"blog","session_id":"4fd9b636-a093-401d-abc2-74c1ac57203a","post_type":"post","is_jetpack":false,"default_tab_experiment":"dashboard","blog_type":"wpcom","editor_has_hw_disabled":"0","outcome":"save"}
19 - [Aug-01 19:27 STATS] 🔵 Tracked: post_list_item_selected, Properties: {"blog_id":202984668,"post_id":38,"has_gutenberg_blocks":true,"site_type":"blog","action":"edit","is_jetpack":false,"default_tab_experiment":"dashboard"}
20 - [Aug-01 19:27 API] Dispatching action: UploadAction-CANCEL_POST
21 - [Aug-01 19:27 API] Dispatching action: SiteAction-FETCH_POST_FORMATS
22 - [Aug-01 19:27 MAIN] SiteStore: Fetch post formats
23 - [Aug-01 19:27 API] Dispatching action: SiteAction-FETCH_SITE_EDITORS
24 - [Aug-01 19:27 UTILS] trackLastActivity, activityId: Post Editor
25 - [Aug-01 19:27 STATS] 🔵 Tracked: editor_opened, Properties: {"blog_id":202984668,"post_id":38,"has_gutenberg_blocks":true,"site_type":"blog","post_type":"post","post_format":"standard","is_jetpack":false,"default_tab_experiment":"dashboard","editor_has_hw_disabled":"0"}
26 - [Aug-01 19:27 DB] XPostsStore: getXPostsFromDb
27 - [Aug-01 19:27 API] XPostsStore: fetchXPosts
28 - [Aug-01 19:27 API] Dispatching action: EditorThemeAction-FETCH_EDITOR_THEME
29 - [Aug-01 19:27 API] EditorThemeStore: EditorThemeStore: On FETCH_EDITOR_THEME
30 - [Aug-01 19:27 API] ReactNativeStore: executeRequest
31 - [Aug-01 19:27 API] Dispatching action: SiteAction-FETCH_POST_FORMATS
32 - [Aug-01 19:27 API] Dispatching action: TaxonomyAction-FETCH_CATEGORIES
33 - [Aug-01 19:27 MAIN] SiteStore: Fetch post formats
34 - [Aug-01 19:27 API] Dispatching action: PostAction-FETCH_REVISIONS
35 - [Aug-01 19:27 API] Dispatching action: PostAction-FETCH_REVISIONS
36 - [Aug-01 19:27 API] Received site Categories
37 - [Aug-01 19:27 API] Successfully fetched WP.com categories
38 - [Aug-01 19:27 API] Dispatching action: SiteAction-FETCHED_SITE_EDITORS
39 - [Aug-01 19:27 DB] Site found by (local) ID: 1
40 - [Aug-01 19:27 DB] Updating site: https://vanessamaartins.wordpress.com/
41 - [Aug-01 19:27 API] Received response to Settings REST request.
42 - [Aug-01 19:27 POSTS] An error occurred while updating the post formats with type: INVALID_RESPONSE
43 - [Aug-01 19:27 API] Volley error on https://public-api.wordpress.com/wpcom/v2/sites/202984668/xposts/?decode_html=true&_locale=pt_BR - exception: null
44 - [Aug-01 19:27 API] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:193)
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

45 - [Aug-01 19:27 API] Dispatching action: TaxonomyAction-FETCHED_TERMS
46 - [Aug-01 19:27 POSTS] An error occurred while updating the post formats with type: INVALID_RESPONSE
47 - [Aug-01 19:27 API] Dispatching action: PostAction-FETCHED_REVISIONS
48 - [Aug-01 19:27 API] Dispatching action: PostAction-FETCHED_REVISIONS
49 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
50 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
51 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
52 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
53 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
54 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
55 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
56 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
57 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
58 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
59 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
60 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
61 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
62 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
63 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
64 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
65 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
66 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
67 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
68 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
69 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
70 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
71 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
72 - [Aug-01 19:27 SETTINGS] An error occurred while updating the post formats with type: INVALID_RESPONSE
73 - [Aug-01 19:27 STATS] 🔵 Tracked: editor_session_start, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","blog_id":202984668,"startup_time_ms":1242,"site_type":"blog","session_id":"e2bebcdc-2180-44f6-b46a-3f5eec08e579","is_jetpack":false,"default_tab_experiment":"dashboard","blog_type":"wpcom","unsupported_blocks":[],"content_type":"gutenberg","post_type":"post","editor_has_hw_disabled":"0","unstable_gallery_with_image_blocks":true}
74 - [Aug-01 19:27 API] ReactNativeStore: executeRequest
75 - [Aug-01 19:27 API] ReactNativeStore: executeRequest
76 - [Aug-01 19:27 API] ReactNativeStore: executeRequest
77 - [Aug-01 19:27 API] ReactNativeStore: executeRequest
78 - [Aug-01 19:27 STATS] 🔵 Tracked: editor_closed, Properties: {"default_tab_experiment":"dashboard"}
79 - [Aug-01 19:27 UTILS] trackLastActivity, activityId: Post List
80 - [Aug-01 19:27 STATS] 🔵 Tracked: editor_session_end, Properties: {"has_unsupported_blocks":"0","editor":"gutenberg","blog_id":202984668,"content_type":"gutenberg","site_type":"blog","session_id":"e2bebcdc-2180-44f6-b46a-3f5eec08e579","post_type":"post","is_jetpack":false,"default_tab_experiment":"dashboard","blog_type":"wpcom","editor_has_hw_disabled":"0","outcome":"save"}
81 - [Aug-01 19:27 UTILS] trackLastActivity, activityId: My Site
82 - [Aug-01 19:27 API] Dispatching action: AccountAction-FETCH_ACCOUNT
83 - [Aug-01 19:27 PROFILING] Visual Editor Startup: begin
84 - [Aug-01 19:27 PROFILING] Visual Editor Startup: 0 ms, EditorFragment.onCreate
85 - [Aug-01 19:27 PROFILING] Visual Editor Startup: 6136 ms, WPMainActivity.onResume
86 - [Aug-01 19:27 PROFILING] Visual Editor Startup: end, 6136 ms
87 - [Aug-01 19:27 API] Dispatching action: SiteAction-FETCH_SITE
88 - [Aug-01 19:27 MAIN] SiteStore: Fetch site
89 - [Aug-01 19:27 API] Dispatching action: SiteAction-FETCH_JETPACK_CAPABILITIES
90 - [Aug-01 19:27 MAIN] DynamicCardStore: Get dynamic card
91 - [Aug-01 19:27 API] Dispatching action: AccountAction-FETCHED_ACCOUNT
92 - [Aug-01 19:27 API] CardsStore: fetchCards
93 - [Aug-01 19:27 API] Dispatching action: SiteAction-FETCHED_JETPACK_CAPABILITIES
94 - [Aug-01 19:27 DB] Site found by (local) ID: 1
95 - [Aug-01 19:27 DB] Updating site: https://vanessamaartins.wordpress.com/
96 - [Aug-01 19:27 STATS] 🔵 Tracked: me_tab_accessed, Properties: {"default_tab_experiment":"dashboard"}
97 - [Aug-01 19:27 READER] reader post list > saving instance state
98 - [Aug-01 19:27 STATS] 🔵 Tracked: support_opened, Properties: {"default_tab_experiment":"dashboard","origin":"ME_SCREEN_HELP"}
99 - [Aug-01 19:27 UTILS] trackLastActivity, activityId: Help Screen
```

</details>

https://user-images.githubusercontent.com/107848100/182233698-49c6d66e-cbca-4763-8d06-5a6850318a23.mp4

## WordPress information
- WordPress version: 20.4
- Gutenberg version: v13.7.3
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: Moto G7 Plus
- Operating system: Android 10
- WordPress app version: 20.4-rc-1

**Comment by geriux** [comment]
Thanks for opening this ticket @vanessamaartinstt 🙇 

I've created a [PR](https://github.com/WordPress/gutenberg/pull/42900) to add a workaround for this issue, once this is merged we'll work on a new beta before the release.

Adding a note here that this is only affecting Android, on iOS works correctly.
