### ISSUE TITLE
TypeError: asset.source.buffer is not a function while using "@wordpress/dependency-extraction-webpack-plugin"

### ISSUE THREAD

**Issue by heyitsuzair** [WordPress/gutenberg#45218]
### Description

I am creating WordPress theme but am stuck on an error. When I try to create a build it shows the error "asset.source.buffer is not a function" which is due to @wordpress/dependency-extraction-webpack-plugin webpack plugin. When I Remove this plugin, it starts working normally but I want to use @wordpress/dependency-extraction-webpack-plugin to combine assets.

Webpack Config

_Formatted by @t-hamano_

```javascript
const path = require( 'path' );

const JS_DIR = path.resolve( __dirname, 'js/' );
const IMG_DIR = path.resolve( __dirname, 'images/' );
const BUILD_DIR = path.resolve( __dirname, 'build' );

const MiniCssExtractPlugin = require( 'mini-css-extract-plugin' );
const { CleanWebpackPlugin } = require( 'clean-webpack-plugin' );
const CssMinimizerPlugin = require( 'css-minimizer-webpack-plugin' );
/**
 * WordPress dependencies
 */
const DependencyExtractionWebpackPlugin = require( '@wordpress/dependency-extraction-webpack-plugin' );
const Uglify = require( 'uglifyjs-webpack-plugin' );

const entry = {
	index: JS_DIR + '/index.js',
	single: JS_DIR + '/single.js',
	editor: JS_DIR + '/editor.js',
	block: JS_DIR + '/block.js',
};
const output = {
	path: BUILD_DIR,
	filename: 'js/[name].js',
};
const rules = [
	{
		test: /.js$/,
		include: [ JS_DIR ],
		exclude: /node_modules/,
		use: 'babel-loader',
	},
	{
		test: /.scss$/,
		exclude: /node_modules/,
		use: [ MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader' ],
	},
	{
		test: /.(png|jpg|svg|jpeg|gif|ico)$/,
		use: [
			{
				loader: 'file-loader',
				options: {
					name: '[path][name].[ext]',
					publicPath:
						'production' === process.env.NODE._ENV
							? '../'
							: '../../',
				},
			},
		],
	},
];

const plugins = ( argv ) => [
	new CleanWebpackPlugin( {
		cleanStaleWebpackAssets: argv.mode === 'production',
	} ),

	new MiniCssExtractPlugin( {
		filename: 'css/[name].css',
	} ),

	new DependencyExtractionWebpackPlugin( {
		injectPolyfill: true,
		// combineAssets: true,
	} ),
];

module.exports = ( env, argv ) => ( {
	entry,
	output,
	devtool: 'source-map',
	module: {
		rules,
	},
	optimization: {
		minimizer: [
			new CssMinimizerPlugin(),
			new Uglify( {
				cache: false,
				parallel: true,
				sourceMap: false,
			} ),
		],
	},
	plugins: plugins( argv ),
	externals: {
		jquery: 'jquery',
	},
} );
```

### Step-by-step reproduction instructions

See The Above Description

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
Thank you for your contribution.
I have edited your comment and formatted the code presented to make it easier to tackle this issue.

**Comment by Mamaduka** [comment]
Hi, @heyitsuzair

I just wanted to check if you're still experiencing this issue.

Based on the error, this looks like a compatibility issue between Webpack plugins.

**Comment by heyitsuzair** [comment]
The issue was solved by downgrading plugins

**Comment by Mamaduka** [comment]
@heyitsuzair, can you provide more details? For example, which plugin downgrade resolved the problem, and to what versions?

**Comment by heyitsuzair** [comment]
@wordpress/dependency-extraction-webpack-plugin

**Comment by acketon** [comment]
I've experienced the same error when running `npm run build` in a custom block that another member of the team built and compiled on a separate machine. This was my first time running `npm install` for this block and attempting to work on it. 

Node version 16.16.0
The block is using an older version of `"@wordpress/scripts": "^13.0.0",`

The error: 
```
TypeError: asset.source.buffer is not a function
    at DependencyExtractionWebpackPlugin.addAssets (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/@wordpress/dependency-extraction-webpack-plugin/lib/index.js:216:31)
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/@wordpress/dependency-extraction-webpack-plugin/lib/index.js:120:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compiler.js:491:19)
    at onCompiled (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Watching.js:51:19)
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compilation.js:1342:27)
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compiler.js:675:18
    at /Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/acketon/Git/bu-stories/blocks/stickers/node_modules/webpack/lib/Compilation.js:1253:28)
```

A colleague was able to compile the same code without issue so I compared the versions that were installed by running: 
`npm list @wordpress/dependency-extraction-webpack-plugin` and saw that for my machine it was installing 3.7.0:
![image](https://user-images.githubusercontent.com/3139096/219423134-789ead61-f683-4655-84af-2ce9b5aa7395.png)

Yet on the colleague's machine it was 3.3.2

I was able to get the block to compile by running `npm install @wordpress/dependency-extraction-webpack-plugin@3.3.2` and adding that as a dependency in my package.json file. 

It seems that something is different or there was a breaking change in some point release update of that package somewhere between 3.3.2 and 3.7.0?
