### ISSUE TITLE
Fatal: Call to private method WP_Theme_JSON::maybe_opt_in_into_settings()

### ISSUE THREAD

**Issue by ironprogrammer** [WordPress/gutenberg#45292]
### Description

I realize this will be moot after 6.1 is released, but for now I'm receiving a fatal error after activating Gutenberg on 5.9. The error does not occur for 5.9.1 and up.

<blockquote>Fatal error: Uncaught Error: Call to private method WP_Theme_JSON::maybe_opt_in_into_settings() from context 'WP_Theme_JSON_6_1' in /Users/brian/Sites/wp-install-test/wp-content/plugins/gutenberg/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php:153</blockquote>

### Step-by-step reproduction instructions

1. Install WordPress 5.9 (not a minor version update).
2. In `wp-config.php`, disable core auto updates with `define( 'WP_AUTO_UPDATE_CORE', false );`, or via WP-CLI: `wp config set WP_AUTO_UPDATE_CORE false --raw`.
3. Install Gutenberg via *Plugins > Add New*, or via WP-CLI: `wp plugin install gutenberg`.
4. Activate the plugin in the UI, or via WP-CLI: `wp plugin activate gutenberg`.
5. The following fatal error occurs:
```sh
Fatal error: Uncaught Error: Call to private method WP_Theme_JSON::maybe_opt_in_into_settings() from context 'WP_Theme_JSON_6_1' in ../wp-content/plugins/gutenberg/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php:153
 Stack trace:
  #0 ../wp-content/plugins/gutenberg/lib/experimental/class-wp-theme-json-resolver-gutenberg.php(198): WP_Theme_JSON_6_1->__construct()
  #1 ../wp-content/plugins/gutenberg/lib/experimental/register-webfonts-from-theme-json.php(13): WP_Theme_JSON_Resolver_Gutenberg::get_merged_data()
  #2 ../wp-includes/class-wp-hook.php(307): gutenberg_register_webfonts_from_theme_json('')
  #3 ../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
  #4 ../wp-includes/plugin.php(474): WP_Hook->do_action(Array)
  #5 ../wp-settings.php(587): do_action('init')
  #6 .. in ../wp-content/plugins/gutenberg/lib/compat/wordpress-6.1/class-wp-theme-json-6-1.php on line 153
```

The `wp-content/gutenberg` folder must be moved/deleted to return the site to an operational state.

### Environment info

- Hardware: MacBook Pro Apple M1 Pro
- OS: macOS 12.6
- Browser: Safari 16.0
- Server: nginx/1.23.2
- PHP: 7.4.32
- WordPress: 5.9
- Theme: twentytwentytwo v1.0
- Active Plugins:
  - Gutenberg v14.3.1

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
Closing since the issue is no longer valid with recent WP versions.
