### ISSUE TITLE
WordPress 6.1: TypeError: (0 , E.__experimentaluseLayoutClasses) is not a function

### ISSUE THREAD

**Issue by ritvikos** [WordPress/gutenberg#45479]
### Description

```
TypeError: (0 , E.__experimentaluseLayoutClasses) is not a function
at Xt (https://website-name.com/queries/js/dist/edit-post.min.js:7:40200)
at ct (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:43430)
at os (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:111136)
at Ur (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:77643)
at Ir (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:77571)
at Dr (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:77434)
at Pr (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:74429)
at https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:30173
at unstable_runWithPriority (https://website-name.com/queries/js/dist/vendor/react.min.js:9:7431)
at xn (https://website-name.com/queries/js/dist/vendor/react-dom.min.js:9:29950)
```

The Main Site is working! But, the editor is not working and show an “Attempt Block” option with Blank white Screen. When I click it, it doesn’t do anything.

What I’ve tried:
1. Updating All Plugins
2. Updating All Themes (On main site: GeneratePress)
3. Re-installing WordPress 6.1
4. Disable Browser Extensions
5. Restart All Process from Hosting

*Can’t share site’s name.
Thanks!

### Step-by-step reproduction instructions

1. Go to "Posts"
2. Click "Edit" button
3. Error will occur

### Screenshots, screen recording, code snippet

![errr](https://user-images.githubusercontent.com/73193822/199432592-41519a4e-6588-4605-bc5b-30907de9e055.png)

### Environment info

- WordPress 6.1
- Browser - Chrome, Brave, Chrome Dev, Edge, Firefox Dev
- Windows 11 (updated)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ritvikos** [comment]
Edit: After numerous refreshes, the error is not visible anymore in firefox dev!!
I wasn't sure if its theme-specific issue, so I opened another [issue on their repo](https://github.com/tomusborne/generatepress/issues/465) too!

**Comment by skorasaurus** [comment]
Can you share a list of what plugins are currently installed on the website and if possible; disable all other plugins and see if the issue is still occurring?

**Comment by ritvikos** [comment]
Found! WP Hide and Security Enhancer is causing this issue! 
Thanks for suggestion :)
