### ISSUE TITLE
Cannot `npm install` with npm 7 and higher

### ISSUE THREAD

**Issue by marekdedic** [WordPress/gutenberg#46652]
### Description

Part of [Upgrade node and npm to latest LTS versions](https://github.com/WordPress/gutenberg/issues/34801).

Hi,
I tried to set up a local copy of the repo in order to fix #46626, but I can't even `npm install`...

```
❯ npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile Error: Integrity checksum failed when using sha512: wanted sha512-AV33EzqiFJ3fj+mPlKABN59YFPReLkDxQnj067Z3uEOeRQf3g05WprL0RDuqM7UBhSRo9W1rMSC2KvZmjE5UOA== but got sha512-PkUpF+qoXTqhOeWL9fu7As8LXsIUZ1WYaJiY/a7McAQzxjk82OF0tibkFXVCDImZtWxbvojFjerkiLb0/q8mew==.
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:144:35)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for prettier@2.6.2 Error: Integrity checksum failed when using sha512: wanted sha512-AV33EzqiFJ3fj+mPlKABN59YFPReLkDxQnj067Z3uEOeRQf3g05WprL0RDuqM7UBhSRo9W1rMSC2KvZmjE5UOA== but got sha512-PkUpF+qoXTqhOeWL9fu7As8LXsIUZ1WYaJiY/a7McAQzxjk82OF0tibkFXVCDImZtWxbvojFjerkiLb0/q8mew==.
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:144:35)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'EINTEGRITY'
npm WARN old lockfile }
npm WARN old lockfile react-native-gesture-handler: No matching version found for react-native-gesture-handler@2.3.2-wp-2.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for react-native-gesture-handler@2.3.2-wp-2 react-native-gesture-handler: No matching version found for react-native-gesture-handler@2.3.2-wp-2.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '2.3.2-wp-2',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.0.1',          '0.0.2',          '0.0.3',          '0.0.4',
npm WARN old lockfile     '0.1.0',          '0.2.0',          '1.0.0-alpha.1',  '1.0.0-alpha.2',
npm WARN old lockfile     '1.0.0-alpha.4',  '1.0.0-alpha.5',  '1.0.0-alpha.7',  '1.0.0-alpha.8',
npm WARN old lockfile     '1.0.0-alpha.9',  '1.0.0-alpha.10', '1.0.0-alpha.11', '1.0.0-alpha.12',
npm WARN old lockfile     '1.0.0-alpha.13', '1.0.0-alpha.14', '1.0.0-alpha.15', '1.0.0-alpha.16',
npm WARN old lockfile     '1.0.0-alpha.17', '1.0.0-alpha.18', '1.0.0-alpha.19', '1.0.0-alpha.20',
npm WARN old lockfile     '1.0.0-alpha.21', '1.0.0-alpha.22', '1.0.0-alpha.23', '1.0.0-alpha.24',
npm WARN old lockfile     '1.0.0-alpha.25', '1.0.0-alpha.26', '1.0.0-alpha.27', '1.0.0-alpha.28',
npm WARN old lockfile     '1.0.0-alpha.29', '1.0.0-alpha.30', '1.0.0-alpha.31', '1.0.0-alpha.32',
npm WARN old lockfile     '1.0.0-alpha.33', '1.0.0-alpha.34', '1.0.0-alpha.35', '1.0.0-alpha.36',
npm WARN old lockfile     '1.0.0-alpha.37', '1.0.0-alpha.39', '1.0.0-alpha.40', '1.0.0-alpha.41',
npm WARN old lockfile     '1.0.0-alpha.42', '1.0.0-alpha.43', '1.0.0',          '1.0.1',
npm WARN old lockfile     '1.0.2',          '1.0.3',          '1.0.4',          '1.0.5',
npm WARN old lockfile     '1.0.6',          '1.0.7',          '1.0.8',          '1.0.9',
npm WARN old lockfile     '1.0.10',         '1.0.11',         '1.0.12',         '1.0.14',
npm WARN old lockfile     '1.0.15',         '1.0.16',         '1.1.0',          '1.0.17',
npm WARN old lockfile     '1.2.0',          '1.2.1',          '1.1.1',          '1.2.2',
npm WARN old lockfile     '1.3.0',          '1.1.2',          '1.1.3',          '1.4.0',
npm WARN old lockfile     '1.4.1',          '1.5.0',          '1.5.1',          '1.5.2',
npm WARN old lockfile     '1.5.3',          '1.5.4',          '1.5.5',          '1.5.6',
npm WARN old lockfile     '1.6.0',          '1.6.1',          '1.7.0',          '1.8.0',
npm WARN old lockfile     '1.9.0',          '1.10.0',         '1.10.1',         '1.10.2',
npm WARN old lockfile     '1.10.3',         '2.0.0',          '2.1.0',          '2.1.1',
npm WARN old lockfile     '2.2.0',          '2.1.2',          '2.1.3',          '2.3.0',
npm WARN old lockfile     '2.3.1',          '2.3.2',          '2.4.0',          '2.4.1',
npm WARN old lockfile     ... 9 more items
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '2.8.0' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile Error: Integrity checksum failed when using sha512: wanted sha512-iwKdUpLc7lGN0+yiVfKxvvouMEXJeR4sRmfXFKXNnWOaBRdcf412zPa5vK4yEGPh5s38GDR29jYMM/RRw5U4nw== but got sha512-LBGmP85xg1/im4+l3pSXjbq7DI4o2dhSoHV8n+xpUjEHWwAj54GcJwYdmFSjOYz7LnlEi30KvTBekiZuW8L8Aw==.
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:144:35)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for react-native-hr@1.1.3 Error: Integrity checksum failed when using sha512: wanted sha512-iwKdUpLc7lGN0+yiVfKxvvouMEXJeR4sRmfXFKXNnWOaBRdcf412zPa5vK4yEGPh5s38GDR29jYMM/RRw5U4nw== but got sha512-LBGmP85xg1/im4+l3pSXjbq7DI4o2dhSoHV8n+xpUjEHWwAj54GcJwYdmFSjOYz7LnlEi30KvTBekiZuW8L8Aw==.
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:144:35)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'EINTEGRITY'
npm WARN old lockfile }
npm WARN old lockfile react-native-hsv-color-picker: No matching version found for react-native-hsv-color-picker@1.0.1-wp-3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for react-native-hsv-color-picker@1.0.1-wp-3 react-native-hsv-color-picker: No matching version found for react-native-hsv-color-picker@1.0.1-wp-3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '1.0.1-wp-3',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.0.1', '0.0.2',
npm WARN old lockfile     '0.0.3', '0.0.4',
npm WARN old lockfile     '1.0.0', '1.0.1',
npm WARN old lockfile     '1.0.2'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '1.0.2' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile react-native-keyboard-aware-scroll-view: No matching version found for react-native-keyboard-aware-scroll-view@0.8.8-wp-1.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for react-native-keyboard-aware-scroll-view@0.8.8-wp-1 react-native-keyboard-aware-scroll-view: No matching version found for react-native-keyboard-aware-scroll-view@0.8.8-wp-1.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '0.8.8-wp-1',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.0.1', '0.0.2', '0.0.3', '0.0.4',
npm WARN old lockfile     '0.0.5', '0.0.6', '0.0.7', '0.1.0',
npm WARN old lockfile     '0.1.1', '0.1.2', '0.2.0', '0.2.1',
npm WARN old lockfile     '0.2.2', '0.2.3', '0.2.4', '0.2.5',
npm WARN old lockfile     '0.2.6', '0.2.7', '0.2.8', '0.2.9',
npm WARN old lockfile     '0.3.0', '0.4.0', '0.4.1', '0.4.2',
npm WARN old lockfile     '0.4.3', '0.4.4', '0.5.0', '0.6.0',
npm WARN old lockfile     '0.7.0', '0.7.1', '0.7.2', '0.7.3',
npm WARN old lockfile     '0.7.4', '0.8.0', '0.9.0', '0.9.1',
npm WARN old lockfile     '0.9.2', '0.9.3', '0.9.4', '0.9.5'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '0.9.5' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile react-native-linear-gradient: No matching version found for react-native-linear-gradient@2.5.6-wp-3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for react-native-linear-gradient@2.5.6-wp-3 react-native-linear-gradient: No matching version found for react-native-linear-gradient@2.5.6-wp-3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '2.5.6-wp-3',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.1.0',   '0.1.1',  '0.1.2',       '0.1.3',
npm WARN old lockfile     '0.1.4',   '0.1.5',  '0.1.6',       '0.1.7',
npm WARN old lockfile     '0.1.8',   '0.1.9',  '0.2.0',       '0.3.0',
npm WARN old lockfile     '0.3.1',   '0.3.2',  '1.0.0-alpha', '1.1.0-alpha',
npm WARN old lockfile     '1.2.0',   '1.3.0',  '1.3.1',       '1.3.2',
npm WARN old lockfile     '1.4.0',   '1.5.0',  '1.5.1',       '1.5.2',
npm WARN old lockfile     '1.5.3',   '1.5.4',  '1.5.5',       '1.5.6',
npm WARN old lockfile     '1.5.7',   '1.5.8',  '1.5.9',       '1.5.10',
npm WARN old lockfile     '1.5.11',  '1.5.12', '1.5.13',      '1.5.14',
npm WARN old lockfile     '1.5.15',  '1.6.0',  '1.6.1',       '1.6.2',
npm WARN old lockfile     '2.0.0',   '2.1.0',  '2.2.0',       '2.3.0',
npm WARN old lockfile     '2.4.0',   '2.4.1',  '2.4.2',       '2.4.3-0',
npm WARN old lockfile     '2.4.3-1', '2.4.3',  '2.4.4',       '2.5.1',
npm WARN old lockfile     '2.5.2',   '2.5.3',  '2.5.4',       '2.5.5',
npm WARN old lockfile     '2.5.6',   '2.6.0',  '2.6.1',       '2.6.2'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '2.6.2', next: '2.5.1' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile react-native-prompt-android: No matching version found for react-native-prompt-android@1.0.0-wp-3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for react-native-prompt-android@1.0.0-wp-3 react-native-prompt-android: No matching version found for react-native-prompt-android@1.0.0-wp-3.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '1.0.0-wp-3',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.0.1', '0.0.2', '0.0.3',
npm WARN old lockfile     '0.0.4', '0.0.5', '0.0.6',
npm WARN old lockfile     '0.0.7', '0.0.8', '0.1.0',
npm WARN old lockfile     '0.2.0', '0.3.0', '0.3.1',
npm WARN old lockfile     '0.3.2', '0.3.3', '0.3.4',
npm WARN old lockfile     '0.3.5', '0.3.6', '1.0.0',
npm WARN old lockfile     '1.1.0'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '1.1.0' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile react-native-reanimated: No matching version found for react-native-reanimated@2.9.1-wp-2.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for react-native-reanimated@2.9.1-wp-2 react-native-reanimated: No matching version found for react-native-reanimated@2.9.1-wp-2.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '2.9.1-wp-2',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.0.1-alpha',   '1.0.0-alpha.2',   '1.0.0-alpha.3',   '1.0.0-alpha.4',
npm WARN old lockfile     '1.0.0-alpha.5', '1.0.0-alpha.6',   '1.0.0-alpha.7',   '1.0.0-alpha.8',
npm WARN old lockfile     '1.0.0-alpha.9', '1.0.0-alpha.10',  '1.0.0-alpha.11',  '1.0.0-alpha.12',
npm WARN old lockfile     '1.0.0',         '1.0.1',           '1.1.0',           '1.2.0',
npm WARN old lockfile     '1.3.0-alpha',   '1.3.0',           '1.3.1',           '1.3.2',
npm WARN old lockfile     '1.4.0',         '1.5.0',           '1.6.0',           '1.7.0',
npm WARN old lockfile     '1.7.1',         '1.8.0',           '1.9.0',           '2.0.0-alpha.1',
npm WARN old lockfile     '2.0.0-alpha.2', '2.0.0-alpha.3',   '2.0.0-alpha.4',   '1.10.0',
npm WARN old lockfile     '1.10.1',        '2.0.0-alpha.5',   '1.10.2',          '1.11.0',
npm WARN old lockfile     '1.12.0',        '1.13.0',          '2.0.0-alpha.6',   '2.0.0-alpha.7',
npm WARN old lockfile     '1.13.1',        '2.0.0-alpha.6.1', '2.0.0-alpha.8',   '1.13.2',
npm WARN old lockfile     '2.0.0-alpha.9', '2.0.0-alpha.9.1', '2.0.0-alpha.9.2', '2.0.0-rc.0',
npm WARN old lockfile     '2.0.0-rc.1',    '2.0.0-rc.2',      '2.0.0-rc.3',      '2.0.0',
npm WARN old lockfile     '1.13.3',        '2.0.1',           '2.1.0',           '2.2.0',
npm WARN old lockfile     '2.3.0-alpha.1', '2.3.0-alpha.2',   '2.3.0-alpha.3',   '2.2.1',
npm WARN old lockfile     '2.2.2',         '2.3.0-beta.1',    '2.3.0-beta.2',    '2.2.3',
npm WARN old lockfile     '2.3.0-beta.3',  '2.2.4',           '2.3.0-beta.4',    '2.3.0',
npm WARN old lockfile     '2.3.1',         '2.4.0',           '2.4.1',           '2.3.2',
npm WARN old lockfile     '1.13.4',        '2.3.3',           '2.5.0',           '2.6.0',
npm WARN old lockfile     '2.7.0',         '2.8.0',           '3.0.0-rc.0',      '2.9.0',
npm WARN old lockfile     '2.9.1',         '3.0.0-rc.1',      '3.0.0-rc.2',      '2.10.0',
npm WARN old lockfile     '3.0.0-rc.3',    '2.11.0',          '2.12.0',          '3.0.0-rc.4',
npm WARN old lockfile     '3.0.0-rc.5',    '2.13.0',          '3.0.0-rc.6',      '3.0.0-rc.7',
npm WARN old lockfile     '3.0.0-rc.8'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '2.13.0', next: '3.0.0-rc.8', 'reanimated-1': '1.13.4' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm WARN old lockfile react-native-video: No matching version found for react-native-video@5.2.0-wp-5.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24)
npm WARN old lockfile  Could not fetch metadata for react-native-video@5.2.0-wp-5 react-native-video: No matching version found for react-native-video@5.2.0-wp-5.
npm WARN old lockfile     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
npm WARN old lockfile     at async Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:733:24) {
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '5.2.0-wp-5',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '0.1.0',         '0.1.2',        '0.1.3',         '0.1.4',
npm WARN old lockfile     '0.1.5',         '0.1.6',        '0.1.8',         '0.1.9',
npm WARN old lockfile     '0.2.0',         '0.2.1',        '0.2.2',         '0.2.3',
npm WARN old lockfile     '0.2.4',         '0.2.5',        '0.2.6',         '0.2.7',
npm WARN old lockfile     '0.2.8',         '0.2.9',        '0.3.1',         '0.3.2',
npm WARN old lockfile     '0.3.3',         '0.3.5',        '0.3.6',         '0.4.0',
npm WARN old lockfile     '0.4.1',         '0.4.2',        '0.4.3',         '0.4.4',
npm WARN old lockfile     '0.4.5',         '0.4.7',        '0.4.8',         '0.4.9',
npm WARN old lockfile     '0.4.10',        '0.4.11',       '0.4.12',        '0.5.0',
npm WARN old lockfile     '0.5.1',         '0.6.0',        '0.6.1',         '0.7.0',
npm WARN old lockfile     '0.7.1',         '0.8.0-beta',   '0.8.0-rc',      '0.8.0',
npm WARN old lockfile     '0.9.0',         '1.0.0',        '1.2.0',         '2.0.0',
npm WARN old lockfile     '2.1.0',         '2.1.1',        '2.2.0',         '2.3.0',
npm WARN old lockfile     '2.3.1',         '3.0.0',        '3.1.0',         '3.2.0',
npm WARN old lockfile     '3.2.1',         '4.0.0',        '4.0.1',         '4.1.0',
npm WARN old lockfile     '4.2.0',         '4.3.0',        '4.3.1',         '4.4.0',
npm WARN old lockfile     '4.4.1',         '4.4.2',        '4.4.3',         '4.4.4',
npm WARN old lockfile     '5.0.0',         '5.0.1',        '5.0.2',         '5.1.0-alpha1',
npm WARN old lockfile     '5.1.0-alpha2',  '5.1.0-alpha3', '5.1.0-alpha4',  '5.1.0-alpha5',
npm WARN old lockfile     '5.1.0-alpha6',  '4.4.5',        '5.1.0-alpha7',  '5.1.0-alpha8',
npm WARN old lockfile     '5.1.1',         '5.2.0-alpha1', '5.2.0',         '6.0.0-alpha.0',
npm WARN old lockfile     '6.0.0-alpha.1', '5.2.1',        '6.0.0-alpha.2', '6.0.0-alpha.3',
npm WARN old lockfile     '6.0.0-alpha.4'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '5.2.1', alpha: '6.0.0-alpha.4', next: '6.0.0-alpha.1' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gutenberg@14.8.0-rc.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"18.2.0" from the root project
npm ERR!   peer react@"*" from @wordpress/react-native-aztec@1.86.0
npm ERR!   node_modules/@wordpress/react-native-aztec
npm ERR!     @wordpress/react-native-aztec@"file:packages/react-native-aztec" from the root project
npm ERR!   29 more (@wordpress/block-directory, @wordpress/block-editor, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"18.0.0" from react-native@0.69.4
npm ERR! node_modules/react-native
npm ERR!   dev react-native@"0.69.4" from the root project
npm ERR!   peer react-native@"*" from @wordpress/react-native-aztec@1.86.0
npm ERR!   node_modules/@wordpress/react-native-aztec
npm ERR!     @wordpress/react-native-aztec@"file:packages/react-native-aztec" from the root project
npm ERR!   3 more (@wordpress/react-native-aztec, ...)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /home/marekdedic/.npm/_logs/2022-12-19T13_14_46_578Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marekdedic/.npm/_logs/2022-12-19T13_14_46_578Z-debug-0.log
```

### Step-by-step reproduction instructions

1. Clone this repo
2. `npm install`

### Environment info

- I'm on tag `@wordpress/data@8.0.0`
- Node version: 18.12.1
- NPM version: 9.2.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by glendaviesnz** [comment]
Thanks for looking to contribute some fixes @marekdedic. Currently, you need to run [npm >=6.9.0 && <7](https://github.com/WordPress/gutenberg/blob/trunk/package.json#L19) in this repo.

**Comment by desrosj** [comment]
I'm going to close this out because this is currently expected and intentionally not supported at the moment.

When #48950 is resolved, then using newer versions of Node/npm will be supported.
