### ISSUE TITLE
Error when opening gutenburg

### ISSUE THREAD

**Issue by janw-oostendorp** [WordPress/gutenberg#4753]
On a freshly installed WordPress I get an error when opening the demo, a new post and/or editing a post with just the title _test_ and the content _test_

Deactivated all plugins, Switched to a blank twentyseventeen.  
A freshly installed site. The user was an admin (no custom roles), An new user (editor) has the same problem.
I just open the demo page, I do see a flash of the demo page, then white screen with error.
The site is using WordPress in a subfolder. (`public_html/wp/wp-includes` & `public_html/wp-content/plugins/gutenberg`)

Only 404 I get is on the vimeo Oembed `https://munchkin.janw.me/wp-json/oembed/1.0/proxy?url=https%3A%2F%2Fvimeo.com%2F22439234&_wpnonce=a3d4497be1`

On Ubuntu Firefox 58.0

I get the error
`TypeError: e.capabilities is undefined`
```
c/o<@https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:11:13421
n@https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:6:21464
c@https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:6:17626
c@https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:11:13398
beginWork@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:133:398
d@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:158:393
f@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:214
g@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:462
t@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:3
x@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247
r@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:164:368
v@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:163:278
enqueueSetState@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:124:386
p.prototype.setState@https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react.min.ca6e2421.js:18:82
value@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:337808
value/<@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:338975
E/</<@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:49155
E/<@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:49025
u@https://munchkin.janw.me/wp-content/plugins/gutenberg/components/build/index.js?ver=1516900642:6:52658

```

So I check chromium (63.0.3239.84) and I get an other error.
Also on chrome windows10
```
TypeError: Cannot read property 'level_1' of undefined
    at https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:11:13443
    at n (https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:6:21464)
    at c (https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:6:17635)
    at c (https://munchkin.janw.me/wp-content/plugins/gutenberg/editor/build/index.js?ver=1516900642:11:13401)
    at beginWork (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:133:398)
    at d (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:158:393)
    at f (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:214)
    at g (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:462)
    at t (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:3)
    at x (https://munchkin.janw.me/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247)
```

Anything else I can check?
I am willing to (privately) share the login.

**Comment by youknowriad** [comment]
These issues #5001 #4753 #4437 and #3747 are all related to the same error. Though we're not being able to reproduce properly yet.

I'm closing all these issues and consolidate in #4437
