### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function block_core_navigation_parse_blocks_from_menu_items()

### ISSUE THREAD

**Issue by kebbet** [WordPress/gutenberg#47822]
### Description

`Fatal error: Uncaught Error: Call to undefined function block_core_navigation_parse_blocks_from_menu_items() in /var/www/src/wp-includes/blocks/navigation.php:`

In WP trunk at the moment, since 
```
Block Editor: Updated the WordPress packages to include Gutenberg 15.1.0 changes.

In addition to all the packages being updated to the latest versions, 
this commit also includes some mandatory changes to avoid editor breakage:

 - Update React to to 18.2.0.
 - Add the right stylesheets to support iframed block editors.

Props ntsekouras, mamaduka, flixos90, desrosj, peterwilsoncc.
See #57471.


git-svn-id: https://develop.svn.wordpress.org/trunk@55246 602fd350-edb4-49c9-b593-d223f7449a82
```
Stack trace
```
:  Uncaught Error: Call to undefined function block_core_navigation_parse_blocks_from_menu_items() in /var/www/src/wp-includes/blocks/navigation.php:317
Stack trace:
#0 /var/www/src/wp-includes/blocks/navigation.php(341): block_core_navigation_get_classic_menu_fallback_blocks(Object(WP_Term))
#1 /var/www/src/wp-includes/blocks/navigation.php(460): block_core_navigation_maybe_use_classic_menu_fallback()
#2 /var/www/src/wp-includes/blocks/navigation.php(636): block_core_navigation_get_fallback_blocks()
#3 /var/www/src/wp-includes/class-wp-block.php(258): render_block_core_navigation(Array, '', Object(WP_Block))
#4 /var/www/src/wp-includes/class-wp-block.php(244): WP_Block->render()
#5 /var/www/src/wp-includes/class-wp-block.php(244): WP_Block->render()
#6 /var/www/src/wp-includes/blocks.php(1051): WP_Block->render()
#7 /var/www/src/wp-includes/blocks.php(1089): render_block(Array)
#8 /var/www/src/wp-includes/blocks/template-part.php(146): do_blocks('<!-- wp:group {...')
#9 /var/www/src/wp-includes/class-wp-block.p in /var/www/src/wp-includes/blocks/navigation.php
```

### Step-by-step reproduction instructions

- Use WordPress trunk
- acticate twenty twenty-three
- visit front end.

### Environment info

- WordPress trunk
- No plugins
- Not event Gutenberg pluginn

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
Hi @kebbet, I am working on triaging the 6.2 project board. Now that #47824 has been merged, this issue can be closed, right?

**Comment by kebbet** [comment]
Just to confirm, WP trunk does not display the fatal error from before, great work on this!
