### ISSUE TITLE
`@wordpress/jest-console` no longer suppresses console output with jest-mock 29.4

### ISSUE THREAD

**Issue by anomiex** [WordPress/gutenberg#48042]
### Description

With jest prior to 29.4, use of `@wordpress/jest-console` suppresses the normal output of the `console` functions. Starting with 29.4, this no longer happens.

This is due to a change in the behavior of jest's `mockReset()` method. Formerly `jest.spyOn()` would call the original function only until a `mockReset()` was called, at which point it would stop doing so. Now they've fixed it to have `mockReset()` restore the call-through to the original implementation.

If the output suppression was intended, you might change [the `.mockReset()` call](https://github.com/WordPress/gutenberg/blob/1c087d4369c1ec2c1dee58301da4aba6017210ba/packages/jest-console/src/index.js#L23) to `.mockReset().mockReturnValue()` or `.mockReset().mockImplementation( () => {} )` or something similar to prevent the call-through to the original version.

### Step-by-step reproduction instructions

1. Create this test file:
   ```js
   require( '@wordpress/jest-console' );
   
   it( 'calls console functions', () => {
       console.log( "log!" );
       console.info( "info!" );
       console.warn( "warn!" );
       console.error( "error!" );
   
       expect( console ).toHaveLogged();
       expect( console ).toHaveInformed();
       expect( console ).toHaveWarned();
       expect( console ).toHaveErrored();
   } );
   ```
2. Execute jest.

### Screenshots, screen recording, code snippet

With jest-mock 29.3.1:
```
 PASS  ./test.js
  ✓ calls console functions (2 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.176 s, estimated 1 s
Ran all test suites matching /test.js/i.
```

With jest-mock 29.4.2:
```
  console.log
    log!

      at node_modules/.pnpm/jest-mock@29.4.2/node_modules/jest-mock/build/index.js:386:39

  console.info
    info!

      at node_modules/.pnpm/jest-mock@29.4.2/node_modules/jest-mock/build/index.js:386:39

  console.warn
    warn!

      4 |     console.log( "log!" );
      5 |     console.info( "info!" );
    > 6 |     console.warn( "warn!" );
        |             ^
      7 |     console.error( "error!" );
      8 |
      9 |     expect( console ).toHaveLogged();

      at node_modules/.pnpm/jest-mock@29.4.2/node_modules/jest-mock/build/index.js:386:39
      at Object.warn (test.js:6:13)

  console.error
    error!

       5 |     console.info( "info!" );
       6 |     console.warn( "warn!" );
    >  7 |     console.error( "error!" );
         |             ^
       8 |
       9 |     expect( console ).toHaveLogged();
      10 |     expect( console ).toHaveInformed();

      at node_modules/.pnpm/jest-mock@29.4.2/node_modules/jest-mock/build/index.js:386:39
      at Object.error (test.js:7:13)

 PASS  ./test.js
  ✓ calls console functions (23 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.22 s, estimated 1 s
Ran all test suites matching /test.js/i.
```

### Environment info

- `@wordpress/jest-console` version 6.9.0
- `jest-mock` version 29.3.1 versus 29.4.2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by youknowriad** [comment]
Verified with jest-mock 29.6.2: @wordpress/jest-console suppresses the output of console calls it intercepts again. Closing as fixed.

**Comment by anomiex** [comment]
For the record: I can still reproduce with jest-mock 29.6.2, but it seems fixed in 29.6.3 (presumably due to jestjs/jest#14429). They don't seem to have restored the behavior with v30 either.

**Comment by youknowriad** [comment]
Mmm you're right, looks like I got a more recent version in my tests. What do you think we should do here? Peer dependency with a minimum version or else? Maybe it's ok since it's solved in the latest jest-mock versions?

**Comment by anomiex** [comment]
🤷 Fine with me to leave it how it is.
