### ISSUE TITLE
Error with recent update to Gutenberg - this block has encountered an error and cannot be previewed

### ISSUE THREAD

**Issue by lmpierce2216** [WordPress/gutenberg#49003]
### Description

I cannot edit any site pages. Each time I try to add or edit a block, I receive the error message "this block has encountered an error and cannot be previewed" and can't do anything with the block. I have used troubleshoot mode with my plugins - starting with only Gutenberg active - the problem still existed until I disabled the Gutenberg plugin then I am able to edit pages, add and edit blocks. Everything worked fine yesterday (03-09-2023).

### Step-by-step reproduction instructions

1. Add new page or Select edit page
2. Click to add a block or Select a block to edit
3. Error message comes up instead of the block
![troubleshooting blocks](https://user-images.githubusercontent.com/127562937/224438504-5f9e1b27-865d-4acc-920a-e4e8b525fea4.JPG)

### Environment info

Gutenberg version is 15.3.1
WordPress version is 6.1.1.
Installed theme is Twenty-Sixteen, which I realize is an older one, but it has always worked without issue with the block editing features.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Tropicalista** [comment]
Can you report back the message in console?

**Comment by lmpierce2216** [comment]
This is my first time reporting any errors. I don't know what you mean
"report back the message in console". I ended up here after following the
instructions on the Gutenberg plugin page via WordPress.

**Comment by Tropicalista** [comment]
Press f12 and check on Console tab

**Comment by lmpierce2216** [comment]
Here are the messages from the console:
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/scripts/iframe_form_check.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/scripts/iframe_form_detection.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

**Comment by lmpierce2216** [comment]
Here is a copy and paste from the console tab when I'm on edit a page and receive the error (while Gutenberg plugin is active):

JQMIGRATE: Migrate is installed, version 3.3.2
index.js:77 Declaring non-string block descriptions is deprecated since version 6.2.
i @ index.js:77
index.js:77 `wp.data.select( 'core/editor' ).getBlocks` is deprecated since version 5.3 and will be removed in version 6.2. Please use `wp.data.select( 'core/block-editor' ).getBlocks` instead.
i @ index.js:77
index.js:77 wp.nux is deprecated since version 5.4 and will be removed in version 6.2. Note: wp.components.Guide can be used to show a user guide.
i @ index.js:77
admin-bar-v2.js?ver=12.0-a.1-202310:3 Missing data from PHP (wpNotesArgs).
(anonymous) @ admin-bar-v2.js?ver=12.0-a.1-202310:3
/wp-json/wpcom/v2/site-intent?_locale=user:1          Failed to load resource: the server responded with a status of 404 ()
/wp-json/wpcom/v2/site-intent?_locale=user:1          Failed to load resource: the server responded with a status of 404 ()
8react-dom.min.js?ver=18:1 TypeError: Mo(...).getSupportedStyles is not a function
    at hooks.js:226:7
    at f (index.js:84:29)
    at a (registry.js:123:20)
    at Object.__unstableMarkListeningStores (registry.js:204:30)
    at index.js:127:14
    at p (index.js:94:22)
    at index.js:126:4
    at $e (index.js:154:34)
    at Xe (index.js:243:5)
    at Zr (hooks.js:221:40)
ar @ react-dom.min.js?ver=18:1
3DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/scripts/iframe_form_check.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/scripts/iframe_form_detection.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://widgets.wp.com/wpcom-block-editor/wpcom.editor.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://widgets.wp.com/wpcom-block-editor/default.editor.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/paragraph-block/dist/paragraph-block.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/newspack-blocks/dist/carousel-block-editor.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/wpcom-block-editor-nux/dist/wpcom-block-editor-nux.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/wpcom-documentation-links/dist/wpcom-documentation-links.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/event-countdown-block/dist/event-countdown-block.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/block-inserter-modifications/dist/contextual-tips.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/help-center/dist/help-center.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/jetpack-timeline/dist/jetpack-timeline.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/common/dist/disable-heic-images.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/wpcom-block-description-links/dist/wpcom-block-description-links.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/newspack-blocks/dist/blog-posts-block-editor.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/whats-new/dist/whats-new.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/common/dist/common.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/tags-education/dist/tags-education.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/wpcom-block-editor-nav-sidebar/dist/wpcom-block-editor-nav-sidebar.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/common/dist/data-stores.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://kranderson.family/wp-content/plugins/full-site-editing/starter-page-templates/dist/starter-page-templates.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by talldan** [comment]
@lmpierce2216 Could you use the Copy All Blocks option and paste the content in a comment here?
![Screen Shot 2023-03-14 at 2 11 23 pm](https://user-images.githubusercontent.com/677833/224911679-e4fa6e60-6613-48ba-af74-15bbdc5ab94c.png)

That should help us know which blocks are having issues.

**Comment by lmpierce2216** [comment]
Here's the requested copy all blocks:
```html
<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:jetpack/tiled-gallery /-->

<!-- wp:columns -->
<div class="wp-block-columns"></div>
<!-- /wp:columns -->

<!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:audio /-->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->
```

The issue exists with any block I select. But the issue goes away if I disable the Gutenberg plugin and simply use WordPress. Also I noted today when I activated the Gutenberg plugin to get this copy - when I open the see all blocks side panel only a few of the blocks appear - only the Text and Media blocks. I will paste a screenshot of that here for you as well.

![add a block side panel 1](https://user-images.githubusercontent.com/127562937/225052065-a67e2c28-f18d-4168-8d3f-7052bd7995d6.JPG)
![add a block side panel 2](https://user-images.githubusercontent.com/127562937/225052072-aa5512fd-6e9b-4bf3-8b05-12a874eff874.JPG)

**Comment by lmpierce2216** [comment]
Looks like the first paste of copy all blocks didn't work. I'll try again.
```
<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:jetpack/tiled-gallery /-->

<!-- wp:columns -->
<div class="wp-block-columns"></div>
<!-- /wp:columns -->

<!-- wp:image -->
<figure class="wp-block-image"><img alt=""/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->

<!-- wp:audio /-->

<!-- wp:spacer -->
<div style="height:100px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->
```
And here's a text file in case the paste doesn't work again:
[copy all blocks.docx](https://github.com/WordPress/gutenberg/files/10970501/copy.all.blocks.docx)

**Comment by talldan** [comment]
@lmpierce2216 All good, you just have to use code blocks for the post content, otherwise github tries to display it as HTML.

I've edited your first comment to fix it.

**Comment by yankazimirchick** [comment]
There was such a problem when switching to wp 6.2 version. The problem was with the theme.json file. Deleting the file or fixing it helped.
