### ISSUE TITLE
Issue while loading or creating articles

### ISSUE THREAD

**Issue by Gunlek** [WordPress/gutenberg#5001]
## Issue Overview
Can't edit or create articles using Gunteberg editor because of an error that show up everytime I'm trying

## Steps to Reproduce (for bugs)

1. Go to article list
2. Click "edit article" or "add article" using Gunteberg editor
3.
4.

## Expected Behavior

The Gunteberg editor should appear allowing us to write or continue our work

## Current Behavior

Wordpress is display a message to copy post, copy error or attempt recovery. The "copy error" result is the following:
`TypeError: Cannot read property 'level_1' of undefined
    at http://website_url/wp-content/plugins/gutenberg/editor/build/index.js?ver=1517908162:11:13443
    at n (http://website_url/wp-content/plugins/gutenberg/editor/build/index.js?ver=1517908162:6:21464)
    at c (http://website_url/wp-content/plugins/gutenberg/editor/build/index.js?ver=1517908162:6:17635)
    at c (http://website_url/wp-content/plugins/gutenberg/editor/build/index.js?ver=1517908162:11:13401)
    at beginWork (http://website_url/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:133:398)
    at d (http://website_url/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:158:393)
    at f (http://website_url/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:214)
    at g (http://website_url/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:159:462)
    at t (http://website_url/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:3)
    at x (http://website_url/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247)`

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by twsp** [comment]
I'm having trouble understanding how to recreate this bug.  Could you include some screenshots to help explain exactly what you're doing?

**Comment by youknowriad** [comment]
These issues #5001 #4753 #4437 and #3747 are all related to the same error. Though we're not being able to reproduce properly yet.

I'm closing all these issues and consolidate in #4437
