### ISSUE TITLE
`wp-env install-path` does not work when offline

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#52157]
### Description

When internet is turned off, you'll get an error trying connect to `api.wordpress.org`.

All I wanted was getting the install path.

### Step-by-step reproduction instructions

1. Turn off internet access
2. Run `wp-env install-path`
3. Get error message

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by t-hamano** [comment]
I was able to reproduce the problem and will leave an error log.

```
$ npm run wp-env install-path

> gutenberg@16.1.0 wp-env /home/username/projects/gutenberg
> wp-env "install-path"

✖ getaddrinfo EAI_AGAIN api.wordpress.org
RequestError: getaddrinfo EAI_AGAIN api.wordpress.org
    at ClientRequest.<anonymous> (/home/username/projects/gutenberg/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/home/username/projects/gutenberg/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  code: 'EAI_AGAIN',
  timings: {
    start: 1688210948625,
    socket: 1688210948625,
    lookup: 1688210958635,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1688210958636,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 10010,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 10011
    }
  }
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gutenberg@16.1.0 wp-env: `wp-env "install-path"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gutenberg@16.1.0 wp-env script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2023-07-01T11_29_18_659Z-debug.log
```

**Comment by swissspidy** [comment]
Closing in favor of #53433
