### ISSUE TITLE
Env: cannot pass ZIP URL for core

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#53002]
### Description

According to the readme it should be possible, but I'm getting an error.

Related: #34866

### Step-by-step reproduction instructions

I tried providing `"core": "https://wordpress.org/wordpress-6.3-RC1.zip"` in `.wp-env.json` but getting the following error:

```
✖ fatal: invalid refspec 'https://wordpress.org/wordpress-6.3-RC1.zip'

GitError: fatal: invalid refspec 'https://wordpress.org/wordpress-6.3-RC1.zip'

    at Object.action (/path/to/node_modules/simple-git/dist/cjs/index.js:1300:25)
    at PluginStore.exec (/path/to/node_modules/simple-git/dist/cjs/index.js:1335:29)
    at /path/to/node_modules/simple-git/dist/cjs/index.js:1734:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/path/to/node_modules/simple-git/dist/cjs/index.js:1732:16)
    at GitExecutorChain.<anonymous> (/path/to/node_modules/simple-git/dist/cjs/index.js:1716:44)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/node_modules/simple-git/dist/cjs/index.js:55:24) {
  task: {
    commands: [
      'fetch',
      '--tags',
      'origin',
      'https://wordpress.org/wordpress-6.3-RC1.zip'
    ],
    format: 'utf-8',
    parser: [Function: parseFetchResult]
  }
}
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by swissspidy** [comment]
Never mind, I passed the wrong ZIP URL 🤦
