### ISSUE TITLE
Scripts: Enhance the way entry points are detected in projects consisting of blocks and editor plugins

### ISSUE THREAD

**Issue by mrleemon** [WordPress/gutenberg#55936]
### Description

I regularly use `@wordpress/scripts` for building both blocks and non-block components. Recently, I started working in a new plugin that registers both some blocks and non-block components that add additional panels using the `registerPlugin()` function. This is the structure of my `/src` directory:

```
/src
    /blocks
        /my-first-block
            block.json
            ...
        /my-second-block
            block.json
            ...
        /my-third-block 
            block.json
            ...
    /components
        /my-first-panel
            index.js
        /my-second-panel
            index.js
    index.js
    index.css
    style.css
```

This is the content of the root `index.js` file:

```
import { __ } from '@wordpress/i18n';
import { registerPlugin } from '@wordpress/plugins';
import { calendar } from '@wordpress/icons';

import FirstPanelOptionsPanelComponent from './components/my-first-panel';
import SecondPanelOptionsPanelComponent from './components/my-second-panel';
import './index.scss';
import './style.scss';

registerPlugin('first-panel-options-panel', {
    icon: calendar,
    render: FirstPanelOptionsPanelComponent,
});

registerPlugin('second-panel-options-panel', {
    icon: calendar,
    render: SecondPanelOptionsPanelComponent,
});
  
```

Until now, I can't remember having any problems with the build script in `@wordpress/scripts`: It built both the blocks and the components found in the `/src` directory. But now, for some reason, it just builds the blocks, ignoring the components completely. The thing is that if I remove the `/blocks` directory then the components are built with no issues.

Has anything changed in `@wordpress/scripts` recently?

### Step-by-step reproduction instructions

Create a `/src` directory with blocks and non-block components
Run `npm build`
The script ignores the non-block components

### Environment info

WP 6.3
No Gutenberg plugin
Windows 10
NPM 10.2.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mrleemon** [comment]
If I run `npm build src/index.js` the components are built, but not the blocks. Is there a way to build everything that is found inside the `/src` directory?

**Comment by gziolo** [comment]
> Until now, I can't remember having any problems with the build script in @wordpress/scripts: It built both the blocks and the components found in the /src directory. But now, for some reason, it just builds the blocks, ignoring the components completely. The thing is that if I remove the /blocks directory then the components are built with no issues.
>
> Has anything changed in @wordpress/scripts recently?

Yes, this is the order of how entry points are created for JavaScript files using webpack:

https://github.com/WordPress/gutenberg/blob/e0c80ab4002095f5b1c75ed9ff7f63a180d3f4f4/packages/scripts/utils/config.js#L181-L191

When `npm run build` finds `block.json` files, it reads all script-related entries and uses them to create entry points. `index.js` is only used as an entry point when there are no `block.json` files found. 

That's said. We are open for iteration based on the feedback received as we plan to expand the application of the build tools outside of blocks, but also to make them helpful when building JS plugins and block themes.

**Comment by mrleemon** [comment]
@gziolo Thanks for the explanation. I hope you can add a way to build both blocks and plugins found in the same directory. It would be very useful for those of us coding for clients.

**Comment by mrleemon** [comment]
The issue is still not resolved.
Thanks.

**Comment by gziolo** [comment]
> Until now, I can't remember having any problems with the build script in @wordpress/scripts: It built both the blocks and the components found in the /src directory. But now, for some reason, it just builds the blocks, ignoring the components completely. The thing is that if I remove the /blocks directory then the components are built with no issues.

I was thinking about it again. We added, at some point, automatic detection of the `block.json` files that allows discovering entry points defined with `script`, `editorScript` and `viewScript`. It looks like there is a check that could be avoided:

https://github.com/WordPress/gutenberg/blob/05b78e0ee987fb2591ebbd211c9651834079a347/packages/scripts/utils/config.js#L300-L302

If we remove that condition, we could combine the entry points detected for blocks with `index.js` to satisfy more advanced configurations in the projects that also ship JavaScript code not directly related to blocks.

**Comment by gziolo** [comment]
@bacoords and @aurooba, I remember you discussing in the [viewSource podcast](https://viewsource.fm) the need to improve `wp-scripts build` to work not only with blocks. What else could we improve the developer experience?

**Comment by bacoords** [comment]
@gziolo Thanks for the tag! So from what I recall, our issues mostly have to do with multiple entry points. 

Basically every entry point is treated as a block, meaning if you had a theme and wanted to also use `wp-scripts` for your theme stylesheet, or maybe a global frontend JavaScript file (in addition to using it for your custom blocks), it would always generate the asset.php file and rename everything to index or style-index or what have you. Basically, could you define an entry point that doesn't rename the file, doesn't generate an asset file, etc.

I believe that was the main issue, but will let @aurooba add or correct me where I'm wrong.

**Comment by bacoords** [comment]
I wanted to add another issue (or need for documentation) that seems to be related to entry points.

When building a block and pulling in external CSS dependencies or scss partials into block stylesheets:

- If you @import some local `.scss` partials into `src/style.scss`, they'll will be loaded (properly, I believe) into the `build/style-index.css` file (the frontend and editor CSS file).
- If you @import a CSS file from a dependency into `src/style.scss`, the result will be imported into `build/index.css` (the editor-only CSS file). 
- If you @import a local `.scss` partial that _then @imports a CSS file from a dependency_ into `src/style.scss`, your code goes to `build/style-index.css` and the module code goes to `build/index.css`.

Meaning the only way to import CSS from a dependency into a frontend stylesheet for a block is to import it in your `src/view.js` file, which will then result in a new `build/view.css` file you can add to your `block.json` file.

**Comment by jdamner** [comment]
You can have multiple entry points using `webpack.config.js` at the root of your project with something like: 
```js
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

module.exports = {
	...defaultConfig,
	entry: {
		...defaultConfig.entry(),
		index: './src/index.js',
	},
};
```

This would build all the usual build tools for `blocks` (ie anything in `/src/blocks/`) and would also compile the `index.js` file out to `build/index.js`. I do think it would be a sensible default for the standard webpack config used in WP-Scripts to look for `index.js|ts` as well also everything inside `/src/blocks` instead of having it as a fallback, but not sure on backwards compatibility for making that sort of change.

**Comment by mrleemon** [comment]
I added your `webpack.config.js` file to my project and now the build script builds both blocks and non-blocks.
I hope it's added to the standard webpack config used in WP-Scripts in a near future.
Thanks, @jdamner!

**Comment by xsonic** [comment]
@jdamner, this works great, thank you. Do you know if this is compatible with HMR using `--hot`? I get an error from the additional JS file:

    Uncaught TypeError: Cannot read properties of undefined (reading 'injectIntoGlobalHook')

**Comment by jdamner** [comment]
@xsonic I'm not sure, I don't use `--hot`. But it's only providing webpack with additional entry-points, so it's not likely to cause any issues. I'm assuming you have hot-reloading sets as per the docs here: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-scripts/#start

> `--hot` – enables “Fast Refresh”. The page will automatically reload if you make changes to the code. For now, it requires that WordPress has the [SCRIPT_DEBUG](https://wordpress.org/documentation/article/debugging-in-wordpress/#script_debug) flag enabled and the [Gutenberg](https://wordpress.org/plugins/gutenberg/) plugin installed.

**Comment by james0r** [comment]
> ```js
> const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );
> ```

Trying this out but getting 

```
webpack-cli] Failed to load '/Users/jamesauble/Projects/diesel/wp-content/themes/fictional-clean-blocks/webpack.config.js' config
[webpack-cli] TypeError: defaultConfig.entry is not a function
    at Object.<anonymous> (/Users/jamesauble/Projects/diesel/wp-content/themes/fictional-clean-blocks/webpack.config.js:14:22)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
```

webpack.config.js
```js
// WordPress webpack config.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Utilities.
const path = require('path');

// Add any new entry points by extending the webpack config.
module.exports = {
  ...defaultConfig,
  entry: {
    ...defaultConfig.entry(),
    'theme-js': path.resolve(process.cwd(), 'src/js', 'index.js'),
    'theme-css': path.resolve(process.cwd(), 'src/css', 'style.scss'),
  },
};
```

**Comment by sirreal** [comment]
@james0r this line is calling `defaultConfig.entry()` like a function:

```
    ...defaultConfig.entry(),
```

Will you try replacing it with this:

```
    ...defaultConfig.entry,
```

**Comment by james0r** [comment]
> @james0r this line is calling `defaultConfig.entry()` like a function:
> 
> ```
>     ...defaultConfig.entry(),
> ```
> 
> Will you try replacing it with this:
> 
> ```
>     ...defaultConfig.entry,
> ```

When using defaultConfig.entry I get 

```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property '1'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, experiments?, extends?, externals?, externalsPresets?, externalsType?, ignoreWarnings?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, snapshot?, stats?, target?, watch?, watchOptions? }
   -> Options object as provided by the user.
   For typos: please correct them.
   For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           1: …
         }
       })
```

**Comment by t-hamano** [comment]
@james0r What version of `@wordpress/scripts`? It may be related to [this discussion](https://github.com/WordPress/gutenberg/discussions/44010#discussioncomment-9284674).

**Comment by wasek23** [comment]
> > @james0r this line is calling `defaultConfig.entry()` like a function:
> > ```
> >     ...defaultConfig.entry(),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Will you try replacing it with this:
> > ```
> >     ...defaultConfig.entry,
> > ```
> 
> When using defaultConfig.entry I get
> 
> ```
> [webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
>  - configuration has an unknown property '1'. These properties are valid:
>    object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, experiments?, extends?, externals?, externalsPresets?, externalsType?, ignoreWarnings?, infrastructureLogging?, loader?, mode?, module?, name?, node?, optimization?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, snapshot?, stats?, target?, watch?, watchOptions? }
>    -> Options object as provided by the user.
>    For typos: please correct them.
>    For loader options: webpack >= v2.0.0 no longer allows custom properties in configuration.
>      Loaders should be updated to allow passing options via loader options in module.rules.
>      Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
>      plugins: [
>        new webpack.LoaderOptionsPlugin({
>          // test: /\.xxx$/, // may apply this only for some modules
>          options: {
>            1: …
>          }
>        })
> ```

I am fetching the same error with this code

```
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

module.exports = {
    ...defaultConfig
};
```


The version I am using is: 27.9.0

**Comment by james0r** [comment]
> @james0r What version of `@wordpress/scripts`? It may be related to [this discussion](https://github.com/WordPress/gutenberg/discussions/44010#discussioncomment-9284674).

I just figured out that I'm only having the `defaultConfig.entry is not a function` issue when running `wp-scripts build` with the `--experimental-modules` flag with version 27.9.0. If I remove the flag it works as expected.

I also found this starter theme which is a great resource https://github.com/bacoords/block-theme

**Comment by ghostintranslation** [comment]
I ran into the same problem. 

With the added flag the default config becomes an array.

You can make the custom Webpack config working with the following:

```
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

module.exports = [
	{
		...defaultConfig[0],
		entry: {
			...defaultConfig[0].entry(),
			// admin: './src/admin/index.js',
		},
	},
	{
		...defaultConfig[1],
	},
];
```

**Comment by daotw** [comment]
@james0r [troychaplin](https://github.com/troychaplin) published a multi-block, with additional non-block scripts, in one plugin solution: [https://github.com/wptrainingteam/building-multi-block-plugin/tree/DontCombineBlockScripts](https://github.com/wptrainingteam/building-multi-block-plugin/tree/DontCombineBlockScripts). Not tested with `--experimental-modules` yet but it's on to-do list.

**Comment by ghostintranslation** [comment]
@daotw I just tested and that repo you shared does not fix the issue of the wrong Webpack config arising when using the `--experimental-modules` flag.
I also tested applying the change I mention just above to the `webpack.config.js` file and it then works.

**Comment by aaronware** [comment]
@daotw and @ghostintranslation you can also use the following. Below is an example of a block I am creating using the interactivity api along with an "admin" slot fill for a panel on multiple post types

```
// Check if the --experimental-modules flag is set.
const { getAsBooleanFromENV } = require( '@wordpress/scripts/utils' );

const hasExperimentalModulesFlag = getAsBooleanFromENV( 'WP_EXPERIMENTAL_MODULES' );

let scriptConfig, moduleConfig;

if ( hasExperimentalModulesFlag ) {
  [ scriptConfig, moduleConfig ] = require( '@wordpress/scripts/config/webpack.config' );
} else {
  scriptConfig = require( '@wordpress/scripts/config/webpack.config' );
}
```

Then from there can use default define or expand the config

```
module.exports = {
  ...scriptConfig,
  entry: {
    ...scriptConfig.entry(),
    admin: path.resolve(__dirname, 'src/admin/index.js')
  },
  plugins: [
    new MiniCssExtractPlugin(),
    new DependencyExtractionWebpackPlugin(),
    new RemoveEmptyScriptsPlugin()
  ],
};
```

**Comment by gziolo** [comment]
PR with the required changes to improve handling for projects containing editor plugins or theme styles is ready for review:
- https://github.com/WordPress/gutenberg/pull/66466

**Comment by theaminulai** [comment]
**Adding the experimental module has this issue with webpack.config:**
```
{
    "scripts": {
        ...
        "build": "wp-scripts build --experimental-modules",
        "start": "wp-scripts start --experimental-modules"
    }
```



```
[webpack-cli] Failed to load 'D:\wampserver\www\wp-plugin\exoole\wp-content\plugins\exoole\webpack.config.js' config
[webpack-cli] TypeError: defaultConfig.plugins is not iterable
    at Object.<anonymous> (D:\wampserver\www\wp-plugin\exoole\wp-content\plugins\exoole\webpack.config.js:19:21)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at WebpackCLI.tryRequireThenImport (D:\wampserver\www\wp-plugin\exoole\wp-content\plugins\exoole\node_modules\webpack-cli\lib\webpack-cli.js:223:30)
    at loadConfigByPath (D:\wampserver\www\wp-plugin\exoole\wp-content\plugins\exoole\node_modules\webpack-cli\lib\webpack-cli.js:1406:38)
    at WebpackCLI.loadConfig (D:\wampserver\www\wp-plugin\exoole\wp-content\plugins\exoole\node_modules\webpack-cli\lib\webpack-cli.js:1515:44)
```

**Comment by kasparsd** [comment]
I've created this sample repository to demo all of the issues described here: https://github.com/kasparsd/wp-scripts-build-issues

1. Default `wp-scripts build` doesn't pick up any `src/*.js` (including `src/index.js`) if there is at least one `src/**/block.json` present.

2. Specifying custom entry points breaks the `**/block.json` scanner and building of blocks.


The first one happens because of the early return during `getWebpackEntryPoints()`:

https://github.com/WordPress/gutenberg/blob/132e8c3220cab53e528af5b0e32f204299de0c5a/packages/scripts/utils/config.js#L348-L350

And the second one because of this early return when any custom entry file is specified:

https://github.com/WordPress/gutenberg/blob/132e8c3220cab53e528af5b0e32f204299de0c5a/packages/scripts/utils/config.js#L239-L243

For anyone looking for a solution, you can use a custom `webpack.config.js` to (1) inherit the `blocks/*/block.json` resolver output and (2) combine it with any number of JS files as entry points:

```js
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

module.exports = {
	...defaultConfig,
	entry: {
		...defaultConfig.entry(), // Default WP entry points for blocks.
		index: './src/index.js',
		custom: './src/custom.js',
	},
};
```

which is picked up automatically when running `wp-scripts build`. It assumes that the default entry returned by `getWebpackEntryPoints()` is a function (reason for `defaultConfig.entry()` function call) which you might want to re-check in case it is changed to something else.

## Eventual Goal

I would recommend we consider supporting the following input eventually:

	wp-scripts build 'js/*.js' 'frontend/**/*.js' --blocks-source=blocks --blocks-source=other-blocks --output-path=build

which takes the following entry files:

- `js/*.js` (without recursing into subdirectories)
- `frontend/**/*.js` (recursing into subdirectories)
- `blocks/**/block.json` linked JS files
- `other-blocks/**/block.json` linked JS files

and ejects them under:

- build/js/*.js
- build/frontend/**/*.js
- build/blocks/**/block.js
- build/other-blocks/**/block.js

**Comment by ethanscorey** [comment]
The solution suggested by @kasparsd works great _unless_ you try to include the new `--experimental-modules` flag in your build script. If you include that flag, `defaultConfig` is an array of two different config objects: `scriptConfig` and `moduleConfig`.

To address this, just change it to:

```javascript
const [
	scriptConfig,
	moduleConfig,
] = require( '@wordpress/scripts/config/webpack.config' );

module.exports = [
	{
		...scriptConfig,
		entry: {
			...scriptConfig.entry(),
			index: './src/index.js',
                        custom: './src/custom.js',
		},
	},
	moduleConfig,
];
```

**Comment by youknowriad** [comment]
We're moving away from @wordpress/scripts current build behavior towards `@wordpress/build`, a more opinionated approach. See #72032 for more details. 

If you need a very customized setup, don't rely on Core tools and use your own tooling. There are multiple valid choices in the community to pick from.
