### ISSUE TITLE
@wordpress/create-block@latest does not work inside npm/pnpm workspaces.

### ISSUE THREAD

**Issue by ivanjeremic** [WordPress/gutenberg#56059]
### Description

The create block package/install script does not work inside npm workspaces. `npx @wordpress/create-block@latest` does not work if I have an npm workspace and want to install it under `/packages`

### Step-by-step reproduction instructions

1. create an npm workspace with a `/packages` folder
2. Run `@wordpress/create-block@latest` inside `/packages`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by gziolo** [comment]
I couldn't reproduce with a test repository that uses npm workspaces:

<img width="1758" alt="Screenshot 2023-11-24 at 13 07 01" src="https://github.com/WordPress/gutenberg/assets/699132/fad0db65-81d4-4085-92de-1b3dff291bf3">


<img width="909" alt="Screenshot 2023-11-24 at 12 59 31" src="https://github.com/WordPress/gutenberg/assets/699132/1ba21902-30cf-417c-bad7-50467b3b2128">

Can you provide more details or a sample project that could help here?

**Comment by ivanjeremic** [comment]
I am on WSL2 and tried pnpm & npm both same error.

**Comment by brettsmason** [comment]
I recently experienced the same issue. Here is an example repository along with instructions to recreate this: https://github.com/brettsmason/gutenberg-issue-56059

Also tagging @ryanwelcher as we briefly discussed on Slack.

**Comment by t-hamano** [comment]
I'd like to confirm if this issue is still valid.

@brettsmason Do you know if #53781 solved this issue?

**Comment by brettsmason** [comment]
Hi @t-hamano unfortunately no it didn't directly fix the issue. That flag specifies what directory the block should be put in, but it doesn't put a directory with the blocks slug within in. So yes this issue still needs addressing. I got around it via a script that moves the block after scaffolding, but it would be great to fix the underlying issue.

**Comment by t-hamano** [comment]
The issues reported by @ivanjeremic and @brettsmason  seem to me to be different: @ivanjeremic seems to be running into some kind of error when running create-block in a subfolder within an npm workspace, whereas @brettsmason seems to be requesting more flexibility in the directory to scaffold.

Is my understanding correct?

**Comment by brettsmason** [comment]
@t-hamano its the same issue. I've had to do a workaround here https://github.com/eighteen73/nebula/blob/main/web/app/mu-plugins/nebula-blocks/scripts/create-block.js

Otherwise if I try and run create block from that directory it puts it in the root of the folder, not where specified.

The repo I set up above demonstrates the issue but if you need durther details let me know.

**Comment by SirLouen** [comment]
Failing for me also, not sure if this could help.

### Steps to reproduce (using WSL2 + node 20)

1. Create a folder called `packages` and went into it
2. Initliazed npm `npm init -y`
3. `package.json`

```json
{
  "name": "packages",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "type": "commonjs",
  "workspaces": ["packages/*"]
}
```

4. `npx @wordpress/create-block@latest`

```
Formatting JavaScript files.
/home/mcamargo/.npm/_npx/9444c7de6ab42aae/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 127: npm run format
sh: 1: wp-scripts: not found
npm error Lifecycle script `format` failed with error:
npm error code 127
npm error path /home/mcamargo/src/wordpress/test-56059/packages/example-dynamic
npm error workspace example-dynamic@0.1.0
npm error location /home/mcamargo/src/wordpress/test-56059/packages/example-dynamic
npm error command failed
npm error command sh -c wp-scripts format

> example-dynamic@0.1.0 format
> wp-scripts format

    at makeError (/home/mcamargo/.npm/_npx/9444c7de6ab42aae/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/mcamargo/.npm/_npx/9444c7de6ab42aae/node_modules/execa/index.js:114:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/home/mcamargo/.npm/_npx/9444c7de6ab42aae/node_modules/@wordpress/create-block/lib/init-wp-scripts.js:22:2)
    at async module.exports (/home/mcamargo/.npm/_npx/9444c7de6ab42aae/node_modules/@wordpress/create-block/lib/scaffold.js:193:4)
    at async Command.<anonymous> (/home/mcamargo/.npm/_npx/9444c7de6ab42aae/node_modules/@wordpress/create-block/lib/index.js:193:6) {
  shortMessage: 'Command failed with exit code 127: npm run format',
  command: 'npm run format',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\n> example-dynamic@0.1.0 format\n> wp-scripts format\n',
  stderr: 'sh: 1: wp-scripts: not found\n' +
    'npm error Lifecycle script `format` failed with error:\n' +
    'npm error code 127\n' +
    'npm error path /home/mcamargo/src/wordpress/test-56059/packages/example-dynamic\n' +
    'npm error workspace example-dynamic@0.1.0\n' +
    'npm error location /home/mcamargo/src/wordpress/test-56059/packages/example-dynamic\n' +
    'npm error command failed\n' +
    'npm error command sh -c wp-scripts format',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v20.19.5
```

If I change the folder from `packages` to `whatever` it works again.
