### ISSUE TITLE
Closing Categories box errors

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#5637]
![error](https://user-images.githubusercontent.com/1204802/37463676-4a75d0b6-2856-11e8-8253-5fd93fa61d61.gif)

This is the error:

```
TypeError: this.fetchRequest.abort is not a function
    at HierarchicalTermSelector.componentWillUnmount (http://gutenberg/wp-content/plugins/gutenberg/editor/build/index.js?ver=1521116540:28416:23)
    at d (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:143:43)
    at g (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:144:322)
    at commitDeletion (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:147:391)
    at b (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:155:334)
    at t (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:167:47)
    at x (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:166:247)
    at batchedUpdates (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:169:173)
    at cc (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:26:56)
    at jc (http://gutenberg/wp-content/plugins/gutenberg/vendor/react-dom.min.3583f8be.js:35:5)
```

This is running using WP Docker on my localhost. I can't reproduce in 2.4.

**Comment by jorgefilipecosta** [comment]
I was able to reproduce this, I'm debugging it.

**Comment by aduth** [comment]
"Attempt Recovery" should serve be a valid workaround in the meantime.
