### ISSUE TITLE
"Cannot read properties of undefined (reading 'map')" JS error in the Gutenberg Storybook for Inserter (Library With Patterns and Reusable Blocks).

### ISSUE THREAD

**Issue by ninio** [WordPress/gutenberg#56975]
### Description

In the Gutenberg storybook, in the Inserter section for "Library With Patterns and Reusable Blocks", the preview shows an error "Cannot read properties of undefined (reading 'map')"

### Step-by-step reproduction instructions

1. Open https://wordpress.github.io/gutenberg/?path=/story/blockeditor-inserter--library-with-patterns-and-reusable-blocks
2. The preview shows the following error:
```
Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at https://wordpress.github.io/gutenberg/1159.e669f509.iframe.bundle.js:1:78621
    at Array.map (<anonymous>)
    at getUserPatterns (https://wordpress.github.io/gutenberg/1159.e669f509.iframe.bundle.js:1:78457)
    at https://wordpress.github.io/gutenberg/1159.e669f509.iframe.bundle.js:1:79547
    at callSelector (https://wordpress.github.io/gutenberg/1572.67ac5f91.iframe.bundle.js:2:14891)
    at https://wordpress.github.io/gutenberg/1159.e669f509.iframe.bundle.js:1:80493
    at callSelector (https://wordpress.github.io/gutenberg/1572.67ac5f91.iframe.bundle.js:2:14891)
    at boundSelector (https://wordpress.github.io/gutenberg/1200.f36aa8fa.iframe.bundle.js:1:135464)
    at https://wordpress.github.io/gutenberg/components-inserter-stories-index-story.62d78d44.iframe.bundle.js:1:298280
    at https://wordpress.github.io/gutenberg/1200.f36aa8fa.iframe.bundle.js:1:116060
```

### Screenshots, screen recording, code snippet

![image](https://github.com/WordPress/gutenberg/assets/1941633/e7697b95-1c34-45ae-875f-5e66690b2f44)

### Environment info

Windows 11
Chrome 119.0.6045.200 (64-bit)

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ninio** [comment]
The same error happens in Storybook > Inserter > Quick Inserter, when you press the "+" button
![image](https://github.com/WordPress/gutenberg/assets/1941633/65f2cf56-1538-492c-8978-6356ad84a999)

Result after press:
![image](https://github.com/WordPress/gutenberg/assets/1941633/4a8826c6-7aaf-4ec3-aa62-bd207b59ce51)

**Comment by Nantris** [comment]
Is there really no solution for this...?

**Comment by Mamaduka** [comment]
I can no longer reproduce the reported error.
