### ISSUE TITLE
createInterpolateElement: Add error handling in case unmatched tags are included

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#60843]
### Description

The problem was discovered in #60654

If a string containing invalid tags is passed to the `createInterpolateElement()` function, a critical error like the one below will occur.

```
create-interpolate-element.js:230 Uncaught TypeError: Cannot read properties of undefined (reading 'prevOffset')
    at proceed (create-interpolate-element.js:230:14)
    at createInterpolateElement (create-interpolate-element.js:129:12)
    at CodeEdit (edit.js:20:26)
    at renderWithHooks (react-dom.js?ver=18:16315:20)
    at mountIndeterminateComponent (react-dom.js?ver=18:20084:15)
    at beginWork (react-dom.js?ver=18:21597:18)
    at HTMLUnknownElement.callCallback (react-dom.js?ver=18:4151:16)
    at Object.invokeGuardedCallbackDev (react-dom.js?ver=18:4200:18)
    at invokeGuardedCallback (react-dom.js?ver=18:4264:33)
    at beginWork$1 (react-dom.js?ver=18:27461:9)
```

This function will most likely be passed a localized string via the `__()` function. In other words, even if the tags included in the original string are correct, invalid tags may be accidentally mixed in when translated into a specific language.

I think it would be better to prevent this critical error and display a nice error message.

### Step-by-step reproduction instructions

- Add the following code inside a component somewhere.
- Confirm that a critical error occurs when the component is rendered.

```javascript
createInterpolateElement( 'Hello </code>World</code>', {
	code: <code />,
} );
```

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by marincarroll** [comment]
Would something like this work? This is my first attempt at contributing so hope I did it correctly – it seems like we may also need to add a new test for this. https://github.com/WordPress/gutenberg/pull/65294

**Comment by SinghCod3r** [comment]
@gziolo , i want to work on this please assign this to me.

**Comment by SinghCod3r** [comment]
@gziolo , Can you please review my work ?

**Comment by gziolo** [comment]
> @gziolo , Can you please review my work ?

I have limited bandwidth these days. @Mamaduka or @t-hamano, do you know who could help with this one?
