### ISSUE TITLE
The editor has encountered an unexpected error.

### ISSUE THREAD

**Issue by FutureMedia** [WordPress/gutenberg#6123]
## Issue Overview
After updating to v. 2.6.0 attempting to edit a post edited with previous version of the plugin presents a modal stating "The editor has encountered an unexpected error." with 3 buttons "Attempt Recovery", "Copy Post Text", "Copy Error". None of these seem to work (see screen capture 1).
Trying to add a new post also seems not to work except for the title entry (see screen capture 2).  The browser console reports a number of javascript errors in the index.js on lines 13.363
`TypeError: Object(F.hasFilter) is not a function. (In 'Object(F.hasFilter)("blocks.getSaveContent.extraProps")', 'Object(F.hasFilter)' is an instance of Object)`
and 13510
`Block validation: Block validation failed because an error occurred while generating block content:
TypeError: Object(F.hasFilter) is not a function. (In 'Object(F.hasFilter)("blocks.getSaveContent.extraProps")', 'Object(F.hasFilter)' is an instance of Object)`

## Possible Solution

The plugin seems to work partially when the Gutenberg Tools plugin is installed.

## Screenshots / Video

![screen shot 2018-04-11 at 20 50 58](https://user-images.githubusercontent.com/449477/38634794-3af812f8-3dcc-11e8-979d-bec0917dd125.png)
![screen shot 2018-04-11 at 20 51 22](https://user-images.githubusercontent.com/449477/38634793-3ac6b19a-3dcc-11e8-9d10-561d2dc0aa38.png)

**Comment by aduth** [comment]
Can you click "Copy Error" (which copies a complete stack trace to your clipboard) and paste the result here?

**Comment by FutureMedia** [comment]
[Error] Block validation: Block validation failed because an error occurred while generating block content:

TypeError: Object(F.hasFilter) is not a function. (In 'Object(F.hasFilter)("blocks.getSaveContent.extraProps")', 'Object(F.hasFilter)' is an instance of Object)
	un (index.js:18:98190)
	vn (index.js:18:103331)
	(anonymous function) (index.js:18:103755)
	reduce
	SETUP_EDITOR (index.js:17:171875)
	(anonymous function) (index.js:12:100212)
	t (index.js:17:176858)
	constructClassInstance (react-dom.b69cca96.js:7193)
	updateClassComponent (react-dom.b69cca96.js:8700)
	performUnitOfWork (react-dom.b69cca96.js:12154)
	workLoop (react-dom.b69cca96.js:12177)
	renderRoot (react-dom.b69cca96.js:12208)
	performWorkOnRoot (react-dom.b69cca96.js:12764)
	performWork (react-dom.b69cca96.js:12685)
	performSyncWork (react-dom.b69cca96.js:12662)
	requestWork (react-dom.b69cca96.js:12562)
	scheduleWorkImpl (react-dom.b69cca96.js:12437)
	scheduleRootUpdate (react-dom.b69cca96.js:13025)
	render (react-dom.b69cca96.js:16504)
	(anonymous function) (react-dom.b69cca96.js:16923)
	legacyRenderSubtreeIntoContainer (react-dom.b69cca96.js:16919)
	Qt (index.js:12:95671)
	(anonymous function) (post.php:2237)
	(anonymous function) (jquery.js:2:28774)
	i (jquery.js:2:27455)
	add (jquery.js:2:27750)
	(anonymous function) (jquery.js:2:28746)
	each (jquery.js:2:2886)
	(anonymous function) (jquery.js:2:28691)
	Deferred (jquery-migrate.js:744)
	then (jquery.js:2:28672)
	(anonymous function) (post.php:2235:319)
	Global Code (post.php:2238)

[Error] The above error occurred in the <t> component:
    in t (created by WithFilters(t))
    in WithFilters(t) (created by i)
    in i (created by WithDispatch(i))
    in WithDispatch(i) (created by WithSelect(WithDispatch(i)))
    in WithSelect(WithDispatch(i)) (created by t)
    in div (created by t)
    in t (created by Connect(t))
    in Connect(t) (created by WithSelect(Connect(t)))
    in WithSelect(Connect(t)) (created by os)
    in os
    in div (created by t)
    in t (created by n)
    in n (created by WithDispatch(n))
    in WithDispatch(n) (created by WithSelect(WithDispatch(n)))
    in WithSelect(WithDispatch(n))
    in div (created by t)
    in div (created by t)
    in t (created by Connect(t))
    in Connect(t)
    in div (created by t)
    in t (created by WithDispatch(t))
    in WithDispatch(t) (created by WithSelect(WithDispatch(t)))
    in WithSelect(WithDispatch(t))
    in Unknown (created by WithViewportMatch(Component))
    in WithViewportMatch(Component) (created by WithSelect(WithViewportMatch(Component)))
    in WithSelect(WithViewportMatch(Component))
    in div
    in div
    in Unknown (created by WithViewportMatch(Component))
    in WithViewportMatch(Component) (created by n)
    in div (created by n)
    in n (created by WithDispatch(n))
    in WithDispatch(n) (created by WithSelect(WithDispatch(n)))
    in WithSelect(WithDispatch(n))
    in t
    in r (created by t)
    in t (created by t)
    in t (created by t)
    in t (created by t)
    in t (created by t)
    in t

React will try to recreate this component tree from scratch using the error boundary you provided, t.
	logCapturedError (react-dom.b69cca96.js:10003)
	logError (react-dom.b69cca96.js:10042)
	commitErrorLogging (react-dom.b69cca96.js:10240)
	commitAllLifeCycles (react-dom.b69cca96.js:11799)
	callCallback (react-dom.b69cca96.js:144)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.b69cca96.js:182)
	invokeGuardedCallback (react-dom.b69cca96.js:231)
	commitRoot (react-dom.b69cca96.js:11934)
	completeRoot (react-dom.b69cca96.js:12817)
	performWorkOnRoot (react-dom.b69cca96.js:12767)
	performWork (react-dom.b69cca96.js:12685)
	performSyncWork (react-dom.b69cca96.js:12662)
	requestWork (react-dom.b69cca96.js:12562)
	scheduleWorkImpl (react-dom.b69cca96.js:12437)
	scheduleRootUpdate (react-dom.b69cca96.js:13025)
	render (react-dom.b69cca96.js:16504)
	(anonymous function) (react-dom.b69cca96.js:16923)
	legacyRenderSubtreeIntoContainer (react-dom.b69cca96.js:16919)
	Qt (index.js:12:95671)
	(anonymous function) (post.php:2237)
	(anonymous function) (jquery.js:2:28774)
	i (jquery.js:2:27455)
	add (jquery.js:2:27750)
	(anonymous function) (jquery.js:2:28746)
	each (jquery.js:2:2886)
	(anonymous function) (jquery.js:2:28691)
	Deferred (jquery-migrate.js:744)
	then (jquery.js:2:28672)
	(anonymous function) (post.php:2235:319)
	Global Code (post.php:2238)

**Comment by aduth** [comment]
Hi @FutureMedia , I'd be curious to know how you resolved the plugin incompatibility? Was it an outdated version? Or did you just disable the plugin? I'm not familiar with what ACF might be doing, but ideally we could help avoid this being a problem for other users of ACF.

**Comment by rchipka** [comment]
This is caused by ACF overwriting `window.wp.hooks` object, causing `wp.hooks.hasFilter` to be undefined.

A workaround is to replace all occurrences of `wp.hooks` with `wp.acf_hooks` within the file `/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js`

**Comment by FutureMedia** [comment]
Thanks Robbie.

**Comment by rajkumargaur91** [comment]
TypeError: Cannot read property 'getCollectionByRoute' of undefined
    at t.value (/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:145344)
    at t.value (/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:144551)
    at jc (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:123)
    at gc (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
    at vb (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at wg (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
    at Ze (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)

**Comment by arekkko** [comment]
I was the same error after update Gutenberg to 3.7.0

**Comment by endurain** [comment]
> This is because ACF overwrites the `window.wp.hooks` object, causing `wp.hooks.hasFilter` to be undefined.
> 
> A workaround is to replace all occurrences of `wp.hooks` with `wp.acf_hooks` within the file `/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js`



> This is because ACF overwrites the `window.wp.hooks` object, causing `wp.hooks.hasFilter` to be undefined.
> 
> A workaround is to replace all occurrences of `wp.hooks` with `wp.acf_hooks` within the file `/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js`

This fixed the issue for me. Thanks!
