### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by TuB-Klub** [WordPress/gutenberg#6174]
Since the last update (2.6) the Gutenberg Editor doesn't work at all.
Wordpress: 4.9.5

**This is our error:**

TypeError: Object(...) is not a function
    at qt (https://trommel-bass.de/wp-content/plugins/gutenberg/blocks/build/index.js?ver=1523555756:18:94467)
    at t.value (https://trommel-bass.de/wp-content/plugins/gutenberg/editor/build/index.js?ver=1523555756:17:137074)
    at m (https://trommel-bass.de/wp-content/plugins/gutenberg/vendor/react-dom.min.b75d8b30.js:129:215)
    at beginWork (https://trommel-bass.de/wp-content/plugins/gutenberg/vendor/react-dom.min.b75d8b30.js:136:144)
    at e (https://trommel-bass.de/wp-content/plugins/gutenberg/vendor/react-dom.min.b75d8b30.js:168:253)
    at f (https://trommel-bass.de/wp-content/plugins/gutenberg/vendor/react-dom.min.b75d8b30.js:169:23)
    at y (https://trommel-bass.de/wp-content/plugins/gutenberg/vendor/react-dom.min.b75d8b30.js:174:431)
    at q (https://trommel-bass.de/wp-content/plugins/gutenberg/vendor/react-dom.min.b75d8b30.js:173:480)
    at x (https://trommel-bass.de/wp-content/plugins/gutenberg/vendor/react-dom.min.b75d8b30.js:173:324)
    at G (https://trommel-bass.de/wp-content/plugins/gutenberg/vendor/react-dom.min.b75d8b30.js:172:209)

Nice Editor!
Hope it will be fixed soon.
JL

**Comment by aduth** [comment]
Can you share what other plugins you have active while using Gutenberg? There've been a couple issues related to Advanced Custom Fields (ACF), so wondering if it's the same.

**Comment by aduth** [comment]
Alternatively, as reported in #6123, it may be resolved in the latest version of the plugin.

**Comment by rchipka** [comment]
@CreativeDive This is caused by ACF overwriting `window.wp.hooks` object, causing `wp.hooks.hasFilter` to be undefined.

A workaround is to replace all occurrences of `wp.hooks` with `wp.acf_hooks` within the file `/plugins/advanced-custom-fields-pro/assets/js/acf-input.min.js`

**Comment by TuB-Klub** [comment]
Hey, 
thanks for the help! Because of the plugin Advanced Custom Fields PRO, the Gutenberg editor doesn't work!! I have now simply deactivated the ACF.
