### ISSUE TITLE
jest-console throwing errors in conjunction with jest.restoreAllMocks()

### ISSUE THREAD

**Issue by jamesmehorter** [WordPress/gutenberg#61971]
### Description

With `jest-console` in place, if you also rely on `jest.restoreAllMocks()`, `jest-console` throws errors like below:

```
TypeError: Cannot read properties of undefined (reading 'calls')
    at calls (/Users/jmehorter/Work/VVV/www/site-com/public_html/wp-content/plugins/a-plugin/assets/node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/matchers.js:32:25)
    at Object.createSpyInfo (/Users/jmehorter/Work/VVV/www/site-com/public_html/wp-content/plugins/a-plugin/assets/node_modules/@wordpress/jest-console/build/@wordpress/jest-console/src/matchers.js:66:19)
    at __EXTERNAL_MATCHER_TRAP__ (/Users/jmehorter/Work/VVV/www/site-com/public_html/wp-content/plugins/a-plugin/assets/node_modules/expect/build/index.js:325:30)
    at Object.throwingMatcher [as toHaveErroredWith] (/Users/jmehorter/Work/VVV/www/site-com/public_html/wp-content/plugins/a-plugin/assets/node_modules/expect/build/index.js:326:15)
    at Object.toHaveErroredWith (/Users/jmehorter/Work/VVV/www/site-com/public_html/wp-content/plugins/a-plugin/assets/src/js/__tests__/a-test.spec.ts:140:22)

    ...
```

### Step-by-step reproduction instructions

1. Create a file which calls `console.log()`
2. Create a test which triggers the above, _in multiple tests_
3. Utilize `jest.restoreAllMocks()`
4. Run tests and observe that tests fail with `Cannot read properties of undefined (reading 'calls')`

### Screenshots, screen recording, code snippet

<img width="1722" alt="Screen Shot 2024-05-24 at 9 09 52 PM" src="https://github.com/WordPress/gutenberg/assets/491189/7c00d597-a616-4e54-bfd5-78cfb96afccc">

---

![Screen-Shot-2024-05-24-at-9-10-16-PM](https://github.com/WordPress/gutenberg/assets/491189/9ec85428-4243-4db0-bd06-1c22921f4b4e)

**foobar.ts**
```
export const foo = () => {
	console.log( 'foo' );
};

export const bar = () => {
	console.log( 'bar' );
};
```

**foobar.spec.ts**
```
import { foo, bar } from '../foobar';

describe( 'foobar', () => {
	afterEach( () => {
		jest.restoreAllMocks();
	} );

	describe( 'foo', () => {
		it( 'logs to console', () => {
			foo();

			expect( console ).toHaveLoggedWith( 'foo' );
		} );
	} );

	describe( 'bar', () => {
		it( 'logs to console', () => {
			bar();

			expect( console ).toHaveLoggedWith( 'bar' );
		} );
	} );
} );
```

### Environment info

- `"@wordpress/scripts": "^26.15.0",`

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jamesmehorter** [comment]
I believe this issue should be labeled as `"[Package] Jest console"`

**Comment by youknowriad** [comment]
Closing to consolidate with #48042: both stem from jest-console's spy lifecycle colliding with jest-mock's revised reset/restore semantics (jest ≥29.4), and one fix addresses both — likely re-applying the implementation after reset instead of relying on mockReset(). Linked this reproduction there. Thanks!
