### ISSUE TITLE
Errors when Redux Devtools is enabled

### ISSUE THREAD

**Issue by kevin940726** [WordPress/gutenberg#65072]
### Description

Do we still support Redux Devtools? Either way, Redux Devtools remains a popular browser extension many React developers install. Enabling the extension in Gutenberg sometimes outputs errors in the console even when the user is not directly interacting with the extension.

```
Uncaught TypeError: t.toString is not a function
    at ae.stringifyFunction (page.bundle.js:1:1448)
    at s (page.bundle.js:1:2855)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
    at s (page.bundle.js:1:4383)
```

What's worse is that it's not clear in the console that it's caused from Redux Devtools.

It's especially confusing for new contributors, who would probably just avoid contributing if they thought that their environment was not supported.

### Step-by-step reproduction instructions

1. Install Redux Devtools in your browser and enable it.
2. Open the devtools and interact with gutenberg (try selecting an image block for instance), sometimes the Redux Devtools tab doesn't even need to be active.
3. See some random errors in the console.

### Screenshots, screen recording, code snippet

![image](https://github.com/user-attachments/assets/d19721b4-a4c3-4088-a838-ffc8a92e0a9b)

### Environment info

- Tested on Brave (or other chromium based browsers) and the latest Redux Devtools from the extension store.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

I found an old [issue](https://github.com/WordPress/gutenberg/issues/919) but proved that we used to support Redux Devtools.

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Rishit30G** [comment]
Thanks for sharing the issue, 

However I could not reproduce the issue, sharing a screencast for the same: 

https://github.com/user-attachments/assets/7475148f-1412-423d-8c13-c1b556c9db75

#### Environment 

- WordPress 6.8.1 
- Gutenberg 20.7.0 
- Theme TT5 
- Google Chrome ( Chromium Based ) 
- MacOS Sequoia
