### ISSUE TITLE
Image Block: Lightbox does not work

### ISSUE THREAD

**Issue by t-hamano** [WordPress/gutenberg#66691]
### Description

When I insert an Image block with the lightbox enabled into the content, the lightbox doesn't work. Also, the Navigation block doesn't work either.

The following error is logged in the browser console:

```
view.js:46 Uncaught (in promise) ReferenceError: Cannot access 'state' before initialization
    at get isMenuOpen (view.js:46:21)
    at callback (signals.ts:106:15)
    at y.x (utils.ts:179:11)
    at __webpack_modules__../node_modules/@preact/signals-core/dist/signals-core.module.js.h (index.ts:567:22)
    at c (index.ts:415:18)
    at t (index.ts:61:39)
    at r (index.ts:102:3)
    at deepMerge (state.ts:397:7)
    at store (store.ts:247:12)
    at view.js:21:33
```

I think this issue is related to #66001. I temporarily reverted #66001 and it fixed the issue.

### Step-by-step reproduction instructions

This issue is a bit unstable, refresh your browser a few times if you can't reproduce it.

- Insert an Image block.
- Apply lightbox and save the post.
- Check the post on the frontend.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/f0ae9362-2879-4df3-b929-7c64472c1e25

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by t-hamano** [comment]
After testing a few different combinations, this appears to occur when the page contains a Navigation block and an Image block with lightbox enabled.

**Comment by annezazu** [comment]
@artemiomorales can you take a look at this? @t-hamano  what version of WP and GB are you using here?

**Comment by artemiomorales** [comment]
@annezazu I've started taking a look 👍

**Comment by artemiomorales** [comment]
I've been able to reproduce this using Gutenberg 19.6.0-rc.3, on both WordPress 6.6.2 and 6.7-RC2. It's only present when Gutenberg is enabled.

it seems this has less to do with the lightbox specifically and more to do with Interactivity API internals via https://github.com/WordPress/gutenberg/pull/66001 as @t-hamano pointed out. Namely, I see that the error originates in the Navigation block's `view.js` when trying to run the `store()` method.

Perhaps it'd be more apt for @michalczaplinski or @DAreRodz to take a look?

**Comment by cbravobernal** [comment]
Checking the `state` before using it would fix it. But we should not rely on this solution and fix it by default on the store function.
I can take a look at it later.

Pinging @westonruter , as I don't know how `window.scheduler?.yield` works under the hood.

```diff
diff --git a/packages/block-library/src/navigation/view.js b/packages/block-library/src/navigation/view.js
index 9da7ab70d8..1f63b9e2a0 100644
--- a/packages/block-library/src/navigation/view.js
+++ b/packages/block-library/src/navigation/view.js
@@ -24,26 +24,26 @@ const { state, actions } = store(
 		state: {
 			get roleAttribute() {
 				const ctx = getContext();
-				return ctx.type === 'overlay' && state.isMenuOpen
+				return ctx.type === 'overlay' && state?.isMenuOpen
 					? 'dialog'
 					: null;
 			},
 			get ariaModal() {
 				const ctx = getContext();
-				return ctx.type === 'overlay' && state.isMenuOpen
+				return ctx.type === 'overlay' && state?.isMenuOpen
 					? 'true'
 					: null;
 			},
 			get ariaLabel() {
 				const ctx = getContext();
-				return ctx.type === 'overlay' && state.isMenuOpen
+				return ctx.type === 'overlay' && state?.isMenuOpen
 					? ctx.ariaLabel
 					: null;
 			},
 			get isMenuOpen() {
 				// The menu is opened if either `click`, `hover` or `focus` is true.
 				return (
-					Object.values( state.menuOpenedBy ).filter( Boolean )
+					Object.values( state?.menuOpenedBy ).filter( Boolean )
 						.length > 0
 				);
 			},
@@ -109,7 +109,7 @@ const { state, actions } = store(
 			handleMenuKeydown( event ) {
 				const { type, firstFocusableElement, lastFocusableElement } =
 					getContext();
-				if ( state.menuOpenedBy.click ) {
+				if ( state?.menuOpenedBy.click ) {
 					// If Escape close the menu.
 					if ( event?.key === 'Escape' ) {
 						actions.closeMenu( 'click' );
@@ -160,7 +160,7 @@ const { state, actions } = store(
 
 			openMenu( menuOpenedOn = 'click' ) {
 				const { type } = getContext();
-				state.menuOpenedBy[ menuOpenedOn ] = true;
+				state?.menuOpenedBy[ menuOpenedOn ] = true;
 				if ( type === 'overlay' ) {
 					// Add a `has-modal-open` class to the <html> root.
 					document.documentElement.classList.add( 'has-modal-open' );
@@ -169,9 +169,9 @@ const { state, actions } = store(
 
 			closeMenu( menuClosedOn = 'click' ) {
 				const ctx = getContext();
-				state.menuOpenedBy[ menuClosedOn ] = false;
+				state?.menuOpenedBy[ menuClosedOn ] = false;
 				// Check if the menu is still open or not.
-				if ( ! state.isMenuOpen ) {
+				if ( ! state?.isMenuOpen ) {
 					if (
 						ctx.modal?.contains( window.document.activeElement )
 					) {
@@ -191,7 +191,7 @@ const { state, actions } = store(
 			initMenu() {
 				const ctx = getContext();
 				const { ref } = getElement();
-				if ( state.isMenuOpen ) {
+				if ( state?.isMenuOpen ) {
 					const focusableElements =
 						ref.querySelectorAll( focusableSelectors );
 					ctx.modal = ref;
@@ -202,7 +202,7 @@ const { state, actions } = store(
 			},
 			focusFirstElement() {
 				const { ref } = getElement();
-				if ( state.isMenuOpen ) {
+				if ( state?.isMenuOpen ) {
 					const focusableElements =
 						ref.querySelectorAll( focusableSelectors );
 					focusableElements?.[ 0 ]?.focus();
```

**Comment by westonruter** [comment]
How was `scheduler.yield()` identified as the source of the problem?

**Comment by t-hamano** [comment]
@westonruter I verified via `git bisect` that this issue first appeared in #66001. If you run `git revert cd8d4dc`, you will see that this problem is solved.

**Comment by cbravobernal** [comment]
Also, only happens in Chrome 😅

**Comment by westonruter** [comment]
Well, I'm guessing that Preact is perhaps itself using `setTimeout()` to break up a task, and so when `splitTask` is using `setTimeout()` as well, then the dependent initialization code for the state is getting set up at the right time. When splitting tasks with `setTimeout()` the split task is added to the end of the queue, whereas with `scheduler.yield()` the split task is added to the beginning of the queue. So perhaps there needs to be a single hard-coded split task using `setTimeout()` up-front for the sake of Preact but then within the loop which hydrates each of the blocks we can continue to leverage `scheduler.yield()`?

**Comment by westonruter** [comment]
It seems there is also a race condition going on as well. If I do a hard reload of the page, I only get the error with `state` about half the time, whereas if I do a soft reload it then occurs almost every time:

https://github.com/user-attachments/assets/55cb54b0-a65b-4f4b-b6da-4deb4456450d

**Comment by westonruter** [comment]
PR incoming.

**Comment by westonruter** [comment]
See proposed fix in #66772. It doesn't seem to be an issue with Preact at all. In fact, it seems the Interactivity API's `init` function was not correctly delaying itself until after the interactive blocks have initialized. This issue was masked by the fact that the hydration loop started with `await splitTask()` which meant it was delaying execution when `splitTask()` was implemented with `setTimeout()`. But when `splitTask()` is implemented with `scheduler.yield()` then the tail of the slit task is added to the front of the task queue instead of the end, meaning that the hydration loop continues before the modules are given a chance to initialize. So my proposed fix is just to add an initial `setTimeout()` before the hydration loop to force a delay to ensure the module dependencies have initialized.

**Comment by westonruter** [comment]
This does not seem to be fixed. It still happens to me sporadically. 

On [my blog](https://weston.ruter.net/), the mobile nav menu sometimes won't work and in the console there will be an error coming from `navigation/view.min.js`:

> ReferenceError: Cannot access 's' before initialization at get isMenuOpen

There seems to be a race condition. It's frustrating because the error happens whenever I least expect it.

**Comment by westonruter** [comment]
After 75 page reloads, for example, I was able to get the issue to occur:

<img width="1202" height="349" alt="Image" src="https://github.com/user-attachments/assets/9de90605-105e-4233-8b2c-e03ae341396e" />

**Comment by westonruter** [comment]
Without the minified scripts:

> Uncaught ReferenceError: Cannot access 'state' before initialization

The error is occurring here:

https://github.com/WordPress/gutenberg/blob/939bcb1238ac54d975316baffaf0a9b2942af6f8/packages/block-library/src/navigation/view.js#L48-L54

```
Uncaught ReferenceError: Cannot access 'state' before initialization
    at get isMenuOpen (view.js?ver=876b8c26d1934a566a17:62:28)
    at callback (debug.js?ver=3b816ce01eec3d8668c8:697:32)
    at signals_core_module_y.wrapped [as x] (debug.js?ver=3b816ce01eec3d8668c8:326:16)
    at __webpack_modules__.615.h (debug.js?ver=3b816ce01eec3d8668c8:55:3929)
    at signals_core_module_c (debug.js?ver=3b816ce01eec3d8668c8:55:3021)
    at signals_core_module_t (debug.js?ver=3b816ce01eec3d8668c8:55:310)
    at signals_core_module_r (debug.js?ver=3b816ce01eec3d8668c8:55:585)
    at deepMerge (debug.js?ver=3b816ce01eec3d8668c8:1055:56)
    at store (debug.js?ver=3b816ce01eec3d8668c8:1354:5)
    at view.js?ver=876b8c26d1934a566a17:46:44
```

**Comment by luisherranz** [comment]
I guess the race condition was caused by the delay in the initialization logic that was introduced in [this PR](https://github.com/WordPress/gutenberg/pull/66772) to avoid the state initialization error when a store is initialized after hydration.

@DAreRodz and I are currently looking at:
- How to [refactor the initialization logic](https://github.com/WordPress/gutenberg/issues/70870) so that this type of racing delays are not needed.
- How to [solve the state initialization error](https://github.com/WordPress/gutenberg/issues/70874) when the stores are initialized after hydration.

**Comment by luisherranz** [comment]
We haven't refactored the initialization logic yet, but the state initialization error has already been resolved. So, starting from Gutenberg 21.6, this problem should not be seen again. This is the PR with the fix:

- https://github.com/WordPress/gutenberg/issues/70874

@westonruter, It would be great if you could take a look to see if this lightbox problem has disappeared.

**Comment by mtias** [comment]
Closing this, but please reopen if still running into issues.
