### ISSUE TITLE
Error in @wordpress/components Storybook

### ISSUE THREAD

**Issue by psrpinto** [WordPress/gutenberg#68090]
### Description

An error is shown in the [`@wordpress/components` Storybook](https://wordpress.github.io/gutenberg/?path=/docs/playground-block-editor--docs), in the "Playground -> Block Editor" section.

### Step-by-step reproduction instructions

1. Go to https://wordpress.github.io/gutenberg/?path=/docs/playground-block-editor--docs
3. The error is shown

### Screenshots, screen recording, code snippet

<img width="1328" alt="Image" src="https://github.com/user-attachments/assets/0e57e2b2-8ea7-4c1b-8fd9-e5d1e1a1461a" />

```
Error: settings is undefined
  at useMemo (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:560907)
  at ./node_modules/react/cjs/react.production.min.js/exports.useMemo (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:632997)
  at useMediaUploadSettings (/gutenberg/4947.ae0f0d66.iframe.bundle.js:1:570189)
  at ./packages/block-editor/build-module/index.js/ExperimentalBlockEditorProvider< (/gutenberg/4947.ae0f0d66.iframe.bundle.js:1:570900)
  at Nh (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:554670)
  at Vk (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:613271)
  at Uk (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:602566)
  at Tk (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:602497)
  at Ik (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:602364)
  at Nk (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:599248)
  at Gk (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:597806)
  at J (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:635257)
  at R (/gutenberg/9584.e086b6ad.iframe.bundle.js:94:635806)
```

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Rishit30G** [comment]
I can see a different issue, this can be fixed through optional chaining: 

<img width="1100" alt="Image" src="https://github.com/user-attachments/assets/e4da9db3-8c72-42bd-872e-679498e9bb8b" />

**Comment by Mamaduka** [comment]
This also has been reported in https://github.com/WordPress/gutenberg/pull/66290#issuecomment-2551053441.

cc @t-hamano
