### ISSUE TITLE
Conflict with Wordfence in multisite

### ISSUE THREAD

**Issue by shoelaced** [WordPress/gutenberg#7643]
**Describe the bug**
When both Wordfence and Gutenberg are active in a multisite, an error appears instead of the editor. Clicking "Copy Error" provided the following. I tested it on a non-multisite installation and did not get the error.

```
TypeError: wp.media is not a function
    at new t (https://example.com/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=1530289025:9:38460)
    at yh (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:5:4154)
    at lg (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2629)
    at mg (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:2927)
    at gc (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:6310)
    at vb (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5820)
    at ub (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5655)
    at zd (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5027)
    at ra (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:4386)
    at Object.enqueueSetState (https://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:8:9426)
```

**To Reproduce**
1. Network-activate both Gutenberg and Wordfence.
2. Go to "Pages" and click on any page.
3. Error appears instead of editor.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 67 (latest)

**Additional context**
- Gutenberg version 3.1.1
- PHP 7.0

**Comment by youknowriad** [comment]
Thanks for the issue, are you still having the issue? 

As 5.0 is out with Gutenberg, I suggest reaching out to the plugin authors as well. If there's more details about the source of the issue we'd be happy to reopen and work on it.
