### ISSUE TITLE
Check output of npm test commands for package errors

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#8086]
Sometimes you need to remove `node_modules` and start over when packages have been changed/not published/etc. or you'll get errors that aren't super-easy to diagnose, especially if you aren't super-familiar with lerna/how our packages work. Stuff like:

```
 FAIL  packages/blocks/src/api/test/serializer.js
  ● Test suite failed to run

    Cannot find module '@wordpress/block-serialization-spec-parser' from 'parser.js'

      41 | 	// - Transformed: `false`
      42 | 	//
    > 43 | 	// <input disabled>
         | 	                             ^
      44 | 	// - Value:       `''`
      45 | 	// - Transformed: `true`
      46 | 	//

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (packages/blocks/src/api/parser.js:43:37)

 FAIL  editor/components/default-block-appender/test/index.js
  ● Test suite failed to run

    Cannot find module '@wordpress/blocks' from 'index.js'

      17 | /**
      18 |  * Internal dependencies
    > 19 |  */
         |              ^
      20 | import './style.scss';
      21 | import BlockDropZone from '../block-drop-zone';
      22 | import InserterWithShortcuts from '../inserter-with-shortcuts';

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (editor/components/default-block-appender/index.js:19:15)
```

See: https://wordpress.slack.com/archives/C02QB2JS7/p1532097292000483

It'd be nice if we could check the output of test commands for things like `Cannot find module '@wordpress/` and suggested clearing out `node_modules`.

**Comment by youknowriad** [comment]
I don't think this is worth the effort. Also, this is happening less often, now that we have packages for everything and we're not moving packages everyday.

Closing for now.
