### ISSUE TITLE
Spacer & Image blocks do not function in IE11

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8613]
**Describe the bug**

In IE11, the spacer and image blocks are replaced with an error message:

<img width="656" alt="screen shot 2018-08-06 at 1 43 17 pm" src="https://user-images.githubusercontent.com/1202812/43732306-511f66c6-997f-11e8-8e83-764525a0b71f.png">

**To Reproduce**

1. Use IE11
2. Add a spacer or image block
3. See the message.

**Tested in:**
Windows 7, IE 11.0.9600.17420
Gutenberg 3.4

**Comment by youknowriad** [comment]
Can you provide the JavaScript error in the console as well? Thanks

**Comment by kjellr** [comment]
Sure, @youknowriad:

```TypeError: Object doesn't support property or method 'from'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'from'",
      message: "Object doesn't support property or method 'from'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'from'
   at Anonymous function (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1533571140:12:70124)
   at base.get (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1533571140:12:70011)
   at value (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1533571140:12:63686)
   at jc (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:121)
   at gc (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
   at vb (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
   at ub (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
   at zd (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/"
   }

TypeError: Object doesn't support property or method 'from'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'from'",
      message: "Object doesn't support property or method 'from'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'from'
   at Anonymous function (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1533571140:12:70124)
   at base.get (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1533571140:12:70011)
   at value (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/build/core-blocks/index.js?ver=1533571140:12:64471)
   at dg (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:110:434)
   at eg (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:113:462)
   at jc (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:131:280)
   at gc (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
   at vb (https://original-smelt.jurassic.ninja/wp-content/plugins/gutenberg"
   }
```

Also, this seems to effect the image block too, so I'll update the title to reflect that. 

<img width="687" alt="screen shot 2018-08-06 at 1 49 49 pm" src="https://user-images.githubusercontent.com/1202812/43732775-82e5e012-9980-11e8-97a9-19273b87774e.png">

**Comment by brandonpayton** [comment]
I can reproduce this with 3.4 but no longer on master. 🙌
