### ISSUE TITLE
"The editor has encountered an unexpected error" and "This block has encountered an error and cannot be previewed" (solved by updating the ACF plugin)

### ISSUE THREAD

**Issue by hornisch** [WordPress/gutenberg#8866]
We installed latest Gutenberg and on every page we used Gutenberg is now noted:
The editor has encountered an unexpected error.

Recovery does not work 

Error copy:

TypeError: Object(...) is not a function
    at Ke (http://test.wirsindheller.de/wp-content/plugins/gutenberg/build/blocks/index.js?ver=1533974678:2:142449)
    at t.value (http://test.wirsindheller.de/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533974678:12:186219)
    at Xf (http://test.wirsindheller.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:268)
    at yh (http://test.wirsindheller.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:102:317)
    at lg (http://test.wirsindheller.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (http://test.wirsindheller.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (http://test.wirsindheller.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)
    at vb (http://test.wirsindheller.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (http://test.wirsindheller.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at zd (http://test.wirsindheller.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449)

And - if we start a new page using gutenberg there is following error:
This block has encountered an error and cannot be previewed.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 68.0.3440.84

**Additional context**
- Please add the version of Gutenberg 3.5.0 
we are using ACF in the theme
Wordfence
WP Rocket

Latest Version of Gutenberg worked fine.
Is this another problem with ACF - and how can we fix this?

Best regards

**Comment by designsimply** [comment]
> Not sure if I should close this and open a new issue

Yes, please! Creating a new issue would be good in this case. In the new issue, it would be helpful to include a copy of any error messages you see in your browser console at same time you see the "updating failed" message on screen. Please also note whether or not you have found this problem happens in more than one theme or if the problem is limited to a specific theme.
