### ISSUE TITLE
Gutenberg crashes when I tried re-editing a post.

### ISSUE THREAD

**Issue by Chintiger** [WordPress/gutenberg#8999]
When I open an existing Gutenberg post (the demo post) and select any of blocks, Gutenberg crashes and moves to the error screen with "unexpected error occurred."

This error occurs on random and arbitrary block such like the title, gallery, the (+) button on a block and any others.

Console messages:

```
Uncaught (in promise) TypeError: Cannot read property 'attributes' of undefined
    at index.js?ver=1533882174:2
    at $e (index.js?ver=1533882174:2)
    at Array.map (<anonymous>)
    at et (index.js?ver=1533882174:2)
    at index.js?ver=1533882174:12
    at d (index.js?ver=1533882174:12)
    at index.js?ver=1533882174:12
    at k (index.js?ver=1533882174:12)
    at Generator._invoke (index.js?ver=1533882174:12)
    at Generator.e.(/wp-admin/anonymous function) [as next] (http://***/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533882174:12:44939)


react-dom.min.82e21c65.js:110 TypeError: Cannot read property 'title' of undefined
    at t.value (index.js?ver=1533882174:12)
    at Xf (react-dom.min.82e21c65.js:91)
    at yh (react-dom.min.82e21c65.js:102)
    at lg (react-dom.min.82e21c65.js:120)
    at mg (react-dom.min.82e21c65.js:120)
    at gc (react-dom.min.82e21c65.js:127)
    at vb (react-dom.min.82e21c65.js:126)
    at ub (react-dom.min.82e21c65.js:126)
    at zd (react-dom.min.82e21c65.js:124)
    at ra (react-dom.min.82e21c65.js:123)


bg @ react-dom.min.82e21c65.js:110
2index.js?ver=1533882174:12 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at t.value (index.js?ver=1533882174:12)
    at e (lodash.min.59550321.js:68)
    at f (lodash.min.59550321.js:68)
index.js?ver=1533882174:12 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at t.value (index.js?ver=1533882174:12)
    at e (lodash.min.59550321.js:68)
    at o (lodash.min.59550321.js:68)
    at i (lodash.min.59550321.js:68)


react-dom.min.82e21c65.js:110 TypeError: Cannot read property 'title' of undefined
    at t.value (index.js?ver=1533882174:12)
    at Xf (react-dom.min.82e21c65.js:91)
    at yh (react-dom.min.82e21c65.js:102)
    at lg (react-dom.min.82e21c65.js:120)
    at mg (react-dom.min.82e21c65.js:120)
    at gc (react-dom.min.82e21c65.js:127)
    at zd (react-dom.min.82e21c65.js:124)
    at ra (react-dom.min.82e21c65.js:123)
    at Id (react-dom.min.82e21c65.js:138)
    at kc (react-dom.min.82e21c65.js:138)
bg @ react-dom.min.82e21c65.js:110

react-dom.min.82e21c65.js:110 TypeError: Cannot read property 'title' of undefined
    at t.value (index.js?ver=1533882174:12)
    at Xf (react-dom.min.82e21c65.js:91)
    at yh (react-dom.min.82e21c65.js:102)
    at lg (react-dom.min.82e21c65.js:120)
    at mg (react-dom.min.82e21c65.js:120)
    at gc (react-dom.min.82e21c65.js:127)
    at vb (react-dom.min.82e21c65.js:126)
    at ub (react-dom.min.82e21c65.js:126)
    at wg (react-dom.min.82e21c65.js:137)
    at Ze (react-dom.min.82e21c65.js:41)
```

**Comment by designsimply** [comment]
May I ask what version of Gutenberg you are testing with?

**Comment by Chintiger** [comment]
It's 3.5.0.

![3df3f6abe17d1ef8efb0d5b8301ed810](https://user-images.githubusercontent.com/13434151/44120623-e78ecb86-a057-11e8-8b20-38856381f981.gif)

**Comment by maddisondesigns** [comment]
After updating to 3.6.2, Gutenberg also crashes for me on multiple pages when I simply try to edit them. I don't even get the editor, it just crashes straight away with "The editor has encountered an unexpected error".

![screenshot_806](https://user-images.githubusercontent.com/2078245/44387952-3fc82d80-a56a-11e8-8803-19e594c36f01.png)

```
this.wp.editor</Gl</<@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1534581736:12:323961
yh@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:96:396
lg@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88
mg@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386
gc@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202
vb@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230
ub@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65
zd@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449
ra@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:123:319
enqueueSetState@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:189:231
q.prototype.setState@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:18:428
value/this.unsubscribe<@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:64692
r/</<@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:60636
r/<@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:60607
d@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:47100
n/<@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:61716
w@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:38364
x/i._invoke</<@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:38154
j/</t[n]@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:38540
o@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:30431
c@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:30633
u@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:43078
A/<@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:43223
s@http://dev.wordpress-test.com/wp-content/plugins/gutenberg/build/data/index.js?ver=1534581736:1:41492
``` 

The Console shows dozens of "Block validation: Block validation failed for..." errors, for all types of blocks.

On a sidenote, the "Copy post Text" button and the "Copy Error" button, copies the exact same content to the clipboard

**Comment by foysalremon** [comment]
On my case, after updating 3.6.2, when I edit and save any block which have some array type attribute values of attributes become undefined and thus giving a **Block validation failed** error.

**Comment by donnywi** [comment]
I am getting a similar error with version 3.7.0.  I was able to edit my document a few times, but suddenly, it just stops working.

This is the error I'm getting.
`TypeError: Cannot read property 'getCollectionByRoute' of undefined
    at t.value (https://sidehustlingparents.com/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:145344)
    at t.value (https://sidehustlingparents.com/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:144551)
    at jc (https://sidehustlingparents.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:123)
    at gc (https://sidehustlingparents.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
    at vb (https://sidehustlingparents.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://sidehustlingparents.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at wg (https://sidehustlingparents.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
    at Ze (https://sidehustlingparents.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)
`

**Comment by youknowriad** [comment]
@donnywi See here https://github.com/WordPress/gutenberg/issues/9541#issuecomment-417874697 it's a different error for you.

**Comment by donnywi** [comment]
Thanks @youknowriad

**Comment by designsimply** [comment]
Please update to the latest version of WordPress and uninstall the Gutenberg plugin. If the problem is still happening, please re-open this issue and please include the console messages again and also note the versions you tested with.

**Comment by davidrhoden** [comment]
Getting this error:
`TypeError: Cannot read property 'title' of undefined
    at http://moxiemedianew.local/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:116844
    at t.value (http://moxiemedianew.local/wp-includes/js/dist/editor.min.js?ver=9.0.11:55:111452)
    at Fd (http://moxiemedianew.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:92:367)
    at Mf (http://moxiemedianew.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:92:160)
    at ph (http://moxiemedianew.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:98:474)
    at eg (http://moxiemedianew.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:125:307)
    at fg (http://moxiemedianew.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:126:168)
    at wc (http://moxiemedianew.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:138:237)
    at fa (http://moxiemedianew.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:137:115)
    at lg (http://moxiemedianew.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:148:342)`

WP 5.1.1.

**Comment by designsimply** [comment]
@davidrhoden can you confirm that the same error happens for you with all plug-ins temporarily deactivated? Also make sure to clear cache for the site if you are using a cashing service of any kind.

**Comment by JeffreyPia** [comment]
I ran into this error when I created custom Gutenberg blocks using a plugin, but then switched to another Git branch that did not have the plugin. The Editor tried to call some functions that no longer existed, and failed hard. I would hope a more graceful fallback could be implemented, but for me at least this seems to be an edge case that would only occur in a Development environment. It was frustrating when it first occurred though.

**Comment by designsimply** [comment]
Thanks for the input and confirmation.

**Comment by dsawardekar** [comment]
I ran into this issue on Gutenberg 10.7.0. The problem was that I was customizing the REST API response and was sending back an empty content response field. Gutenberg expects the `content.rendered` property in the response, if it is absent the Block parser fails very early in the loading staging -- resulting in a fatal exception & white screen.
