### ISSUE TITLE
A New Bug for Image-Upload,The response is not a valid JSON response.

### ISSUE THREAD

**Issue by ddgweb** [WordPress/gutenberg#9142]
Today I update the version to  3.6.2 ,then the bug's coming ,when I upload Image ,the webview will tip "The response is not a valid JSON response"

**Comment by ddgweb** [comment]
Em...when I foud the Image cann't be upload, I cancel the gutenberg and install the WordPress default's Edit ,So Now , The another question is how to show the gutenberg back to my WordPress.......

**Comment by zethodderskov** [comment]
I got the same error. 

Demo: https://d.pr/free/i/5PLEvA
Demo with console open: https://d.pr/free/i/53sBpo
... in the console it writes: `POST http://MYURL.com/wp-json/wp/v2/media 500 (Internal Server Error)`
If I click the error in the console, then it takes me here: https://d.pr/free/i/AidpEx

Here's what happens in the PHP error-log on the server:

```
[DATETIME-STAMP] [fcgid:warn] [pid 19611:tid 140091104134912] [CLIENT_IP] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function upload_is_user_over_quota() in /PATH/FOO/BAR/PUBLIC_HTML/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php:808, referer: URL/wp-admin/post.php?post=949&action=edit
[DATETIME-STAMP] [fcgid:warn] [pid 19611:tid 140091104134912] [CLIENT_IP] mod_fcgid: stderr: Stack trace:, referer: URL/wp-admin/post.php?post=949&action=edit
[DATETIME-STAMP] [fcgid:warn] [pid 19611:tid 140091104134912] [CLIENT_IP] mod_fcgid: stderr: #0 /PATH/FOO/BAR/PUBLIC_HTML/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(734): WP_REST_Attachments_Controller->check_upload_size(Array), referer: URL/wp-admin/post.php?post=949&action=edit
[DATETIME-STAMP] [fcgid:warn] [pid 19611:tid 140091104134912] [CLIENT_IP] mod_fcgid: stderr: #1 /PATH/FOO/BAR/PUBLIC_HTML/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(108): WP_REST_Attachments_Controller->upload_from_file(Array, Array), referer: URL/wp-admin/post.php?post=949&action=edit
[DATETIME-STAMP] [fcgid:warn] [pid 19611:tid 140091104134912] [CLIENT_IP] mod_fcgid: stderr: #2 /PATH/FOO/BAR/PUBLIC_HTML/wp-includes/rest-api/class-wp-rest-server.php(936): WP_REST_Attachments_Controller->create_item(Object(WP_REST_Request)), referer: URL/wp-admin/post.php?post=949&action=edit
[DATETIME-STAMP] [fcgid:warn] [pid 19611:tid 140091104134912] [CLIENT_IP] mod_fcgid: stderr: #3 /PATH/FOO/BAR/PUBLIC_HTML/wp-includes/rest-api/class-wp-rest-server.php(321): WP_REST_Server->dispatch(Object(WP_REST_Request)), referer: URL/wp-admin/post.php?post=949&action=edit
[DATETIME-STAMP] [fcgid:warn] [pid 19611:tid 140091104134912] [CLIENT_IP] mod_fcgid: stderr: #4 /PATH/FOO/BAR/PUBLIC_HTML/wp-includes/rest-api.php(266): WP_REST_Server->serve_request('/wp/v2/media'), referer: URL/wp-admin/post.php?post=949&action=edit
[DATETIME-STAMP] [fcgid:warn] [pid 19611:tid 140091104134912] [CLIENT_IP] mod_fcgid: stderr: #5 /PATH/FOO/BAR/PUBLIC_HTML/wp-inclu in /PATH/FOO/BAR/PUBLIC_HTML/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php on line 808, referer: URL/wp-admin/post.php
```

**Facts:**
 - When I click the error in the console, then it takes me 
 - I'm getting the error in both Google Chrome and Safari. I'm on a Macbook Pro 10.12.6 (Sierra). 
 - I get it both with PNG's and JPG's, both larger files [2mb+] and smaller ones [5kb]. I get the same error regardless. 
 - I'm on a multi-site, where all sites share the same parent- and child-theme. I have the issue in all sites. 
 - I have previously had issues with the permissions of my `.htaccess`-file, - but I don't think this is related. 
 - The site is running HTTP - and not HTTPS. 
 - I tried reinstalling WordPress (from the 'Update Core'-page). It didn't change anything. 
 - On this multisite I have been making quite a few customizations, - making a new CPT and messing with the save_post-hook. 
 - I have tried commenting almost everything out in the functions.php-file, - and I still get the same error. 
 - I have Gutenberg installed on another site, - and I DO NOT get the error on that site. Hmm! I'm using the same image-file. So it DOES NOT work on www.foobar.org, - but it DOES work on www.example.org. Before testing on www.example.org, then I updated to the latest version of Gutenberg (so they're running the save version - 3.6.2).

**Comment by zethodderskov** [comment]
I tried to find a work-around, - and a Jacob Peattie said that he found the bug implemented in WordPress version 4.9.8. Source: https://wordpress.stackexchange.com/questions/312859/call-to-undefined-function-upload-is-user-over-quota

... There is a work-around on that page as well.

**Comment by designsimply** [comment]
@ddgweb to re-install Gutenberg, go to WP Admin > Plugins, search for Gutenberg, and follow the on screen instructions to install and activate it. You should also see an option to install the plugin with a "Try Gutenberg" button on your main WP Admin > Dashboard page.

@zethodderskov thank you for the StackExchange link! I've added a `[Type] WP Core Bug` label because of the patch mentioned: https://core.trac.wordpress.org/changeset/43462
