### ISSUE TITLE
Editor won't work at all

### ISSUE THREAD

**Issue by jalexander4444** [WordPress/gutenberg#9506]
**Describe the bug**
When I try to edit a post or add a new post, I get a message that says "The editor has encountered an unexpected error." This has been happening since I updated the Gutenberg plugin earlier today. Clicking "Attempt Recovery" has not fixed the issue.

**To Reproduce**
1. Go to 'New'
2. Click on 'Post.'

OR

1. Go to 'All Posts'
2. Click 'Edit'
3. See error

**Expected behavior**
I should be able to add a new post or edit an existing post.

**Screenshots**
![error message](https://user-images.githubusercontent.com/42870379/44918061-134da780-ad08-11e8-82f0-f6f3b04dbaaf.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser - Chrome
 - Version - 68

**Additional context**
- Gutenberg version - 3.7.0
- Bug message:
TypeError: Cannot read property 'getCollectionByRoute' of undefined
    at t.value (https://blog.workful.com/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:145344)
    at t.value (https://blog.workful.com/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:144551)
    at jc (https://blog.workful.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:123)
    at gc (https://blog.workful.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
    at vb (https://blog.workful.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://blog.workful.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at zd (https://blog.workful.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449)
    at ra (https://blog.workful.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:123:319)
    at Object.enqueueSetState (https://blog.workful.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:189:231)
    at r.q.setState (https://blog.workful.com/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:18:441)

**Comment by Soean** [comment]
Hey @jalexander4444 
thanks for your issue. It's an error from the Yoast plugin, they are working on it, see: https://github.com/Yoast/wordpress-seo/issues/10867
Yoast SEO 8.1.1 will fix it.

**Comment by jalexander4444** [comment]
@Soean Thanks so much for letting me know!

**Comment by afercia** [comment]
Sorry for the issue, yes there's a pending fix in the Yoast plugin that will be hopefully released on Monday. 

The bug happens when trying to open the "Categories" panel in the Gutenberg sidebar. As a temporary workaround I would suggest: temporary disable Yoast SEO, then edit a post in Gutenberg and **close** the Categories panel. Then you can safely re-activate Yoast SEO and edit posts, as long as you don't re-open the Categories panel 🙂

**Comment by jalexander4444** [comment]
@afercia Thank you for the workaround!

**Comment by designsimply** [comment]
Thank you so much for reporting the conflict!

Here is the related issue at Yoast SEO for reference: https://github.com/Yoast/wordpress-seo/issues/10850

**Comment by designsimply** [comment]
A temporary workaround plugin file was posted at https://github.com/Yoast/wordpress-seo/issues/10867#issuecomment-417696845

**Comment by jdevalk** [comment]
This was fixed in our 8.1.1 release we did just now.

**Comment by GlennMartin1** [comment]
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, and (if applicable) deactivate and uninstall the workaround, and confirm the issue is addressed.
