### ISSUE TITLE
Gutenberg version: 3.7.0 - editor has encountered an unexpected error 

### ISSUE THREAD

**Issue by Pikkals** [WordPress/gutenberg#9516]
**Describe the bug**

The editor has encountered an unexpected error.

Can't attempt recovery, nothing happens.

**To Reproduce**
1. Go to 'Posts'
2. Click on 'Add New'
3. Select Gutenburg.'
4. See error:  "The editor has encountered an unexpected error."

Copy Error:

TypeError: Cannot read property 'getCollectionByRoute' of undefined
    at t.value (https://www.discerningtheworld.com/wp-content/plugins/wordpress-seo-premium/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:145344)
    at t.value (https://www.discerningtheworld.com/wp-content/plugins/wordpress-seo-premium/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:144551)
    at jc (https://www.discerningtheworld.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:123)
    at gc (https://www.discerningtheworld.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
    at vb (https://www.discerningtheworld.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://www.discerningtheworld.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at zd (https://www.discerningtheworld.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449)
    at ra (https://www.discerningtheworld.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:123:319)
    at Object.enqueueSetState (https://www.discerningtheworld.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:189:231)
    at r.q.setState (https://www.discerningtheworld.com/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:18:441)

**Desktop (please complete the following information):**
 - Windows 10: 
 - Chrome 
 - WP version  4.9.8–en_ZA
 - Gutenberg version: 3.7.0

**Comment by designsimply** [comment]
Thank you for reporting this! It is very helpful to have the console error noted. 

I am working to test it now and noting it may be the same issue at #9515.

**Comment by designsimply** [comment]
Here's what I have found so far:

<blockquote>This console error means in general that a plugin is relying on the `wp-api` script being present in the page. This script is no longer present by default in Gutenberg because Gutenberg is not using it anymore. Plugins should add it as an explicit dependency if they rely on it.</blockquote>

Would you be able to help me identify which plugins are the source of the trouble in your case? I will help work to notify them and help the plugin developers figure out how to fix the problem.

To find the source of a plugin conflict, you can temporarily disable all plugins and try creating a new post. If the error disappears, then re-activate each plugin one-by-one and test creating a new post each time until you find which plugin triggers the error.

**Comment by Pikkals** [comment]
Ok cool, I will check this out tomorrow if you don't mind.  Will come back to you asap :)

**Comment by Pikkals** [comment]
Oh that was easy... it's Yoast SEO.

I think it's got to do with the categories, in the classic editor you can select a primary category, in Gutenberg that option is not available anymore...  I noticed on previous version of Gutenberg the categories section was very unstable.  Would show a list of categories, and other times it wouldn't.

But that's just me guessing, but it's definitely Yoasts plugin Version 8.1

**Comment by Pikkals** [comment]
Yip definitely Yoast SEO Version 8..  Gutenberg now works fine with Yoast SEO Version 8.1 disabled.

**Comment by youknowriad** [comment]
Yes, they're working on a fix see here https://github.com/WordPress/gutenberg/issues/9506#issuecomment-417688790

Thanks

**Comment by Pikkals** [comment]
Oh YAY :) 

Great now we know.

**Comment by designsimply** [comment]
Thank you so much for testing and reporting!

Here is the related issue at Yoast SEO: https://github.com/Yoast/wordpress-seo/issues/10850

**Comment by GlennMartin1** [comment]
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, and (if applicable) deactivate and uninstall the workaround, and confirm the issue is addressed.

**Comment by Pikkals** [comment]
Gutenberg is working fine now on Yoast 8.1.1.

Thank you 👍
