### ISSUE TITLE
Bug report after upgrading Gutenberg

### ISSUE THREAD

**Issue by Visdief** [WordPress/gutenberg#9518]
Hello,

Earlier this evening I informed you about the bug after upgrading Gutenberg (the message editor does not work anymore; the page editor is still working fine). I now discover how to copy the code. Every minute a man discovers new things ;-).

The code is:

TypeError: Cannot read property 'getCollectionByRoute' of undefined
    at t.value (https://www.visdief.nl/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:145344)
    at t.value (https://www.visdief.nl/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:144551)
    at jc (https://www.visdief.nl/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:123)
    at gc (https://www.visdief.nl/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
    at vb (https://www.visdief.nl/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://www.visdief.nl/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at wg (https://www.visdief.nl/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
    at Ze (https://www.visdief.nl/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)

I hope you will be able to solve the problem. Thanks.

Sincerely,

Jako
[Issue Gutenberg.docx](https://github.com/WordPress/gutenberg/files/2341030/Issue.Gutenberg.docx)

**Comment by skorasaurus** [comment]
Hi, 
Do you have yoast seo installed? If so, thas is the cause; there's a workaround at https://github.com/Yoast/wordpress-seo/issues/10867#issuecomment-417696845

**Comment by GlennMartin1** [comment]
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, deactivate and uninstall the workaround, and confirm the issue is addressed.
