### ISSUE TITLE
Bug report after update to 3.7.0

### ISSUE THREAD

**Issue by marlonlamancio** [WordPress/gutenberg#9519]
**Describe the bug**

I'm not able to edit my post:

TypeError: Cannot read property 'getCollectionByRoute' of undefined
    at t.value (https://universowp.com.br/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:145344)
    at t.value (https://universowp.com.br/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:144551)
    at jc (https://universowp.com.br/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:9780)
    at gc (https://universowp.com.br/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:6331)
    at vb (https://universowp.com.br/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5820)
    at ub (https://universowp.com.br/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5655)
    at zd (https://universowp.com.br/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:5027)
    at ra (https://universowp.com.br/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:7:4386)
    at Object.enqueueSetState (https://universowp.com.br/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:8:9426)
    at r.q.setState (https://universowp.com.br/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:1:5028)

**To Reproduce**
Edit any post

**Desktop:**
 - OS: macOS High Sierra Version 10.13.6 (17G65)
 - Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Additional context**
- Gutenberg version: 3.7.0

**Comment by GlennMartin1** [comment]
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, and confirm the issue is addressed.

**Comment by wilanna** [comment]
This keeps showing up in the SEO when trying to use wizard and now on top of website: to join this conversation on GitHub. Already have an account? Sign in to comment © 2018 GitHub, Inc. Terms Privacy Security Status Help Contact GitHub Pricing API Training Blog About
