### ISSUE TITLE
gutenbug latest build has and isssue with yoast seo(may be)

### ISSUE THREAD

**Issue by rajkumargaur91** [WordPress/gutenberg#9526]
TypeError: Cannot read property 'getCollectionByRoute' of undefined
    at t.value (/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:145344)
    at t.value (/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:144551)
    at jc (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:123)
    at gc (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
    at vb (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at wg (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
    at Ze (/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)

both of plugins are up to date
Gutenberg Version 3.7.0
Yoast SEO : 8.1

**Comment by youknowriad** [comment]
Unfortunately, they have a bug in the Yoast 8.1 which was made visible by the Gutenberg 3.7 update. They are working on a fix (see here https://github.com/Yoast/wordpress-seo/issues/10850)

in the meantime, you can do the following workaround https://github.com/WordPress/gutenberg/issues/9506#issuecomment-417688790

Thanks

**Comment by jdevalk** [comment]
We've just released Yoast SEO 8.1.1 that fixes this. 

Background: Gutenberg 3.7 removed a dependency that we also relied on. The bug was on our side (we should have registered our dependency ourselves) but the testing process needs improvement on both sides, we're talking about that right now :)
