### ISSUE TITLE
TypeError: Cannot read property 'getCollectionByRoute' of undefined

### ISSUE THREAD

**Issue by Adivor** [WordPress/gutenberg#9527]
[https://ibb.co/iRQ3xz](url)

```
TypeError: Cannot read property 'getCollectionByRoute' of undefined
    at t.value (https://xxxxxxxx.xxx/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:145344)
    at t.value (https://xxxxxxxx.xxx/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-810.min.js?ver=8.1:1:144551)
    at jc (https://xxxxxxxx.xxx/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:134:123)
    at gc (https://xxxxxxxx.xxx/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:223)
    at vb (https://xxxxxxxx.xxx/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (https://xxxxxxxx.xxx/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at wg (https://xxxxxxxx.xxx/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
    at Ze (https://xxxxxxxx.xxx/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)
```

Any solution?

**Comment by Soean** [comment]
Hey @Adivor
Unfortunately, they have a bug in the Yoast 8.1 which was made visible by the Gutenberg 3.7 update. They are working on a fix (see here https://github.com/Yoast/wordpress-seo/pull/10870)

in the meantime, you can do the following workaround https://github.com/Yoast/wordpress-seo/issues/10867#issuecomment-417696845

Thanks

**Comment by Adivor** [comment]
Thanks!

**Comment by GlennMartin1** [comment]
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, deactivate and remove the workaround, and confirm the issue is addressed.
