### ISSUE TITLE
List blocks: Very frequent "this editor has encountered an error" crashes 

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#9602]
**Describe the bug**
I'm getting **lots** of crashes in the editor when doing anything with the list block

**To Reproduce**

example 1:
1. Create paragraph block
2. convert to list
3. crash (every time)

example 2:
1. Create a few list and paragraph blocks
2. select the list
3. crash (randomly, but frequently)

**Expected behavior**
I expect it not crash when doing simple operations like selecting a block

**Screenshots**
This gif shows me crashing the editor 2 times in 30 seconds

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/40266703/45016073-e6f59c00-b023-11e8-91fd-0b3e28e6eded.gif)

(side note: It also shows that it's hard to get the + icon to between blocks at some occasions)

**logs**

When converting the paragraph I get the following error:
```
TypeError: Cannot read property 'name' of undefined
    at http://sitename.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1535715874:12:312098
    at i (http://sitename.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:6:91)
    at An.filter (http://sitename.com/wp-content/plugins/gutenberg/vendor/lodash.min.59550321.js:99:338)
    at t.value (http://sitename.com/wp-content/plugins/gutenberg/build/editor/index.js?ver=1535715874:12:312028)
    at Xf (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:268)
    at yh (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:102:317)
    at lg (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)
    at vb (http://sitename.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
```

**Desktop (please complete the following information):**
- OS: macOS
- browser: Chrome

**Additional context**
- v 3.7
- From what I can tell there should be no plugin conflicts, I have this issue when I disable all block related plugins

**Comment by slimmilkduds** [comment]
Huh, I missed de-activating one of the Gutenberg related plugins. The cause of this issue is a conflict with the "Gutenberg Manager" Plugin, deactivating it makes this problem go away.
