### ISSUE TITLE
Uninstall and ReInstall corrupted the Entire WP-Admin

### ISSUE THREAD

**Issue by windson** [WordPress/gutenberg#9717]
**Describe the bug**
TypeError: wp.media is not a function
    at new t (http://example.com/wp-content/plugins/gutenberg/build/edit-post/index.js?ver=1536238904:12:36622)
    at yh (http://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:97:111)
    at lg (http://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (http://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (http://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)
    at vb (http://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230)
    at ub (http://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65)
    at wg (http://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182)
    at Ze (http://example.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24)

**To Reproduce**
I installed new wordpress along with Gutenberg 3 days ago. I enabled ocean theme
Today I installed Elementor and Ocean Extra plugins
WP-admin has few pages that contains tabs, editor pages (post, page editors) all stopped functioning.
The Tabs won't switch
The editor won't save changes

I uninstalled Elementor and Ocean Extra plugins and also uninstalled Gutenberg plugin.
The wp-admin is still non functional in the pages mentioned above. And Gutenberg editor is not installing and shows the above mentioned error stack trace.

**Comment by windson** [comment]
Hi,
Thanks for the response. I did a fresh install with same set up reported
and still faced the problem. But when I aced the wp-admin from my mobile
having different data plan everything seemed smooth. Later I accessed from
the same laptop where I saw the problem with different internet connection
and I no longer see the issue. I assume that the prior internet connection
has some automatic vpn configuration that caused few wp-admin areas like
add/edit post, add new theme and admin pages where tabs are present
malfunction. Switching to different internet connection solve my problem.

Thanks for your concern!
