### ISSUE TITLE
Gutenberg returns error 500 on save/update

### ISSUE THREAD

**Issue by Armadur** [WordPress/gutenberg#9816]
Gutenberg plugin throws error 500 on save of certain pages.
I also use WPML translation plugin, and both got stuck on SAVE/UPDATE
I have two languages, german and english, translation of same page on german works but on english it fails

**To Reproduce**
1. Go to 'pages' > somePage
2. Click on 'Save'
4. See error "Update failed"

**Expected behavior**
I except to save it with no problems, just like other pages,

**Screenshots**
![image](https://user-images.githubusercontent.com/26959135/45418450-d1681e00-b684-11e8-853c-828f1c827601.png)
![image](https://user-images.githubusercontent.com/26959135/45418496-ecd32900-b684-11e8-8569-e895e8971838.png)
![image](https://user-images.githubusercontent.com/26959135/45418513-f6f52780-b684-11e8-9123-663368d9f68c.png)

In my error_log on server i got this error when i try to save
```
[12-Sep-2018 09:46:18 UTC] PHP Fatal error:  Uncaught Exception: Invalid page template. in /usr/www/users/foodno/v32/wp-content/plugins/sitepress-multilingual-cms/inc/post-translation/wpml-post-duplication.class.php:99
Stack trace:
#0 /usr/www/users/myDomain/wp-content/plugins/sitepress-multilingual-cms/sitepress.class.php(4219): WPML_Post_Duplication->make_duplicate(5950, 'he')
#1 /usr/www/users/myDomain/wp-content/plugins/sitepress-multilingual-cms/inc/post-translation/wpml-post-synchronization.class.php(84): SitePress->make_duplicate(5950, 'he')
#2 /usr/www/users/myDomain/wp-content/plugins/sitepress-multilingual-cms/inc/post-translation/wpml-post-translation.class.php(248): WPML_Post_Synchronization->sync_with_duplicates(5950)
#3 /usr/www/users/myDomain/wp-content/plugins/sitepress-multilingual-cms/inc/post-translation/wpml-admin-post-actions.class.php(113): WPML_Post_Translation->after_save_post('535', Array, 'en', NULL)
#4 /usr/www/users/myDomain/wp-includes/class-wp-hook.php(288): WPML_Admin_Post_Actions->save_post_actions('5950', Objec in /usr/www/users/foodno/v32/wp-content/plugins/sitepress-multilingual-cms/inc/post-translation/wpml-post-duplication.class.php on line 99
```

**Additional context**
- Version of Gutenberg is 3.7.0, problems occured before and i updated in hope it will be fixed

**Comment by tofumatt** [comment]
Understood, in that case you will need to contact WPML and let them know about the bug, as they'll need to work to be compatible with Gutenberg on their end. For now you may want to use the Classic Editor plugin instead of Gutenberg, sorry about that.

**Comment by brucepearson** [comment]
@Armadur What version of WPML are you using? We're currently working on Gutenberg compatibility for our next release.

**Comment by Armadur** [comment]
We are using
- WPML Multilingual CMS v4.0.5
- WPML String Translation v2.8.6

I hope it will be solved soon, currently you must delete page and then create it again so it can work...
Thanks for reply
