### ISSUE TITLE
Minified React error #130; after update to 3.80

### ISSUE THREAD

**Issue by studio500** [WordPress/gutenberg#9866]
Unable to create a new post or edit existing.
I noticed on wordpress support page others are experiencing same issue.
[https://wordpress.org/support/topic/nvariant-violation-minified-react-error-130/](url)
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Sg (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:142:327)
    at m (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:12:388)
    at ed (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:65:98)
    at https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:87:294
    at rd (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:10)
    at O (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:90:455)
    at yh (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:104:145)
    at lg (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
    at mg (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386)
    at gc (https://www.bisfhouse.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202)

**Comment by youknowriad** [comment]
Can you try running your site with `SCRIPT_DEBUG`set to `true` to have a clearer error? This could be related to a plugin still using a deprecated component but it's not the only possible reason for it.

**Comment by studio500** [comment]
Will do

**Comment by studio500** [comment]
Nothing at all showing up in debug logs as yet.

Unable to create new post or new page. 
I have also deactivated all plugins and the error remains.

**Comment by studio500** [comment]
It may not be relevant but prior to this error, I had to edit a permalink on a new Gutenberg created post.
I did this by entering the post via the classic editor where I changed the link to match the new title, which I then saved.
I can still enter and edit all my posts via the classic editor but I get the above error when trying to edit in Gutenberg.

**Comment by studio500** [comment]
I appear to have solved the issue.
I simply changed my permalink structure saved, and then re saved as per my usual postname structure and all appears in order.
