### ISSUE TITLE
Editor Has Encountered an Unexpected Error....Not Yoast Plugin

### ISSUE THREAD

**Issue by ArchivesofAdventure** [WordPress/gutenberg#9885]
**Describe the bug**
Same error as a few weeks ago, but this time I disabled the Yoast Plugin and it still comes up with this error.

```
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Sg (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:142:327)
    at m (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:12:388)
    at ed (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:65:98)
    at If (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:82:141)
    at v (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:84:389)
    at https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:88:328
    at rd (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:10)
    at O (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:90:455)
    at yh (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:104:145)
    at lg (https://www.archivesofadventure.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)
```

**Comment by designsimply** [comment]
In the report you filed a few weeks ago at #9095 you mentioned the problem was happening for drafts. Can you provide a little bit more detail about that? Is the problem now happening only for drafts or for all posts and pages? 

I also noticed in your report at #9095 you said that clearing browser cache solved the problem in that case, may I confirm with you that you have also tried that step for this case as well?

Do you have other plugins installed which you think might be causing a conflict or are you using any other custom blocks that you know of such as in a theme?

Here is a copy of the error message from the first link for reference:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

I searched for past reports of the same error and I found a few cases where the problem was traced back to problems with how some of the custom code was written:

https://github.com/WordPress/gutenberg/issues/6460#issuecomment-384874544

https://github.com/WordPress/gutenberg/issues/4851#issuecomment-415779624

It may not be the same in your case, and the first thing to check will be to look for a plugin or theme conflict if that is something you are able to do.

**Comment by iandunn** [comment]
Related #9866, where re-saving permalink structure fixed the problem.

**Comment by iandunn** [comment]
Several other reports of this on the forums:

https://wordpress.org/support/topic/nvariant-violation-minified-react-error-130/

**Comment by studio500** [comment]
Try re setting the permalinks

Go to permalinks in settings, change your structure to something other than your default, then save.

Then select your usual default permalink again and save.

Return to your problem pages and check status.

**Comment by youknowriad** [comment]
Closing as stale, if we have more detailed informations about the errors ( `SCRIPT_DEBUG`  set tot true) and reproducible steps, we'll reopen.
